export const AMAN_FAST_FOOD_VENDOR = {
  id: 34,
  name: 'Aman Fast Food',
  slug: 'aman-fast-food',
  phone: '9896481605',
  whatsapp: '9896481605',
  address: 'Near NIT Gate, Right Lane of NIT Gate, Kurukshetra',
  latitude: '29.9678',
  longitude: '76.8821',
  opensAt: '08:00',
  closesAt: '23:00',
  deliversTo: ['NIT Main Gate', 'NIT Back Gate', 'Girls Hostel', 'Boys Hostel', 'Hostel Delivery', 'Right Lane NIT Gate'],
  image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&auto=format&fit=crop&q=80',
  isActive: true,
  isFeatured: true,
  displayOrder: 14,
  createdAt: new Date()
};

export const AMAN_FAST_FOOD_MENU_ITEMS = [
  // ================= ⭐ SPECIALS & POPULAR CURRIES (Category 4) =================
  {
    id: 3601,
    vendorId: 34,
    categoryId: 4,
    name: 'Kadhai Paneer',
    description: 'Fresh cottage cheese cubes cooked with crisp capsicum, onions and kadhai masala',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'kadhai paneer', 'curry', 'bestseller'],
    displayOrder: 1
  },
  {
    id: 3602,
    vendorId: 34,
    categoryId: 4,
    name: 'Dal Makhani',
    description: 'Slow simmered black lentils cooked overnight with butter, fresh cream and spices',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal makhani', 'curry', 'bestseller'],
    displayOrder: 2
  },
  {
    id: 3603,
    vendorId: 34,
    categoryId: 4,
    name: 'Chicken Curry',
    description: 'Desi homestyle flavorful chicken curry cooked in rich aromatic gravy (Half: ₹250 / Full: ₹500)',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken curry', 'curry', 'nonveg', 'bestseller'],
    displayOrder: 3
  },
  {
    id: 3604,
    vendorId: 34,
    categoryId: 4,
    name: 'Chicken Biryani',
    description: 'Aromatic basmati dum biryani layered with spiced chicken and served with gravy',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'chicken biryani', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 4
  },
  {
    id: 3605,
    vendorId: 34,
    categoryId: 4,
    name: 'Aman Special Chicken (Ghar Jaisa)',
    description: 'Homestyle light desi chicken curry prepared with chef special spices',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'special chicken', 'nonveg', 'bestseller'],
    displayOrder: 5
  },
  {
    id: 3606,
    vendorId: 34,
    categoryId: 4,
    name: 'Butter Chicken',
    description: 'Tender roasted chicken simmered in rich creamy tomato butter makhani gravy',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'butter chicken', 'makhani', 'nonveg', 'bestseller'],
    displayOrder: 6
  },
  {
    id: 3607,
    vendorId: 34,
    categoryId: 4,
    name: 'Tawa Chicken',
    description: 'Spiced chicken cooked on high flame tawa with chopped onions and green chilies',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'tawa chicken', 'nonveg'],
    displayOrder: 7
  },
  {
    id: 3608,
    vendorId: 34,
    categoryId: 4,
    name: 'Lemon Chicken',
    description: 'Zesty tangy chicken tossed with freshly squeezed lemon juice and mild spices',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'lemon chicken', 'nonveg'],
    displayOrder: 8
  },
  {
    id: 3609,
    vendorId: 34,
    categoryId: 4,
    name: 'Chilli Chicken',
    description: 'Crisp chicken pieces tossed with capsicum, onion and Indo-Chinese spicy sauces',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chilli chicken', 'chinese', 'nonveg'],
    displayOrder: 9
  },
  {
    id: 3610,
    vendorId: 34,
    categoryId: 4,
    name: 'Afghani Chicken',
    description: 'Mild creamy tandoori chicken cooked in rich cashew and curd marinade',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'afghani chicken', 'nonveg'],
    displayOrder: 10
  },
  {
    id: 3611,
    vendorId: 34,
    categoryId: 4,
    name: 'Chicken Pakoda',
    description: 'Crispy deep-fried golden marinated chicken pakodas served with mint dip',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken pakoda', 'starter', 'nonveg', 'bestseller'],
    displayOrder: 11
  },
  {
    id: 3612,
    vendorId: 34,
    categoryId: 4,
    name: 'Egg Curry (4 Pcs)',
    description: 'Four hard boiled eggs cooked in rich spicy onion tomato curry',
    price: '150.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg curry', 'egg', 'eggs', 'curry', 'protein', 'bestseller'],
    displayOrder: 12
  },

  // ================= 🥘 VEGETARIAN MAIN COURSE (Category 4) =================
  {
    id: 3613,
    vendorId: 34,
    categoryId: 4,
    name: 'Shahi Paneer',
    description: 'Soft cottage cheese cubes cooked in creamy royal cashew-tomato gravy',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'shahi paneer', 'curry', 'bestseller'],
    displayOrder: 13
  },
  {
    id: 3614,
    vendorId: 34,
    categoryId: 4,
    name: 'Paneer Butter Masala',
    description: 'Cottage cheese simmered in smooth butter makhani gravy',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer butter masala', 'curry'],
    displayOrder: 14
  },
  {
    id: 3615,
    vendorId: 34,
    categoryId: 4,
    name: 'Paneer Do Pyaza',
    description: 'Succulent paneer cubes simmered with crunchy double onions and spices',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer do pyaza', 'curry'],
    displayOrder: 15
  },
  {
    id: 3616,
    vendorId: 34,
    categoryId: 4,
    name: 'Paneer Bhurji',
    description: 'Crumbled cottage cheese scrambled with tomatoes, onions and green chilies',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer bhurji', 'curry'],
    displayOrder: 16
  },
  {
    id: 3617,
    vendorId: 34,
    categoryId: 4,
    name: 'Paneer Lababdar',
    description: 'Rich grated and cubed paneer in luscious tomato cream gravy',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer lababdar', 'curry'],
    displayOrder: 17
  },
  {
    id: 3618,
    vendorId: 34,
    categoryId: 4,
    name: 'Matar Paneer',
    description: 'Classic cottage cheese and green peas in spiced homestyle gravy',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'matar paneer', 'curry'],
    displayOrder: 18
  },
  {
    id: 3619,
    vendorId: 34,
    categoryId: 4,
    name: 'Palak Paneer',
    description: 'Fresh spinach puree gravy with cottage cheese cubes tempered with garlic',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'palak paneer', 'curry', 'healthy'],
    displayOrder: 19
  },
  {
    id: 3620,
    vendorId: 34,
    categoryId: 4,
    name: 'Palak Corn',
    description: 'Sweet golden American corn kernels simmered in velvety garlic palak gravy',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['palak corn', 'curry', 'healthy'],
    displayOrder: 20
  },
  {
    id: 3621,
    vendorId: 34,
    categoryId: 4,
    name: 'Soya Chaap Gravy',
    description: 'Tender soya chaap pieces cooked in rich masala gravy',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soya chaap', 'curry', 'bestseller'],
    displayOrder: 21
  },
  {
    id: 3622,
    vendorId: 34,
    categoryId: 4,
    name: 'Malai Kofta',
    description: 'Fried cottage cheese & potato dumplings in rich sweet cashew gravy',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['malai kofta', 'curry'],
    displayOrder: 22
  },
  {
    id: 3623,
    vendorId: 34,
    categoryId: 4,
    name: 'Afghani Paneer',
    description: 'Mild creamy cottage cheese gravy cooked with curd, pepper, and herbs',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['afghani paneer', 'curry'],
    displayOrder: 23
  },
  {
    id: 3624,
    vendorId: 34,
    categoryId: 4,
    name: 'Dal Fry',
    description: 'Yellow lentils tempered with ghee, cumin seeds, garlic, and red chilies',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal fry', 'dal', 'comfort'],
    displayOrder: 24
  },
  {
    id: 3625,
    vendorId: 34,
    categoryId: 4,
    name: 'Yellow Dal Tadka',
    description: 'Homestyle arhar dal double tempered with garlic, tomato, and hing',
    price: '130.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal tadka', 'dal', 'comfort'],
    displayOrder: 25
  },
  {
    id: 3626,
    vendorId: 34,
    categoryId: 4,
    name: 'Mix Veg',
    description: 'Assorted seasonal vegetables tossed with cumin and Indian spices',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix veg', 'curry', 'healthy'],
    displayOrder: 26
  },
  {
    id: 3627,
    vendorId: 34,
    categoryId: 4,
    name: 'Aloo Jeera',
    description: 'Potato cubes sautéed with cumin seeds, turmeric, and fresh coriander',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo jeera', 'subji'],
    displayOrder: 27
  },
  {
    id: 3628,
    vendorId: 34,
    categoryId: 4,
    name: 'Channa Masala',
    description: 'Punjabi style spiced chickpeas simmered in tangy onion-tomato masala',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['channa masala', 'chole', 'curry'],
    displayOrder: 28
  },
  {
    id: 3629,
    vendorId: 34,
    categoryId: 4,
    name: 'Paneer Pyaz Sabzi',
    description: 'Quick dry preparation of paneer tossed with crunchy sautéed onions',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer pyaz', 'under-50'],
    displayOrder: 29
  },

  // ================= 🌯 ROLLS & FAST FOOD =================
  {
    id: 3630,
    vendorId: 34,
    categoryId: 7,
    name: 'Paneer Roll',
    description: 'Crispy flaky paratha wrapped with spiced paneer cubes, onions and mint chutney',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roll', 'paneer roll', 'snack', 'bestseller'],
    displayOrder: 30
  },
  {
    id: 3631,
    vendorId: 34,
    categoryId: 7,
    name: 'Chicken Roll',
    description: 'Golden paratha rolled with seasoned succulent roasted chicken pieces',
    price: '80.00',
    isVeg: false,
    isAvailable: true,
    tags: ['roll', 'chicken roll', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 31
  },
  {
    id: 3632,
    vendorId: 34,
    categoryId: 7,
    name: 'Veg Roll',
    description: 'Paratha wrap loaded with spiced mixed vegetables and tangy sauces',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roll', 'veg roll', 'snack', 'under-50'],
    displayOrder: 32
  },
  {
    id: 3633,
    vendorId: 34,
    categoryId: 7,
    name: 'Egg Roll',
    description: 'Egg coated crisp paratha wrapped with diced onions and chaat masala',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['roll', 'egg roll', 'egg', 'eggs', 'under-50'],
    displayOrder: 33
  },
  {
    id: 3634,
    vendorId: 34,
    categoryId: 1,
    name: 'White Sauce Pasta',
    description: 'Penne pasta tossed in rich creamy cheesy white garlic sauce',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pasta', 'white sauce', 'bestseller'],
    displayOrder: 34
  },
  {
    id: 3635,
    vendorId: 34,
    categoryId: 1,
    name: 'French Fries',
    description: 'Crispy golden potato salted french fries',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fries', 'french fries', 'snack'],
    displayOrder: 35
  },
  {
    id: 3636,
    vendorId: 34,
    categoryId: 2,
    name: 'Veg Chowmein / Hakka Noodles',
    description: 'Wok tossed noodles with shredded cabbage, carrots, bell pepper, and soy sauce',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chowmein', 'noodles', 'chinese', 'bestseller'],
    displayOrder: 36
  },
  {
    id: 3637,
    vendorId: 34,
    categoryId: 1,
    name: 'Veg Maggi',
    description: 'Classic masala Maggi tossed with chopped onions, tomatoes, and vegetables',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'veg maggi', 'under-50'],
    displayOrder: 37
  },
  {
    id: 3638,
    vendorId: 34,
    categoryId: 1,
    name: 'Fried Maggi',
    description: 'Crispy pan-fried Maggi noodles tossed with desi tadka spices',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'fried maggi'],
    displayOrder: 38
  },

  // ================= 🫓 BREAKFAST & PARATHAS =================
  {
    id: 3639,
    vendorId: 34,
    categoryId: 8,
    name: 'Aloo Paratha',
    description: 'Whole wheat tawa paratha stuffed with spicy mashed potatoes and butter',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'aloo paratha', 'breakfast', 'under-50', 'bestseller'],
    displayOrder: 39
  },
  {
    id: 3640,
    vendorId: 34,
    categoryId: 8,
    name: 'Plain Paratha',
    description: 'Layered tawa paratha brushed with fresh butter',
    price: '25.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'plain paratha', 'under-50'],
    displayOrder: 40
  },
  {
    id: 3641,
    vendorId: 34,
    categoryId: 8,
    name: 'Gobhi Paratha',
    description: 'Grated spiced cauliflower stuffed tawa paratha',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'gobhi paratha', 'under-50'],
    displayOrder: 41
  },
  {
    id: 3642,
    vendorId: 34,
    categoryId: 8,
    name: 'Onion Paratha',
    description: 'Crispy paratha filled with seasoned crunchy chopped onions',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'onion paratha', 'under-50'],
    displayOrder: 42
  },
  {
    id: 3643,
    vendorId: 34,
    categoryId: 8,
    name: 'Paneer Paratha',
    description: 'Rich tawa paratha packed with freshly grated seasoned cottage cheese',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'paneer paratha', 'under-50', 'bestseller'],
    displayOrder: 43
  },
  {
    id: 3644,
    vendorId: 34,
    categoryId: 8,
    name: 'Paneer Onion Paratha',
    description: 'Stuffed paratha with cottage cheese and crunchy spiced onions',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'paneer onion', 'under-50'],
    displayOrder: 44
  },
  {
    id: 3645,
    vendorId: 34,
    categoryId: 8,
    name: 'Egg Paratha',
    description: 'Layered paratha cooked with fluffy egg and spices',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['paratha', 'egg paratha', 'egg', 'eggs', 'under-50'],
    displayOrder: 45
  },
  {
    id: 3646,
    vendorId: 34,
    categoryId: 8,
    name: 'Mix Paratha',
    description: 'Stuffed paratha with potatoes, paneer, onions, and cauliflower',
    price: '45.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'mix paratha', 'under-50'],
    displayOrder: 46
  },
  {
    id: 3647,
    vendorId: 34,
    categoryId: 7,
    name: 'Omelette',
    description: 'Double egg fluffy classic masala omelet with green chilies and onions',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['omelet', 'egg', 'eggs', 'under-50'],
    displayOrder: 47
  },
  {
    id: 3648,
    vendorId: 34,
    categoryId: 7,
    name: 'Bread Omelette',
    description: 'Toasted bread sandwiched with double egg masala omelet',
    price: '60.00',
    isVeg: false,
    isAvailable: true,
    tags: ['bread omelet', 'egg', 'eggs', 'breakfast', 'bestseller'],
    displayOrder: 48
  },
  {
    id: 3649,
    vendorId: 34,
    categoryId: 7,
    name: 'Boiled Egg (2 Pcs)',
    description: 'Two farm fresh hard boiled eggs served with chaat masala and black pepper',
    price: '30.00',
    isVeg: false,
    isAvailable: true,
    tags: ['boiled egg', 'egg', 'eggs', 'protein', 'under-50'],
    displayOrder: 49
  },
  {
    id: 3650,
    vendorId: 34,
    categoryId: 8,
    name: 'Poha',
    description: 'Light flattened rice tempered with mustard seeds, curry leaves and peanuts',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['poha', 'breakfast', 'under-50'],
    displayOrder: 50
  },
  {
    id: 3651,
    vendorId: 34,
    categoryId: 4,
    name: 'Litti (1 Pc)',
    description: 'Traditional wood-baked sattu litti with desi ghee (Order 1 day in advance)',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['litti', 'desi', 'under-50'],
    displayOrder: 51
  },

  // ================= 🫓 TAWA ROTIS & BREADS =================
  {
    id: 3652,
    vendorId: 34,
    categoryId: 4,
    name: 'Tawa Roti',
    description: 'Fresh hot whole wheat tawa phulka',
    price: '10.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'phulka', 'under-50'],
    displayOrder: 52
  },
  {
    id: 3653,
    vendorId: 34,
    categoryId: 4,
    name: 'Butter Roti',
    description: 'Tawa roti brushed with pure amul butter',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'butter roti', 'under-50'],
    displayOrder: 53
  },
  {
    id: 3654,
    vendorId: 34,
    categoryId: 4,
    name: 'Laccha Paratha',
    description: 'Multi-layered crispy flaky whole wheat paratha brushed with ghee',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'laccha paratha', 'under-50'],
    displayOrder: 54
  },
  {
    id: 3655,
    vendorId: 34,
    categoryId: 4,
    name: 'Rumali Roti',
    description: 'Ultra thin soft handkerchief style bread',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rumali roti', 'under-50'],
    displayOrder: 55
  },

  // ================= 🍚 RICE & BIRYANIS =================
  {
    id: 3656,
    vendorId: 34,
    categoryId: 4,
    name: 'Veg Rice',
    description: 'Steamed basmati rice tossed with fresh seasonal vegetables',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'veg rice'],
    displayOrder: 56
  },
  {
    id: 3657,
    vendorId: 34,
    categoryId: 4,
    name: 'Egg Rice',
    description: 'Basmati rice cooked with scrambled eggs, onions and mild spices',
    price: '150.00',
    isVeg: false,
    isAvailable: true,
    tags: ['rice', 'egg rice', 'egg', 'eggs'],
    displayOrder: 57
  },
  {
    id: 3658,
    vendorId: 34,
    categoryId: 4,
    name: 'Veg Biryani',
    description: 'Spiced aromatic dum basmati rice layered with vegetables',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['biryani', 'veg biryani'],
    displayOrder: 58
  },
  {
    id: 3659,
    vendorId: 34,
    categoryId: 4,
    name: 'Egg Biryani',
    description: 'Fragrant dum biryani served with spiced hard boiled eggs',
    price: '160.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'egg biryani', 'egg', 'eggs'],
    displayOrder: 59
  },
  {
    id: 3660,
    vendorId: 34,
    categoryId: 4,
    name: 'Jeera Rice',
    description: 'Fragrant basmati rice tempered with roasted cumin and ghee',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'jeera rice'],
    displayOrder: 60
  },
  {
    id: 3661,
    vendorId: 34,
    categoryId: 4,
    name: 'Paneer Rice',
    description: 'Basmati rice tossed with tender spiced cottage cheese cubes',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'paneer rice'],
    displayOrder: 61
  },

  // ================= 🥣 RAITA & PAPAD =================
  {
    id: 3662,
    vendorId: 34,
    categoryId: 4,
    name: 'Boondi Raita',
    description: 'Chilled spiced yogurt with crispy gram flour boondi and roasted cumin',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'boondi raita'],
    displayOrder: 62
  },
  {
    id: 3663,
    vendorId: 34,
    categoryId: 4,
    name: 'Mix Veg Raita',
    description: 'Creamy curd mixed with finely diced cucumber, tomato and onions',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'mix raita'],
    displayOrder: 63
  },
  {
    id: 3664,
    vendorId: 34,
    categoryId: 4,
    name: 'Pineapple Raita',
    description: 'Sweet and savory yogurt tossed with juicy pineapple bits',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'pineapple raita'],
    displayOrder: 64
  },
  {
    id: 3665,
    vendorId: 34,
    categoryId: 4,
    name: 'Masala Papad (2 Pcs)',
    description: 'Crispy papad topped with chopped onions, tomatoes, green chilies, and chaat masala',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['papad', 'masala papad', 'under-50'],
    displayOrder: 65
  },

  // ================= 🍱 TIFFIN SERVICES =================
  {
    id: 3666,
    vendorId: 34,
    categoryId: 4,
    name: 'Breakfast Tiffin Combo',
    description: 'Complete morning breakfast with 2 Stuffed Parathas + 1 Cup Dahi + 1 Hot Tea or Coffee',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tiffin', 'breakfast', 'combo', 'bestseller'],
    displayOrder: 66
  },
  {
    id: 3667,
    vendorId: 34,
    categoryId: 4,
    name: 'Lunch Tiffin Meal',
    description: 'Nutritious homestyle lunch with Dal, Seasonal Sabzi, 4 Butter Roti, Rice, and Salad',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tiffin', 'lunch', 'meal', 'bestseller'],
    displayOrder: 67
  },
  {
    id: 3668,
    vendorId: 34,
    categoryId: 4,
    name: 'Dinner Tiffin Meal',
    description: 'Fresh evening dinner with Dal Makhani, Paneer or Sabzi, 4 Butter Roti, Rice, and Salad',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tiffin', 'dinner', 'meal', 'bestseller'],
    displayOrder: 68
  },

  // ================= ☕ BEVERAGES & SHAKES =================
  {
    id: 3669,
    vendorId: 34,
    categoryId: 8,
    name: 'Kadak Chai (Tea)',
    description: 'Freshly brewed hot milk tea with ginger and cardamom',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tea', 'chai', 'hot beverage', 'under-50'],
    displayOrder: 69
  },
  {
    id: 3670,
    vendorId: 34,
    categoryId: 8,
    name: 'Hot Coffee',
    description: 'Steaming frothy aromatic milk coffee',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['coffee', 'hot coffee', 'under-50'],
    displayOrder: 70
  },
  {
    id: 3671,
    vendorId: 34,
    categoryId: 3,
    name: 'Lemon Soda',
    description: 'Chilled fizzy soda with lemon juice, mint, and black salt',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soda', 'lemon soda', 'beverage', 'under-50'],
    displayOrder: 71
  },
  {
    id: 3672,
    vendorId: 34,
    categoryId: 3,
    name: 'Banana Shake',
    description: 'Nutritious thick banana milk shake',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'banana shake', 'under-50'],
    displayOrder: 72
  },
  {
    id: 3673,
    vendorId: 34,
    categoryId: 3,
    name: 'Mango Shake',
    description: 'Sweet thick mango pulp shake with chilled milk',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'mango shake', 'under-50'],
    displayOrder: 73
  },

  // ================= 🍧 SNACKS & DESSERTS =================
  {
    id: 3674,
    vendorId: 34,
    categoryId: 6,
    name: 'Gulab Jamun (2 Pcs)',
    description: 'Two soft warm khoya gulab jamuns soaked in aromatic sugar syrup',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['gulab jamun', 'dessert', 'sweet', 'under-50', 'bestseller'],
    displayOrder: 74
  },
  {
    id: 3675,
    vendorId: 34,
    categoryId: 8,
    name: 'Bhel Puri',
    description: 'Crispy puffed rice tossed with potatoes, sev, chopped onions and tangy tamarind chutney',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['bhel', 'chaat', 'snack'],
    displayOrder: 75
  },
  {
    id: 3676,
    vendorId: 34,
    categoryId: 8,
    name: 'Peanut Masala',
    description: 'Roasted crunchy peanuts tossed with onions, green chilies, chaat masala and lemon juice',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['peanut masala', 'snack', 'chakna'],
    displayOrder: 76
  }
];
