export const BAKERS_BITE_KKR_VENDOR = {
  id: 29,
  name: 'Bakers Bite KKR',
  slug: 'bakers-bite-kkr',
  phone: '7027052525',
  whatsapp: '7027052525',
  address: 'Near NIT Kurukshetra, Kurukshetra',
  latitude: '29.9680',
  longitude: '76.8820',
  opensAt: '10:00',
  closesAt: '21:30',
  deliversTo: ['NITKKR campus all'],
  image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&auto=format&fit=crop&q=80',
  isActive: true,
  isFeatured: true,
  displayOrder: 9,
  createdAt: new Date()
};

export const BAKERS_BITE_KKR_MENU_ITEMS = [
  // ================= 🍰 PASTRIES (Category 6 - Desserts & Sweets) =================
  {
    id: 3001,
    vendorId: 29,
    categoryId: 6,
    name: 'Pineapple Pastry',
    description: 'Fresh whipped cream pastry layered with sweet pineapple compote and cherries',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pastry', 'pineapple', 'dessert', 'cake', 'bestseller'],
    displayOrder: 1
  },
  {
    id: 3002,
    vendorId: 29,
    categoryId: 6,
    name: 'Black Forest Pastry',
    description: 'Classic chocolate sponge layered with whipped cream, sour cherries and dark chocolate shavings',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pastry', 'black forest', 'chocolate', 'dessert', 'bestseller'],
    displayOrder: 2
  },
  {
    id: 3003,
    vendorId: 29,
    categoryId: 6,
    name: 'Butterscotch Pastry',
    description: 'Caramel crunch sponge with butterscotch cream and praline bits',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pastry', 'butterscotch', 'caramel', 'dessert'],
    displayOrder: 3
  },
  {
    id: 3004,
    vendorId: 29,
    categoryId: 6,
    name: 'Choco Crunch Pastry',
    description: 'Rich dark chocolate pastry filled with crunchy chocolate pearls and ganache',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pastry', 'choco crunch', 'chocolate', 'crunchy'],
    displayOrder: 4
  },
  {
    id: 3005,
    vendorId: 29,
    categoryId: 6,
    name: 'White Forest Pastry',
    description: 'Vanilla sponge layered with white chocolate ganache, whipped cream and cherries',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pastry', 'white forest', 'white chocolate'],
    displayOrder: 5
  },
  {
    id: 3006,
    vendorId: 29,
    categoryId: 6,
    name: 'Red Velvet Pastry',
    description: 'Velvety crimson sponge with signature smooth cream cheese frosting',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pastry', 'red velvet', 'dessert', 'bestseller'],
    displayOrder: 6
  },
  {
    id: 3007,
    vendorId: 29,
    categoryId: 6,
    name: 'Choco Truffle Pastry',
    description: 'Decadent pure chocolate truffle pastry coated in silky chocolate ganache',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pastry', 'truffle', 'choco truffle', 'chocolate', 'bestseller'],
    displayOrder: 7
  },
  {
    id: 3008,
    vendorId: 29,
    categoryId: 6,
    name: 'Death By Chocolate Pastry',
    description: 'Loaded multi-layer chocolate pastry for extreme chocolate lovers',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pastry', 'death by chocolate', 'chocolate', 'heavy'],
    displayOrder: 8
  },
  {
    id: 3009,
    vendorId: 29,
    categoryId: 6,
    name: 'Blueberry Pastry',
    description: 'Fluffy sponge filled with tart blueberry filling and light frosting',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pastry', 'blueberry', 'fruit', 'dessert'],
    displayOrder: 9
  },
  {
    id: 3010,
    vendorId: 29,
    categoryId: 6,
    name: 'Chocolate Red Velvet Pastry',
    description: 'Dual layer combination of rich chocolate sponge and classic red velvet',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pastry', 'chocolate', 'red velvet'],
    displayOrder: 10
  },

  // ================= 🍩 DESSERTS & BROWNIES (Category 6) =================
  {
    id: 3011,
    vendorId: 29,
    categoryId: 6,
    name: 'Chocolate Ball',
    description: 'Fudgy cake pop chocolate ball rolled in rich dark chocolate truffle',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dessert', 'chocolate ball', 'snack', 'under-50'],
    displayOrder: 11
  },
  {
    id: 3012,
    vendorId: 29,
    categoryId: 6,
    name: 'Choco Lava Cup Cake',
    description: 'Warm chocolate cupcake with molten gooey molten lava core',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['choco lava', 'cupcake', 'lava cake', 'dessert', 'bestseller', 'under-50'],
    displayOrder: 12
  },
  {
    id: 3013,
    vendorId: 29,
    categoryId: 6,
    name: 'Chocolate Doughnut',
    description: 'Soft and fluffy fried doughnut glazed with thick dark chocolate coating',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['doughnut', 'donut', 'chocolate', 'dessert'],
    displayOrder: 13
  },
  {
    id: 3014,
    vendorId: 29,
    categoryId: 6,
    name: 'Choco Walnut Brownie',
    description: 'Dense fudgy dark chocolate brownie loaded with toasted crunchy walnuts',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['brownie', 'choco walnut', 'walnut brownie', 'bestseller'],
    displayOrder: 14
  },
  {
    id: 3015,
    vendorId: 29,
    categoryId: 6,
    name: 'Choco Walnut Pie',
    description: 'Crispy buttery crust filled with rich chocolate fudge and walnut topping',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pie', 'choco pie', 'walnut pie', 'dessert'],
    displayOrder: 15
  },

  // ================= 🧁 MUFFINS (Category 6) =================
  {
    id: 3016,
    vendorId: 29,
    categoryId: 6,
    name: 'Vanilla Muffin',
    description: 'Soft, golden fluffy baked vanilla tea-time muffin',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['muffin', 'vanilla muffin', 'bakery', 'under-50'],
    displayOrder: 16
  },
  {
    id: 3017,
    vendorId: 29,
    categoryId: 6,
    name: 'Tutti Frutti Muffin',
    description: 'Classic sweet bakery muffin studded with colorful candied fruits',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['muffin', 'tutti frutti', 'bakery', 'under-50'],
    displayOrder: 17
  },
  {
    id: 3018,
    vendorId: 29,
    categoryId: 6,
    name: 'Choco Chips Muffin',
    description: 'Fluffy chocolate muffin studded with real dark chocolate chips',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['muffin', 'choco chips', 'chocolate muffin', 'under-50'],
    displayOrder: 18
  },
  {
    id: 3019,
    vendorId: 29,
    categoryId: 6,
    name: 'Choco Walnut Muffin',
    description: 'Rich chocolate muffin topped with chopped California walnuts',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['muffin', 'choco walnut', 'walnut muffin', 'under-50'],
    displayOrder: 19
  },
  {
    id: 3020,
    vendorId: 29,
    categoryId: 6,
    name: 'Blueberry Muffin',
    description: 'Moist vanilla muffin bursting with juicy wild blueberries',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['muffin', 'blueberry muffin', 'under-50'],
    displayOrder: 20
  },
  {
    id: 3021,
    vendorId: 29,
    categoryId: 6,
    name: 'Red Velvet Muffin',
    description: 'Soft crimson cocoa muffin with a hint of vanilla sweetness',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['muffin', 'red velvet', 'under-50'],
    displayOrder: 21
  },

  // ================= 🧋 SHAKES & COLD COFFEE (Category 3) =================
  {
    id: 3022,
    vendorId: 29,
    categoryId: 3,
    name: 'Pineapple Shake',
    description: 'Thick creamy blended milk shake with sweet tropical pineapple flavor',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'pineapple shake', 'beverage'],
    displayOrder: 22
  },
  {
    id: 3023,
    vendorId: 29,
    categoryId: 3,
    name: 'Mango Shake',
    description: 'Chilled rich shake made with sweet Alphonso mango pulp and vanilla ice cream',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'mango shake', 'beverage', 'bestseller'],
    displayOrder: 23
  },
  {
    id: 3024,
    vendorId: 29,
    categoryId: 3,
    name: 'Strawberry Shake',
    description: 'Pink creamy shake flavored with luscious strawberries',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'strawberry shake', 'beverage'],
    displayOrder: 24
  },
  {
    id: 3025,
    vendorId: 29,
    categoryId: 3,
    name: 'Blueberry Shake',
    description: 'Thick shake made with rich blueberry fruit crush and cold milk',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'blueberry shake', 'beverage'],
    displayOrder: 25
  },
  {
    id: 3026,
    vendorId: 29,
    categoryId: 3,
    name: 'Chocolate Shake',
    description: 'Thick chocolate fudge shake topped with chocolate syrup',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'chocolate shake', 'beverage', 'bestseller'],
    displayOrder: 26
  },
  {
    id: 3027,
    vendorId: 29,
    categoryId: 3,
    name: 'Thick Cold Coffee',
    description: 'Creamy frothy chilled cold coffee made with rich espresso blend',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['coffee', 'cold coffee', 'beverage', 'bestseller'],
    displayOrder: 27
  },

  // ================= 🎂 CELEBRATION CAKES (Category 6) =================
  {
    id: 3028,
    vendorId: 29,
    categoryId: 6,
    name: 'Pineapple Cake',
    description: 'Fresh cream cake layered with juicy pineapple compote (Half KG: ₹340 / 1 KG: ₹660)',
    price: '340.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'pineapple cake', 'birthday', 'bestseller'],
    displayOrder: 28
  },
  {
    id: 3029,
    vendorId: 29,
    categoryId: 6,
    name: 'Vanilla Cake',
    description: 'Classic light and fluffy vanilla celebration sponge (Half KG: ₹340 / 1 KG: ₹660)',
    price: '340.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'vanilla cake', 'birthday'],
    displayOrder: 29
  },
  {
    id: 3030,
    vendorId: 29,
    categoryId: 6,
    name: 'Mango Cake',
    description: 'Tropical mango celebration cake layered with sweet mango cream (Half KG: ₹340 / 1 KG: ₹660)',
    price: '340.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'mango cake', 'fruit cake'],
    displayOrder: 30
  },
  {
    id: 3031,
    vendorId: 29,
    categoryId: 6,
    name: 'Strawberry Cake',
    description: 'Delicate strawberry cream cake with pink frosting (Half KG: ₹340 / 1 KG: ₹660)',
    price: '340.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'strawberry cake', 'birthday'],
    displayOrder: 31
  },
  {
    id: 3032,
    vendorId: 29,
    categoryId: 6,
    name: 'Butterscotch Cake',
    description: 'Caramel crunch cake with butterscotch praline and whipped cream (Half KG: ₹360 / 1 KG: ₹680)',
    price: '360.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'butterscotch cake', 'bestseller'],
    displayOrder: 32
  },
  {
    id: 3033,
    vendorId: 29,
    categoryId: 6,
    name: 'Choco Vanilla Cake',
    description: 'Half-and-half dual flavor fusion of rich chocolate and vanilla (Half KG: ₹360 / 1 KG: ₹680)',
    price: '360.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'choco vanilla', 'chocolate cake'],
    displayOrder: 33
  },
  {
    id: 3034,
    vendorId: 29,
    categoryId: 6,
    name: 'Choco Strawberry Cake',
    description: 'Decadent chocolate sponge layered with sweet strawberry cream (Half KG: ₹360 / 1 KG: ₹680)',
    price: '360.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'choco strawberry', 'chocolate cake'],
    displayOrder: 34
  },
  {
    id: 3035,
    vendorId: 29,
    categoryId: 6,
    name: 'Choco Butterscotch Cake',
    description: 'Chocolate and crunchy butterscotch praline combination (Half KG: ₹360 / 1 KG: ₹680)',
    price: '360.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'choco butterscotch', 'chocolate cake'],
    displayOrder: 35
  },
  {
    id: 3036,
    vendorId: 29,
    categoryId: 6,
    name: 'Black Forest Cake',
    description: 'All-time favorite chocolate sponge layered with cherries and chocolate flakes (Half KG: ₹380 / 1 KG: ₹720)',
    price: '380.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'black forest cake', 'birthday', 'bestseller'],
    displayOrder: 36
  },
  {
    id: 3037,
    vendorId: 29,
    categoryId: 6,
    name: 'Light Chocolate Cake',
    description: 'Mild milk chocolate sponge with light chocolate mousse cream (Half KG: ₹380 / 1 KG: ₹720)',
    price: '380.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'chocolate cake', 'light chocolate'],
    displayOrder: 37
  },
  {
    id: 3038,
    vendorId: 29,
    categoryId: 6,
    name: 'Vanilla Chips Cake',
    description: 'Fluffy vanilla cake filled with crunchy white and dark chocolate chips (Half KG: ₹380 / 1 KG: ₹720)',
    price: '380.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'vanilla chips', 'choco chips'],
    displayOrder: 38
  },
  {
    id: 3039,
    vendorId: 29,
    categoryId: 6,
    name: 'Caramel Cake',
    description: 'Rich golden caramel sponge drizzled with buttery caramel glaze (Half KG: ₹380 / 1 KG: ₹720)',
    price: '380.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'caramel cake', 'dessert'],
    displayOrder: 39
  },
  {
    id: 3040,
    vendorId: 29,
    categoryId: 6,
    name: 'Choco Crunch Cake',
    description: 'Crispy chocolate pearls and rich cocoa cream layered cake (Half KG: ₹380 / 1 KG: ₹720)',
    price: '380.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'choco crunch', 'chocolate cake'],
    displayOrder: 40
  },
  {
    id: 3041,
    vendorId: 29,
    categoryId: 6,
    name: 'White Forest Cake',
    description: 'Vanilla sponge decorated with snowy white chocolate curls and red cherries (Half KG: ₹380 / 1 KG: ₹720)',
    price: '380.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'white forest', 'birthday'],
    displayOrder: 41
  },
  {
    id: 3042,
    vendorId: 29,
    categoryId: 6,
    name: 'Paan Flavor Cake',
    description: 'Special refreshing Indian paan flavored cake with gulkand filling (Half KG: ₹400 / 1 KG: ₹750)',
    price: '400.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'paan cake', 'fusion'],
    displayOrder: 42
  },
  {
    id: 3043,
    vendorId: 29,
    categoryId: 6,
    name: 'Coffee Cake',
    description: 'Aromatic mocha coffee cake for coffee lovers (Half KG: ₹400 / 1 KG: ₹750)',
    price: '400.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'coffee cake', 'mocha'],
    displayOrder: 43
  },
  {
    id: 3044,
    vendorId: 29,
    categoryId: 6,
    name: 'KitKat Cake',
    description: 'Loaded chocolate cake topped and surrounded with crunchy KitKat bars (Half KG: ₹450 / 1 KG: ₹850)',
    price: '450.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'kitkat cake', 'chocolate', 'bestseller'],
    displayOrder: 44
  },
  {
    id: 3045,
    vendorId: 29,
    categoryId: 6,
    name: 'Cassata Cake',
    description: 'Multi-flavor layered Sicilian style cake with tutti frutti and nuts (Half KG: ₹450 / 1 KG: ₹850)',
    price: '450.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'cassata cake', 'nuts'],
    displayOrder: 45
  },
  {
    id: 3046,
    vendorId: 29,
    categoryId: 6,
    name: 'Truffle Cake',
    description: 'Pure dark chocolate truffle cake with dense silky ganache (Half KG: ₹400 / 1 KG: ₹750)',
    price: '400.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'truffle cake', 'chocolate', 'bestseller'],
    displayOrder: 46
  },
  {
    id: 3047,
    vendorId: 29,
    categoryId: 6,
    name: 'Red Velvet Cake',
    description: 'Premium crimson red velvet cake with rich cream cheese frosting (Half KG: ₹400 / 1 KG: ₹750)',
    price: '400.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'red velvet cake', 'birthday', 'bestseller'],
    displayOrder: 47
  },
  {
    id: 3048,
    vendorId: 29,
    categoryId: 6,
    name: 'Blueberry Cake',
    description: 'Exquisite blueberry cake loaded with fruit compote and purple glaze (Half KG: ₹450 / 1 KG: ₹850)',
    price: '450.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'blueberry cake', 'fruit cake'],
    displayOrder: 48
  },
  {
    id: 3049,
    vendorId: 29,
    categoryId: 6,
    name: 'Mix Fruit Cake',
    description: 'Fresh seasonal sliced kiwi, apple, grapes and cherries topped vanilla cake (Half KG: ₹450 / 1 KG: ₹850)',
    price: '450.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'mix fruit cake', 'fresh fruit', 'bestseller'],
    displayOrder: 49
  },
  {
    id: 3050,
    vendorId: 29,
    categoryId: 6,
    name: 'Oreo Cake',
    description: 'Cookies and cream cake loaded with crushed Oreo cookies (Half KG: ₹450 / 1 KG: ₹850)',
    price: '450.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'oreo cake', 'chocolate', 'bestseller'],
    displayOrder: 50
  },
  {
    id: 3051,
    vendorId: 29,
    categoryId: 6,
    name: 'Death By Chocolate Cake',
    description: 'Ultra rich triple chocolate layers with melted fudge and choco gems (Half KG: ₹450 / 1 KG: ₹850)',
    price: '450.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'death by chocolate', 'chocolate cake', 'bestseller'],
    displayOrder: 51
  },
  {
    id: 3052,
    vendorId: 29,
    categoryId: 6,
    name: 'Mud Cake',
    description: 'Heavy dense dark chocolate mud cake with fudgy crumb (Half KG: ₹450 / 1 KG: ₹850)',
    price: '450.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'mud cake', 'chocolate'],
    displayOrder: 52
  },
  {
    id: 3053,
    vendorId: 29,
    categoryId: 6,
    name: 'Choco Red Velvet Cake',
    description: 'Best of both worlds: chocolate fudge and red velvet layered celebration cake (Half KG: ₹450 / 1 KG: ₹850)',
    price: '450.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'choco red velvet'],
    displayOrder: 53
  },
  {
    id: 3054,
    vendorId: 29,
    categoryId: 6,
    name: 'Choco Walnut Cake',
    description: 'Rich chocolate ganache cake generously studded with crunchy walnuts (Half KG: ₹550 / 1 KG: ₹980)',
    price: '550.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'choco walnut cake', 'walnut cake'],
    displayOrder: 54
  },
  {
    id: 3055,
    vendorId: 29,
    categoryId: 6,
    name: 'Rasmalai Cake',
    description: 'Royal Indian fusion cake soaked in saffron cardamom milk and soft rasmalai pieces (Half KG: ₹500 / 1 KG: ₹950)',
    price: '500.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cake', 'rasmalai cake', 'fusion', 'bestseller'],
    displayOrder: 55
  }
];
