export const CAFE_AROMA_VENDOR = {
  id: 32,
  name: 'Cafe Aroma',
  slug: 'cafe-aroma',
  phone: '7027981103',
  whatsapp: '7027981103',
  address: 'Opp. NIT Gate, Kirmach Road, Kurukshetra',
  latitude: '29.9672',
  longitude: '76.8824',
  opensAt: '10:00',
  closesAt: '23:00',
  deliversTo: ['NIT Main Gate', 'NIT Back Gate', 'Girls Hostel', 'Boys Hostel', 'Kirmach Road', 'Hostel Delivery'],
  image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80',
  isActive: true,
  isFeatured: true,
  displayOrder: 12,
  createdAt: new Date()
};

export const CAFE_AROMA_MENU_ITEMS = [
  // ================= 🍟 FRIES (Category 1 - Fast Food) =================
  {
    id: 3301,
    vendorId: 32,
    categoryId: 1,
    name: 'French Fries',
    description: 'Crispy golden classic salted potato fries',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fries', 'french fries', 'snack', 'bestseller'],
    displayOrder: 1
  },
  {
    id: 3302,
    vendorId: 32,
    categoryId: 1,
    name: 'Peri Peri Fries',
    description: 'Crispy fries tossed in zesty spicy peri peri seasoning',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fries', 'peri peri', 'spicy', 'bestseller'],
    displayOrder: 2
  },
  {
    id: 3303,
    vendorId: 32,
    categoryId: 1,
    name: 'Peri Peri Loaded Fries',
    description: 'Loaded fries drizzled with melted cheese sauce, jalapenos and peri peri spice',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fries', 'loaded fries', 'cheese', 'bestseller'],
    displayOrder: 3
  },
  {
    id: 3304,
    vendorId: 32,
    categoryId: 1,
    name: 'Salted Fries',
    description: 'Lightly salted golden potato fries',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fries', 'snack'],
    displayOrder: 4
  },

  // ================= 🥪 SANDWICHES (Category 1) =================
  {
    id: 3305,
    vendorId: 32,
    categoryId: 1,
    name: 'Paneer Tikka Sandwich',
    description: 'Grilled sandwich stuffed with smoky tandoori paneer tikka and mint mayo',
    price: '130.00',
    isVeg: true,
    isAvailable: true,
    tags: ['sandwich', 'paneer tikka', 'grilled', 'bestseller'],
    displayOrder: 5
  },
  {
    id: 3306,
    vendorId: 32,
    categoryId: 1,
    name: 'Vegetable Sandwich',
    description: 'Double decker toasted sandwich with cucumber, tomato, potato and chutney',
    price: '110.00',
    isVeg: true,
    isAvailable: true,
    tags: ['sandwich', 'veg sandwich', 'healthy'],
    displayOrder: 6
  },
  {
    id: 3307,
    vendorId: 32,
    categoryId: 1,
    name: 'Cheese Onion Sandwich',
    description: 'Crisp toasted bread filled with melted cheese and chopped onions',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['sandwich', 'cheese onion', 'under-50'],
    displayOrder: 7
  },
  {
    id: 3308,
    vendorId: 32,
    categoryId: 1,
    name: 'Cheese Tomato Sandwich',
    description: 'Toasted sandwich with juicy tomatoes, herbs and melted cheese',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['sandwich', 'cheese tomato', 'under-50'],
    displayOrder: 8
  },
  {
    id: 3309,
    vendorId: 32,
    categoryId: 1,
    name: 'Cheese Capsicum Sandwich',
    description: 'Crunchy green capsicum and melted cheese in golden toasted bread',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['sandwich', 'cheese capsicum', 'under-50'],
    displayOrder: 9
  },
  {
    id: 3310,
    vendorId: 32,
    categoryId: 1,
    name: 'Cheese Corn Sandwich',
    description: 'Sweet golden corn kernels mixed with melted mozzarella cheese',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['sandwich', 'cheese corn', 'under-50', 'bestseller'],
    displayOrder: 10
  },

  // ================= 🍔 BURGER (Category 1) =================
  {
    id: 3311,
    vendorId: 32,
    categoryId: 1,
    name: 'Aloo Tikki Burger',
    description: 'Crispy potato patty with onion slices and tangy burger sauce',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['burger', 'aloo tikki', 'under-50', 'bestseller'],
    displayOrder: 11
  },
  {
    id: 3312,
    vendorId: 32,
    categoryId: 1,
    name: 'Veg. Tikki Burger',
    description: 'Assorted vegetable patty burger layered with tomatoes and creamy spread',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['burger', 'veg burger'],
    displayOrder: 12
  },
  {
    id: 3313,
    vendorId: 32,
    categoryId: 1,
    name: 'Egg Tikki Burger',
    description: 'Juicy egg patty burger with fresh onions and mayo',
    price: '70.00',
    isVeg: false,
    isAvailable: true,
    tags: ['burger', 'egg burger', 'egg', 'eggs', 'protein'],
    displayOrder: 13
  },
  {
    id: 3314,
    vendorId: 32,
    categoryId: 1,
    name: 'Spicy Paneer Burger',
    description: 'Crispy spiced cottage cheese patty with fiery chili mayo and lettuce',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['burger', 'paneer burger', 'spicy', 'bestseller'],
    displayOrder: 14
  },
  {
    id: 3315,
    vendorId: 32,
    categoryId: 1,
    name: 'Makhani Burger',
    description: 'Rich fusion burger smothered in authentic butter makhani gravy',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['burger', 'makhani burger', 'bestseller'],
    displayOrder: 15
  },
  {
    id: 3316,
    vendorId: 32,
    categoryId: 1,
    name: 'Jumbo Burger (Special)',
    description: 'Massive double-layer special burger with double patty, extra cheese and fries',
    price: '149.00',
    isVeg: true,
    isAvailable: true,
    tags: ['burger', 'jumbo burger', 'loaded', 'bestseller'],
    displayOrder: 16
  },

  // ================= 🌯 ROLLS & MOMOS (Category 7 & 2) =================
  {
    id: 3317,
    vendorId: 32,
    categoryId: 7,
    name: 'Paneer Roll',
    description: 'Soft paratha wrap loaded with spiced cottage cheese cubes and sauces',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roll', 'paneer roll', 'bestseller'],
    displayOrder: 17
  },
  {
    id: 3318,
    vendorId: 32,
    categoryId: 7,
    name: 'Veg. Roll',
    description: 'Crisp paratha rolled with seasoned shredded vegetables and tangy mint chutney',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roll', 'veg roll', 'under-50'],
    displayOrder: 18
  },
  {
    id: 3319,
    vendorId: 32,
    categoryId: 7,
    name: 'Egg Roll',
    description: 'Egg coated flaky paratha wrapped with crunchy onions and sauces',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['roll', 'egg roll', 'egg', 'eggs', 'under-50'],
    displayOrder: 19
  },
  {
    id: 3320,
    vendorId: 32,
    categoryId: 7,
    name: 'Chicken Roll',
    description: 'Tender spiced roasted chicken chunks wrapped in golden crisp paratha',
    price: '80.00',
    isVeg: false,
    isAvailable: true,
    tags: ['roll', 'chicken roll', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 20
  },
  {
    id: 3321,
    vendorId: 32,
    categoryId: 2,
    name: 'Veg. Spring Roll',
    description: 'Crispy fried thin pastry rolls packed with spiced noodle & vegetable stuffing',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['spring roll', 'chinese', 'snack'],
    displayOrder: 21
  },
  {
    id: 3322,
    vendorId: 32,
    categoryId: 2,
    name: 'Veg. Steamed Momos (8 Pcs)',
    description: 'Steamed dumplings packed with minced vegetables served with fiery momo chutney',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['momos', 'veg momos', 'chinese', 'bestseller'],
    displayOrder: 22
  },

  // ================= 🌯 WRAPS (Category 7) =================
  {
    id: 3323,
    vendorId: 32,
    categoryId: 7,
    name: 'Paneer Wrap',
    description: 'Tortilla wrap loaded with marinated cottage cheese, lettuce and mayo',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['wrap', 'paneer wrap'],
    displayOrder: 23
  },
  {
    id: 3324,
    vendorId: 32,
    categoryId: 7,
    name: 'Spicy Paneer Wrap',
    description: 'Fiery chili spiced paneer with crunchy greens wrapped in grilled tortilla',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['wrap', 'spicy paneer', 'bestseller'],
    displayOrder: 24
  },
  {
    id: 3325,
    vendorId: 32,
    categoryId: 7,
    name: 'Veg. Wrap',
    description: 'Fresh healthy vegetable wrap with mint spread and onions',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['wrap', 'veg wrap'],
    displayOrder: 25
  },
  {
    id: 3326,
    vendorId: 32,
    categoryId: 7,
    name: 'Chicken Wrap',
    description: 'Grilled tortilla loaded with succulent seasoned chicken pieces and garlic mayo',
    price: '110.00',
    isVeg: false,
    isAvailable: true,
    tags: ['wrap', 'chicken wrap', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 26
  },
  {
    id: 3327,
    vendorId: 32,
    categoryId: 7,
    name: 'Veg. Patty Wrap',
    description: 'Crispy veg patty crushed inside grilled wrap with cheese blend',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['wrap', 'patty wrap'],
    displayOrder: 27
  },
  {
    id: 3328,
    vendorId: 32,
    categoryId: 7,
    name: 'Egg Wrap',
    description: 'Double fluffy omelet wrapped with veggies and mustard sauce',
    price: '90.00',
    isVeg: false,
    isAvailable: true,
    tags: ['wrap', 'egg wrap', 'egg', 'eggs'],
    displayOrder: 28
  },

  // ================= 🍜 MAGGI (Category 1) =================
  {
    id: 3329,
    vendorId: 32,
    categoryId: 1,
    name: 'Veg. Maggi',
    description: 'Classic noodles tossed with tomatoes, onions and peas',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'veg maggi', 'bestseller'],
    displayOrder: 29
  },
  {
    id: 3330,
    vendorId: 32,
    categoryId: 1,
    name: 'Cheese Veg. Maggi',
    description: 'Hot vegetable Maggi topped with melted shredded mozzarella cheese',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'cheese maggi', 'bestseller'],
    displayOrder: 30
  },
  {
    id: 3331,
    vendorId: 32,
    categoryId: 1,
    name: 'Paneer Maggi',
    description: 'Noodles cooked with soft cottage cheese cubes and spices',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'paneer maggi'],
    displayOrder: 31
  },
  {
    id: 3332,
    vendorId: 32,
    categoryId: 1,
    name: 'Egg Maggi',
    description: 'Masala Maggi scrambled with fresh farm eggs',
    price: '60.00',
    isVeg: false,
    isAvailable: true,
    tags: ['maggi', 'egg maggi', 'egg', 'eggs'],
    displayOrder: 32
  },
  {
    id: 3333,
    vendorId: 32,
    categoryId: 1,
    name: 'Chicken Maggi',
    description: 'Hot noodles cooked with tender spiced shredded chicken',
    price: '100.00',
    isVeg: false,
    isAvailable: true,
    tags: ['maggi', 'chicken maggi', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 33
  },
  {
    id: 3334,
    vendorId: 32,
    categoryId: 1,
    name: 'Spicy Maggi',
    description: 'Extra fiery masala Maggi tossed with chopped green chilies and paprika',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'spicy maggi', 'under-50'],
    displayOrder: 34
  },
  {
    id: 3335,
    vendorId: 32,
    categoryId: 1,
    name: 'Plain Masala Maggi',
    description: 'Original 2-minute classic recipe masala noodles',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'plain maggi', 'under-50'],
    displayOrder: 35
  },

  // ================= 🍳 EGGS (Category 7 / 4) =================
  {
    id: 3336,
    vendorId: 32,
    categoryId: 7,
    name: 'Plain Omelette',
    description: 'Double egg fluffy classic seasoned omelet',
    price: '40.00',
    isVeg: false,
    isAvailable: true,
    tags: ['omelet', 'egg', 'eggs', 'under-50'],
    displayOrder: 36
  },
  {
    id: 3337,
    vendorId: 32,
    categoryId: 7,
    name: 'Cheese Bread Omelette',
    description: 'Toasted bread sandwiched with double egg omelet and gooey melted cheese',
    price: '80.00',
    isVeg: false,
    isAvailable: true,
    tags: ['bread omelet', 'cheese omelet', 'egg', 'eggs', 'bestseller'],
    displayOrder: 37
  },
  {
    id: 3338,
    vendorId: 32,
    categoryId: 7,
    name: 'Egg Bhurji',
    description: 'Double egg spicy Indian scramble with chopped onions and tomatoes',
    price: '40.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg bhurji', 'egg', 'eggs', 'under-50'],
    displayOrder: 38
  },
  {
    id: 3339,
    vendorId: 32,
    categoryId: 7,
    name: 'Veg. Omelette',
    description: 'Omelet loaded with finely chopped onions, capsicum, and fresh coriander',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['omelet', 'egg', 'eggs', 'under-50'],
    displayOrder: 39
  },

  // ================= 🍝 PASTA (Category 1) =================
  {
    id: 3340,
    vendorId: 32,
    categoryId: 1,
    name: 'White Sauce Pasta (Alfredo)',
    description: 'Penne pasta in silky, creamy cheesy white garlic bechamel sauce',
    price: '129.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pasta', 'white sauce', 'alfredo', 'cheese', 'bestseller'],
    displayOrder: 40
  },
  {
    id: 3341,
    vendorId: 32,
    categoryId: 1,
    name: 'Red Sauce Pasta (Arrabbiata)',
    description: 'Penne tossed in tangy Italian tomato basil sauce with oregano and olives',
    price: '129.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pasta', 'red sauce', 'arrabbiata'],
    displayOrder: 41
  },
  {
    id: 3342,
    vendorId: 32,
    categoryId: 1,
    name: 'Chicken Pasta',
    description: 'Rich pasta tossed with roasted chicken pieces, cream, and Italian seasoning',
    price: '179.00',
    isVeg: false,
    isAvailable: true,
    tags: ['pasta', 'chicken pasta', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 42
  },
  {
    id: 3343,
    vendorId: 32,
    categoryId: 1,
    name: 'Tandoori Sauce Pasta',
    description: 'Desi fusion penne tossed in smoky orange tandoori sauce with peppers',
    price: '149.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pasta', 'tandoori pasta', 'fusion'],
    displayOrder: 43
  },
  {
    id: 3344,
    vendorId: 32,
    categoryId: 1,
    name: 'Toasted Garlic Bread (Slice)',
    description: 'Crispy oven baked garlic bread brushed with herb butter',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['garlic bread', 'side', 'under-50'],
    displayOrder: 44
  },

  // ================= 🫓 KULCHA (Category 8) =================
  {
    id: 3345,
    vendorId: 32,
    categoryId: 8,
    name: 'Paneer Bhurji Kulcha',
    description: 'Soft buttered kulcha stuffed with spiced cottage cheese bhurji',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kulcha', 'paneer kulcha', 'bestseller'],
    displayOrder: 45
  },
  {
    id: 3346,
    vendorId: 32,
    categoryId: 8,
    name: 'Stuffed Paneer Kulcha',
    description: 'Golden tawa kulcha packed with seasoned crumbled paneer',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kulcha', 'stuffed kulcha'],
    displayOrder: 46
  },
  {
    id: 3347,
    vendorId: 32,
    categoryId: 8,
    name: 'Egg Kulcha',
    description: 'Buttered kulcha stuffed with savory spiced egg filling',
    price: '100.00',
    isVeg: false,
    isAvailable: true,
    tags: ['kulcha', 'egg kulcha', 'egg', 'eggs'],
    displayOrder: 47
  },

  // ================= 🥢 CHINESE (Category 2) =================
  {
    id: 3348,
    vendorId: 32,
    categoryId: 2,
    name: 'Chilli Potato',
    description: 'Crisp fried potato fingers tossed in spicy sweet chili honey glaze',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chinese', 'chilli potato', 'bestseller'],
    displayOrder: 48
  },
  {
    id: 3349,
    vendorId: 32,
    categoryId: 2,
    name: 'Chilli Garlic Noodles',
    description: 'Spicy wok-tossed noodles with burnt garlic, red chilies, and vegetables',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['noodles', 'chilli garlic', 'chinese', 'chowmein', 'bestseller'],
    displayOrder: 49
  },
  {
    id: 3350,
    vendorId: 32,
    categoryId: 2,
    name: 'Veg. Hakka Noodles',
    description: 'Classic wok-tossed noodles with cabbage, carrots, bell peppers, and soy sauce',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['noodles', 'hakka noodles', 'chinese', 'chowmein'],
    displayOrder: 50
  },
  {
    id: 3351,
    vendorId: 32,
    categoryId: 2,
    name: 'Chilli Paneer',
    description: 'Crisp cottage cheese cubes tossed with capsicum, onion and Indo-Chinese sauces (Half: ₹120 / Full: ₹240)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilli paneer', 'chinese', 'paneer', 'bestseller'],
    displayOrder: 51
  },
  {
    id: 3352,
    vendorId: 32,
    categoryId: 2,
    name: 'Veg. Manchurian',
    description: 'Deep fried veggie balls tossed in thick dark savory Chinese gravy',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['manchurian', 'chinese'],
    displayOrder: 52
  },

  // ================= 🍚 RICE & BIRYANI (Category 4) =================
  {
    id: 3353,
    vendorId: 32,
    categoryId: 4,
    name: 'Egg Fried Rice',
    description: 'Fragrant basmati rice tossed with scrambled egg and spring onions',
    price: '100.00',
    isVeg: false,
    isAvailable: true,
    tags: ['fried rice', 'egg fried rice', 'egg', 'eggs'],
    displayOrder: 53
  },
  {
    id: 3354,
    vendorId: 32,
    categoryId: 4,
    name: 'Veg. Fried Rice',
    description: 'Wok tossed basmati rice with finely chopped carrots, beans and peppers',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fried rice', 'veg fried rice'],
    displayOrder: 54
  },
  {
    id: 3355,
    vendorId: 32,
    categoryId: 4,
    name: 'Chicken Fried Rice',
    description: 'Wok-tossed rice with tender chicken bits and dark soy sauce',
    price: '160.00',
    isVeg: false,
    isAvailable: true,
    tags: ['fried rice', 'chicken fried rice', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 55
  },
  {
    id: 3356,
    vendorId: 32,
    categoryId: 4,
    name: 'Veg. Biryani',
    description: 'Spiced aromatic dum rice layered with seasonal vegetables and herbs',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['biryani', 'veg biryani'],
    displayOrder: 56
  },
  {
    id: 3357,
    vendorId: 32,
    categoryId: 4,
    name: 'Egg Biryani',
    description: 'Flavorful dum biryani rice served with spiced hard-boiled eggs',
    price: '140.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'egg biryani', 'egg', 'eggs'],
    displayOrder: 57
  },
  {
    id: 3358,
    vendorId: 32,
    categoryId: 4,
    name: 'Chicken Biryani',
    description: 'Rich spiced chicken dum biryani with saffron scented basmati',
    price: '160.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'chicken biryani', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 58
  },

  // ================= 🧋 BEVERAGES & COOLERS (Category 3) =================
  {
    id: 3359,
    vendorId: 32,
    categoryId: 3,
    name: 'Masala Soda (Sweet/Salty)',
    description: 'Fizzy digestive lemon soda flavored with black salt and cumin',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soda', 'masala soda', 'beverage', 'under-50'],
    displayOrder: 59
  },
  {
    id: 3360,
    vendorId: 32,
    categoryId: 3,
    name: 'Mint Mojito',
    description: 'Crisp refreshing soda muddled with fresh mint sprigs and lime',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mojito', 'mint mojito', 'mocktail', 'bestseller'],
    displayOrder: 60
  },
  {
    id: 3361,
    vendorId: 32,
    categoryId: 3,
    name: 'Classic Mojito',
    description: 'Chilled lime and soda cooler with sugar syrup and mint',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mojito', 'mocktail'],
    displayOrder: 61
  },
  {
    id: 3362,
    vendorId: 32,
    categoryId: 3,
    name: 'Strawberry Mojito',
    description: 'Sweet pink strawberry flavored sparkling mint cooler',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mojito', 'strawberry', 'mocktail'],
    displayOrder: 62
  },
  {
    id: 3363,
    vendorId: 32,
    categoryId: 3,
    name: 'Blue Curacao Cooler',
    description: 'Vibrant tropical citrus blue lagoon iced mocktail',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mocktail', 'blue curacao', 'cooler', 'bestseller'],
    displayOrder: 63
  },
  {
    id: 3364,
    vendorId: 32,
    categoryId: 3,
    name: 'Mango Mojito',
    description: 'Sweet mango fruit pulp shaken with fizzy soda and mint',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mojito', 'mango', 'mocktail'],
    displayOrder: 64
  },
  {
    id: 3365,
    vendorId: 32,
    categoryId: 3,
    name: 'Fruit Beer (Non-Alcoholic)',
    description: 'Malty, fizzy non-alcoholic fruit beer refresher',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fruit beer', 'beverage', 'under-50'],
    displayOrder: 65
  },
  {
    id: 3366,
    vendorId: 32,
    categoryId: 3,
    name: 'Ginger Beer (Non-Alcoholic)',
    description: 'Zingy ginger spiced fizzy sparkling drink',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['ginger beer', 'beverage', 'under-50'],
    displayOrder: 66
  },
  {
    id: 3367,
    vendorId: 32,
    categoryId: 3,
    name: 'Lemon Iced Tea',
    description: 'Chilled freshly brewed black tea with lemon and crushed ice',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['iced tea', 'beverage', 'under-50'],
    displayOrder: 67
  },
  {
    id: 3368,
    vendorId: 32,
    categoryId: 3,
    name: 'Masala Lassi',
    description: 'Cool savory spiced churning curd lassi with jeera and mint',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lassi', 'masala lassi', 'desi', 'under-50'],
    displayOrder: 68
  },
  {
    id: 3369,
    vendorId: 32,
    categoryId: 3,
    name: 'Mango Lassi',
    description: 'Thick creamy Punjabi sweet lassi blended with Alphonso mango',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lassi', 'mango lassi', 'bestseller'],
    displayOrder: 69
  },

  // ================= 🫓 PARATHAS (Category 8) =================
  {
    id: 3370,
    vendorId: 32,
    categoryId: 8,
    name: 'Aloo Pyaz Paratha',
    description: 'Crispy tawa paratha stuffed with seasoned potato and onion mix',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'aloo pyaz', 'under-50', 'bestseller'],
    displayOrder: 70
  },
  {
    id: 3371,
    vendorId: 32,
    categoryId: 8,
    name: 'Aloo Paratha',
    description: 'Golden whole wheat paratha packed with spicy potato filling',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'aloo paratha', 'under-50'],
    displayOrder: 71
  },
  {
    id: 3372,
    vendorId: 32,
    categoryId: 8,
    name: 'Pyaz Paratha',
    description: 'Crispy paratha filled with spiced crunchy diced onions',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'pyaz paratha', 'under-50'],
    displayOrder: 72
  },
  {
    id: 3373,
    vendorId: 32,
    categoryId: 8,
    name: 'Gobhi Paratha',
    description: 'Spiced grated cauliflower stuffed hot tawa paratha',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'gobhi paratha', 'under-50'],
    displayOrder: 73
  },
  {
    id: 3374,
    vendorId: 32,
    categoryId: 8,
    name: 'Paneer Pyaz Paratha',
    description: 'Rich paratha stuffed with crumbled cottage cheese and onions',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'paneer paratha', 'under-50', 'bestseller'],
    displayOrder: 74
  },
  {
    id: 3375,
    vendorId: 32,
    categoryId: 8,
    name: 'Plain Paratha',
    description: 'Crispy layered tawa paratha brushed with fresh butter',
    price: '25.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'plain paratha', 'under-50'],
    displayOrder: 75
  },
  {
    id: 3376,
    vendorId: 32,
    categoryId: 8,
    name: 'Mix Veg Paratha',
    description: 'Stuffed paratha with paneer, potatoes, onions, and cauliflower',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'mix paratha', 'under-50'],
    displayOrder: 76
  },
  {
    id: 3377,
    vendorId: 32,
    categoryId: 8,
    name: 'Chicken Paratha',
    description: 'Stuffed tawa paratha packed with savory minced chicken filling',
    price: '90.00',
    isVeg: false,
    isAvailable: true,
    tags: ['paratha', 'chicken paratha', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 77
  },

  // ================= 🍨 SHAKES & COLD COFFEE (Category 3) =================
  {
    id: 3378,
    vendorId: 32,
    categoryId: 3,
    name: 'Chocolate Shake',
    description: 'Rich blended chocolate milk shake with chocolate syrup',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'chocolate shake', 'dessert'],
    displayOrder: 78
  },
  {
    id: 3379,
    vendorId: 32,
    categoryId: 3,
    name: 'Vanilla Shake',
    description: 'Creamy smooth vanilla ice cream thick shake',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'vanilla shake'],
    displayOrder: 79
  },
  {
    id: 3380,
    vendorId: 32,
    categoryId: 3,
    name: 'Strawberry Shake',
    description: 'Chilled creamy milk shake infused with sweet strawberries',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'strawberry shake'],
    displayOrder: 80
  },
  {
    id: 3381,
    vendorId: 32,
    categoryId: 3,
    name: 'Butterscotch Shake',
    description: 'Sweet butterscotch shake with crunchy butter praline bits',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'butterscotch'],
    displayOrder: 81
  },
  {
    id: 3382,
    vendorId: 32,
    categoryId: 3,
    name: 'Kitkat Shake',
    description: 'Thick chocolate shake blended with crunchy KitKat bars',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'kitkat shake', 'bestseller'],
    displayOrder: 82
  },
  {
    id: 3383,
    vendorId: 32,
    categoryId: 3,
    name: 'Oreo Shake',
    description: 'Cookies and cream shake blended with rich Oreo biscuits',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'oreo shake', 'bestseller'],
    displayOrder: 83
  },
  {
    id: 3384,
    vendorId: 32,
    categoryId: 3,
    name: 'Cold Coffee',
    description: 'Chilled thick frothy blended coffee with chocolate drizzle',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['coffee', 'cold coffee', 'bestseller'],
    displayOrder: 84
  },
  {
    id: 3385,
    vendorId: 32,
    categoryId: 3,
    name: 'Caramelized Cold Coffee',
    description: 'Cold coffee enriched with gooey buttery caramel sauce',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['coffee', 'caramel coffee', 'bestseller'],
    displayOrder: 85
  },
  {
    id: 3386,
    vendorId: 32,
    categoryId: 3,
    name: 'Banana Shake',
    description: 'Healthy energy-packed ripe banana blended milk shake',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'banana shake', 'healthy', 'under-50'],
    displayOrder: 86
  },
  {
    id: 3387,
    vendorId: 32,
    categoryId: 3,
    name: 'Papaya Shake',
    description: 'Fresh nutritious blended papaya fruit shake',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'papaya shake', 'healthy', 'under-50'],
    displayOrder: 87
  },
  {
    id: 3388,
    vendorId: 32,
    categoryId: 3,
    name: 'Mango Shake',
    description: 'Thick sweet mango shake made with real mango pulp',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'mango shake', 'bestseller'],
    displayOrder: 88
  },

  // ================= ☕ HOT BEVERAGES (Category 3) =================
  {
    id: 3389,
    vendorId: 32,
    categoryId: 3,
    name: 'Kadak Chai (Tea)',
    description: 'Hot brewed milk tea with ginger and aromatic cardamom',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tea', 'chai', 'hot beverage', 'under-50'],
    displayOrder: 89
  },
  {
    id: 3390,
    vendorId: 32,
    categoryId: 3,
    name: 'Hot Coffee',
    description: 'Steaming frothy aromatic espresso milk coffee',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['coffee', 'hot coffee', 'under-50'],
    displayOrder: 90
  },
  {
    id: 3391,
    vendorId: 32,
    categoryId: 3,
    name: 'Hot Caramel Coffee',
    description: 'Warm frothy coffee flavored with rich sweet caramel',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['coffee', 'hot caramel', 'under-50'],
    displayOrder: 91
  },
  {
    id: 3392,
    vendorId: 32,
    categoryId: 3,
    name: 'Hot Chocolate',
    description: 'Warm thick melted chocolate milk topped with cocoa powder',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['hot chocolate', 'chocolate', 'under-50', 'bestseller'],
    displayOrder: 92
  },

  // ================= 🥘 PANEER KA KAMAL (Category 4 - North Indian) =================
  {
    id: 3393,
    vendorId: 32,
    categoryId: 4,
    name: 'Kadhai Paneer',
    description: 'Fresh cottage cheese cooked with bell peppers, onion cubes and kadhai gravy (Half: ₹130 / Full: ₹260)',
    price: '130.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'kadhai paneer', 'curry', 'bestseller'],
    displayOrder: 93
  },
  {
    id: 3394,
    vendorId: 32,
    categoryId: 4,
    name: 'Shahi Paneer',
    description: 'Soft paneer in rich mild sweet cashew nut gravy (Half: ₹120 / Full: ₹240)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'shahi paneer', 'curry'],
    displayOrder: 94
  },
  {
    id: 3395,
    vendorId: 32,
    categoryId: 4,
    name: 'Paneer Butter Masala',
    description: 'Tender cottage cheese cooked in creamy tomato butter makhani gravy (Half: ₹120 / Full: ₹240)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer butter masala', 'curry', 'bestseller'],
    displayOrder: 95
  },
  {
    id: 3396,
    vendorId: 32,
    categoryId: 4,
    name: 'Paneer Bhurji',
    description: 'Spiced scrambled cottage cheese with tomatoes, onions and green chillies',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer bhurji', 'curry'],
    displayOrder: 96
  },
  {
    id: 3397,
    vendorId: 32,
    categoryId: 4,
    name: 'Paneer Do Pyaza',
    description: 'Succulent paneer cubes simmered in aromatic double onion gravy',
    price: '240.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer do pyaza', 'curry'],
    displayOrder: 97
  },

  // ================= 🍗 CHICKEN CORNER (Category 4) =================
  {
    id: 3398,
    vendorId: 32,
    categoryId: 4,
    name: 'Chicken Home Style',
    description: 'Homestyle light desi chicken curry just like homemade (Half: ₹300 / Full: ₹500)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'home style chicken', 'curry', 'nonveg', 'bestseller'],
    displayOrder: 98
  },
  {
    id: 3399,
    vendorId: 32,
    categoryId: 4,
    name: 'Kadhai Chicken',
    description: 'Tender chicken tossed with crunchy bell peppers and aromatic spices (Half: ₹300 / Full: ₹550)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'kadhai chicken', 'nonveg'],
    displayOrder: 99
  },
  {
    id: 3400,
    vendorId: 32,
    categoryId: 4,
    name: 'Butter Chicken',
    description: 'Clay roasted chicken cooked in luscious butter tomato cream gravy (Half: ₹300 / Full: ₹550)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'butter chicken', 'makhani', 'nonveg', 'bestseller'],
    displayOrder: 100
  },
  {
    id: 3401,
    vendorId: 32,
    categoryId: 4,
    name: 'Chilli Chicken',
    description: 'Crispy fried chicken chunks tossed in spicy soy-chili sauce (Half: ₹300 / Full: ₹500)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chilli chicken', 'chinese', 'nonveg'],
    displayOrder: 101
  },
  {
    id: 3402,
    vendorId: 32,
    categoryId: 4,
    name: 'Chicken Pakora',
    description: 'Crispy golden fried marinated chicken pakoras served with mint dip (Half: ₹250 / Full: ₹450)',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken pakora', 'starter', 'nonveg', 'bestseller'],
    displayOrder: 102
  },

  // ================= 🍱 GHAR JAISA KHANA & POHA =================
  {
    id: 3403,
    vendorId: 32,
    categoryId: 4,
    name: 'Veg. Thali',
    description: 'Homestyle comforting meal with Dal, Chawal, Subji, 4 Butter Roti, Salad and Pickle',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['thali', 'veg thali', 'ghar jaisa', 'healthy', 'bestseller'],
    displayOrder: 103
  },
  {
    id: 3404,
    vendorId: 32,
    categoryId: 4,
    name: 'Shahi Thali (Special)',
    description: 'Deluxe royal thali with Dal Makhani, Shahi Paneer, 4 Butter Roti, Chawal, Raita, Salad and Sweet dessert',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['thali', 'shahi thali', 'deluxe', 'bestseller'],
    displayOrder: 104
  },
  {
    id: 3405,
    vendorId: 32,
    categoryId: 4,
    name: 'Plain Roti',
    description: 'Fresh hot whole wheat tawa roti',
    price: '10.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'phulka', 'under-50'],
    displayOrder: 105
  },
  {
    id: 3406,
    vendorId: 32,
    categoryId: 4,
    name: 'Butter Roti',
    description: 'Hot tawa roti brushed with fresh butter',
    price: '12.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'butter roti', 'under-50'],
    displayOrder: 106
  },
  {
    id: 3407,
    vendorId: 32,
    categoryId: 8,
    name: 'Poha',
    description: 'Light flattened rice tempered with peanuts, mustard seeds, onions and sev',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['poha', 'breakfast', 'under-50'],
    displayOrder: 107
  },
  {
    id: 3408,
    vendorId: 32,
    categoryId: 8,
    name: 'Special Poha',
    description: 'Loaded poha topped with extra fried peanuts, roasted sev, coriander and pomegranate',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['poha', 'special poha', 'breakfast', 'bestseller'],
    displayOrder: 108
  },
  {
    id: 3409,
    vendorId: 32,
    categoryId: 4,
    name: 'Litti Chokha (Special Order)',
    description: 'Traditional wood-roasted sattu litti served with spicy smoked brinjal-tomato chokha and desi ghee',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['litti chokha', 'desi', 'bihari', 'bestseller'],
    displayOrder: 109
  }
];
