export const CHEF_ON_FOOD_JUNCTION_VENDOR = {
  id: 28,
  name: 'Chef On Food Junction',
  slug: 'chef-on-food-junction',
  phone: '9911331439',
  whatsapp: '9911331439',
  address: 'Opposite NIT Main Gate, Kurukshetra',
  latitude: '29.9675',
  longitude: '76.8818',
  opensAt: '10:30',
  closesAt: '22:00',
  deliversTo: ['NIT Main Gate', 'NIT Back Gate', 'Girls Hostel', 'Boys Hostel'],
  image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
  isActive: true,
  isFeatured: true,
  displayOrder: 8,
  createdAt: new Date()
};

export const CHEF_ON_FOOD_JUNCTION_MENU_ITEMS = [
  // ================= 🧀 TANDOOR SE (VEG) (Category 4) =================
  {
    id: 2801,
    vendorId: 28,
    categoryId: 4,
    name: 'Paneer Tikka',
    description: 'Cubes of cottage cheese marinated in spiced yogurt and grilled in tandoor (Full: ₹170 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'tandoor', 'tikka', 'starter', 'protein', 'bestseller'],
    displayOrder: 1
  },
  {
    id: 2802,
    vendorId: 28,
    categoryId: 4,
    name: 'Paneer Malai Tikka',
    description: 'Tender paneer cubes marinated in cream, cashew paste, and mild spices (Full: ₹190 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'malai tikka', 'creamy', 'tandoor'],
    displayOrder: 2
  },
  {
    id: 2803,
    vendorId: 28,
    categoryId: 4,
    name: 'Paneer Haryali Tikka',
    description: 'Cottage cheese coated in fresh mint, coriander, and green chili paste (Full: ₹180 / Half: ₹110)',
    price: '110.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'haryali', 'mint', 'tandoor'],
    displayOrder: 3
  },

  // ================= 🍲 MAIN COURSE (VEG) (Category 4) =================
  {
    id: 2804,
    vendorId: 28,
    categoryId: 4,
    name: 'Dal Makhani',
    description: 'Slow-cooked black lentils simmered with butter and cream (Full: ₹150 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal', 'dal makhani', 'north indian', 'bestseller'],
    displayOrder: 4
  },
  {
    id: 2805,
    vendorId: 28,
    categoryId: 4,
    name: 'Dal Tadka',
    description: 'Yellow arhar dal tempered with cumin, garlic, and red chilies (Full: ₹130 / Half: ₹90)',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal', 'dal tadka', 'yellow dal'],
    displayOrder: 5
  },
  {
    id: 2806,
    vendorId: 28,
    categoryId: 4,
    name: 'Dal Fry',
    description: 'Homestyle fried yellow lentils cooked with onions and tomatoes (Full: ₹130 / Half: ₹90)',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal', 'dal fry'],
    displayOrder: 6
  },
  {
    id: 2807,
    vendorId: 28,
    categoryId: 4,
    name: 'Matar Mushroom',
    description: 'Fresh button mushrooms and green peas in spiced onion-tomato gravy (Full: ₹170 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom', 'matar mushroom', 'curry'],
    displayOrder: 7
  },
  {
    id: 2808,
    vendorId: 28,
    categoryId: 4,
    name: 'Mushroom Do Pyaja',
    description: 'Tender mushrooms tossed with caramelized onions and whole spices (Full: ₹160 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom', 'do pyaza'],
    displayOrder: 8
  },
  {
    id: 2809,
    vendorId: 28,
    categoryId: 4,
    name: 'Mix Vegetable',
    description: 'Seasonal assorted garden vegetables cooked in semi-dry aromatic masala (Full: ₹140 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix veg', 'vegetable'],
    displayOrder: 9
  },
  {
    id: 2810,
    vendorId: 28,
    categoryId: 4,
    name: 'Jeera Aloo',
    description: 'Crispy potato cubes tempered with roasted cumin seeds and turmeric (Full: ₹90 / Half: ₹70)',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['jeera aloo', 'aloo', 'under-50'],
    displayOrder: 10
  },
  {
    id: 2811,
    vendorId: 28,
    categoryId: 4,
    name: 'Aloo Gobhi',
    description: 'Classic cauliflower and potato curry sauteed with ginger and spices (Full: ₹110 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo gobhi', 'gobhi'],
    displayOrder: 11
  },
  {
    id: 2812,
    vendorId: 28,
    categoryId: 4,
    name: 'Palak Mushroom',
    description: 'Sliced button mushrooms simmered in fresh pureed spinach gravy (Full: ₹120 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['palak', 'mushroom', 'healthy'],
    displayOrder: 12
  },
  {
    id: 2813,
    vendorId: 28,
    categoryId: 4,
    name: 'Dum Aloo',
    description: 'Crispy fried baby potatoes cooked in rich spiced Kashmiri gravy (Full: ₹130 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dum aloo', 'aloo'],
    displayOrder: 13
  },
  {
    id: 2814,
    vendorId: 28,
    categoryId: 4,
    name: 'Baingan Bharta',
    description: 'Smoky fire-roasted eggplant mashed and cooked with garlic and tomatoes (Full: ₹130 / Half: ₹90)',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['baingan', 'bharta'],
    displayOrder: 14
  },

  // ================= 🧀 PANEER SPECIAL (Category 4) =================
  {
    id: 2815,
    vendorId: 28,
    categoryId: 4,
    name: 'Kadai Paneer',
    description: 'Paneer cubes cooked with bell peppers, onions, and freshly ground kadhai masala (Full: ₹200 / Half: ₹150)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'kadai paneer', 'bestseller'],
    displayOrder: 15
  },
  {
    id: 2816,
    vendorId: 28,
    categoryId: 4,
    name: 'Shahi Paneer',
    description: 'Paneer in rich, mildly sweet cashew nut and tomato cream gravy (Full: ₹190 / Half: ₹150)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shahi paneer', 'paneer'],
    displayOrder: 16
  },
  {
    id: 2817,
    vendorId: 28,
    categoryId: 4,
    name: 'Punjabi Paneer',
    description: 'Dhaba-style spicy paneer curry cooked with whole spices (Full: ₹200 / Half: ₹150)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['punjabi paneer', 'spicy'],
    displayOrder: 17
  },
  {
    id: 2818,
    vendorId: 28,
    categoryId: 4,
    name: 'Paneer Lababdar',
    description: 'Soft cottage cheese simmered in velvety tomato onion gravy with grated paneer (Full: ₹200 / Half: ₹150)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer lababdar', 'paneer'],
    displayOrder: 18
  },
  {
    id: 2819,
    vendorId: 28,
    categoryId: 4,
    name: 'Paneer Butter Masala',
    description: 'Rich buttery tomato gravy loaded with soft paneer cubes (Full: ₹200 / Half: ₹150)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer butter masala', 'bestseller'],
    displayOrder: 19
  },
  {
    id: 2820,
    vendorId: 28,
    categoryId: 4,
    name: 'Tawa Paneer',
    description: 'Dry-spiced tawa roasted paneer tossed with crunchy onions and capsicum (Full: ₹200 / Half: ₹150)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tawa paneer', 'paneer'],
    displayOrder: 20
  },
  {
    id: 2821,
    vendorId: 28,
    categoryId: 4,
    name: 'Paneer Bhurji',
    description: 'Freshly scrambled paneer cooked with chopped onions, green chilies and spices (Full: ₹210 / Half: ₹160)',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer bhurji', 'protein'],
    displayOrder: 21
  },
  {
    id: 2822,
    vendorId: 28,
    categoryId: 4,
    name: 'Chilli Paneer (Gravy / Dry)',
    description: 'Indo-Chinese wok-tossed cottage cheese with soy, garlic and peppers (Full: ₹220 / Half: ₹150)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilli paneer', 'chinese'],
    displayOrder: 22
  },
  {
    id: 2823,
    vendorId: 28,
    categoryId: 4,
    name: 'Paneer Tomato',
    description: 'Paneer simmered in tangy spiced tomato-based North Indian curry (Full: ₹220 / Half: ₹150)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer tomato', 'curry'],
    displayOrder: 23
  },
  {
    id: 2824,
    vendorId: 28,
    categoryId: 4,
    name: 'Paneer Tikka Butter Masala',
    description: 'Chargrilled paneer tikka finished in rich makhani butter gravy (Full: ₹200 / Half: ₹150)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer tikka butter masala', 'paneer'],
    displayOrder: 24
  },
  {
    id: 2825,
    vendorId: 28,
    categoryId: 4,
    name: 'Paneer Do Pyaza',
    description: 'Cottage cheese cooked with double the onions in rich aromatic masala (Full: ₹200 / Half: ₹150)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer do pyaza', 'paneer'],
    displayOrder: 25
  },
  {
    id: 2826,
    vendorId: 28,
    categoryId: 4,
    name: 'Paneer Malai Methi',
    description: 'Smooth creamy paneer flavored with fragrant fenugreek leaves (Full: ₹210 / Half: ₹150)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['methi malai', 'paneer'],
    displayOrder: 26
  },
  {
    id: 2827,
    vendorId: 28,
    categoryId: 4,
    name: 'Makhani Paneer',
    description: 'Silky smooth butter-tomato paneer curry prepared with 5-star hotel recipe (Full: ₹200 / Half: ₹150)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['makhani paneer', 'paneer'],
    displayOrder: 27
  },

  // ================= 🍗 MAIN COURSE (NON VEG) (Category 4) =================
  {
    id: 2828,
    vendorId: 28,
    categoryId: 4,
    name: 'Butter Chicken',
    description: 'Tender chicken cooked in rich velvety tomato-cream gravy with pure butter (Full: ₹550 / Half: ₹300)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'butter chicken', 'nonveg', 'bestseller'],
    displayOrder: 28
  },
  {
    id: 2829,
    vendorId: 28,
    categoryId: 4,
    name: 'Chicken Masala',
    description: 'Classic spiced dhaba chicken curry with thick caramelized onion-tomato masala (Full: ₹550 / Half: ₹280)',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken masala', 'nonveg'],
    displayOrder: 29
  },
  {
    id: 2830,
    vendorId: 28,
    categoryId: 4,
    name: 'Punjabi Butter Chicken',
    description: 'Rich Punjabi-style spiced butter chicken with authentic desi spices (Full: ₹550 / Half: ₹280)',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'punjabi chicken', 'nonveg'],
    displayOrder: 30
  },
  {
    id: 2831,
    vendorId: 28,
    categoryId: 4,
    name: 'Tawa Chicken',
    description: 'Juicy chicken pieces roasted on heavy iron griddle with roasted ground spices (Full: ₹550 / Half: ₹280)',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['tawa chicken', 'chicken', 'nonveg'],
    displayOrder: 31
  },
  {
    id: 2832,
    vendorId: 28,
    categoryId: 4,
    name: 'Kadai Chicken',
    description: 'Wok-tossed chicken cooked with crushed coriander seeds and bell peppers (Full: ₹550 / Half: ₹280)',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['kadai chicken', 'chicken', 'nonveg'],
    displayOrder: 32
  },
  {
    id: 2833,
    vendorId: 28,
    categoryId: 4,
    name: 'Chicken Tikka Masala',
    description: 'Roasted boneless chicken tikka simmered in spiced onion-tomato gravy (Full: ₹580 / Half: ₹300)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken tikka masala', 'chicken', 'nonveg'],
    displayOrder: 33
  },
  {
    id: 2834,
    vendorId: 28,
    categoryId: 4,
    name: 'Chicken Tikka Lababdar',
    description: 'Tandoori chicken tikka cooked in rich makhani and cashew sauce (Full: ₹580 / Half: ₹300)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken lababdar', 'chicken', 'nonveg'],
    displayOrder: 34
  },
  {
    id: 2835,
    vendorId: 28,
    categoryId: 4,
    name: 'Chicken Curry',
    description: 'Homestyle light and flavorful chicken curry (Full: ₹550 / Half: ₹280)',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken curry', 'chicken', 'nonveg'],
    displayOrder: 35
  },
  {
    id: 2836,
    vendorId: 28,
    categoryId: 4,
    name: 'Chicken Masala Dry',
    description: 'Semi-dry spicy roasted chicken coated in thick caramelized masala (Full: ₹550 / Half: ₹280)',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken dry', 'chicken', 'nonveg'],
    displayOrder: 36
  },
  {
    id: 2837,
    vendorId: 28,
    categoryId: 4,
    name: 'Home Made Chicken',
    description: 'Light, fragrant rustic homestyle chicken curry (Full: ₹550 / Half: ₹280)',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['home chicken', 'chicken', 'nonveg'],
    displayOrder: 37
  },
  {
    id: 2838,
    vendorId: 28,
    categoryId: 4,
    name: 'Chicken Pakoda',
    description: 'Crispy gram-flour battered chicken fritters tossed with chaat masala (Full: ₹550 / Half: ₹280)',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken pakoda', 'snack', 'chicken', 'nonveg'],
    displayOrder: 38
  },
  {
    id: 2839,
    vendorId: 28,
    categoryId: 4,
    name: 'Chicken Rogan Josh',
    description: 'Aromatic Kashmiri-style chicken stew flavored with cloves and cardamom (Full: ₹550 / Half: ₹280)',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken rogan', 'chicken', 'nonveg'],
    displayOrder: 39
  },
  {
    id: 2840,
    vendorId: 28,
    categoryId: 4,
    name: 'Tandoori Lemon Chicken',
    description: 'Tangy tandoor-roasted chicken with fresh lemon, garlic and cracked pepper (Full: ₹550 / Half: ₹280)',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['lemon chicken', 'tandoori', 'chicken', 'nonveg'],
    displayOrder: 40
  },
  {
    id: 2841,
    vendorId: 28,
    categoryId: 4,
    name: 'Pepper Chicken',
    description: 'Spicy black pepper tossed chicken preparation (Full: ₹580 / Half: ₹300)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['pepper chicken', 'spicy', 'chicken', 'nonveg'],
    displayOrder: 41
  },
  {
    id: 2842,
    vendorId: 28,
    categoryId: 4,
    name: 'Fried Chicken',
    description: 'Golden deep-fried crunchy chicken pieces (Full: ₹350 / Half: ₹280)',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['fried chicken', 'crispy', 'chicken', 'nonveg'],
    displayOrder: 42
  },
  {
    id: 2843,
    vendorId: 28,
    categoryId: 4,
    name: 'Egg Curry',
    description: 'Boiled eggs simmered in spiced onion-tomato curry (4 Eggs Full: ₹160 / 2 Eggs Half: ₹110)',
    price: '110.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg curry', 'egg', 'eggs', 'protein'],
    displayOrder: 43
  },
  {
    id: 2844,
    vendorId: 28,
    categoryId: 4,
    name: 'Chicken Making Charges',
    description: 'Bring your own chicken and our 5-star hotel experienced chef will cook it fresh (1kg: ₹350 / 500g: ₹150)',
    price: '150.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken cooking', 'custom', 'nonveg'],
    displayOrder: 44
  },

  // ================= 🥢 SOYA CHAAP (Category 4) =================
  {
    id: 2845,
    vendorId: 28,
    categoryId: 4,
    name: 'Soya Chap Tandoori',
    description: 'Chargrilled soya chaap marinated in yogurt and tandoori spices (Full: ₹220 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chaap', 'soya chaap', 'tandoori', 'protein'],
    displayOrder: 45
  },
  {
    id: 2846,
    vendorId: 28,
    categoryId: 4,
    name: 'Soya Chap Achari',
    description: 'Tangy pickled spice marinated soya chaap grilled to perfection (Full: ₹220 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['achari chaap', 'soya chaap'],
    displayOrder: 46
  },
  {
    id: 2847,
    vendorId: 28,
    categoryId: 4,
    name: 'Malai Chap',
    description: 'Creamy, rich cashew and cream marinated tender soya chaap (Full: ₹220 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['malai chaap', 'soya chaap', 'bestseller'],
    displayOrder: 47
  },
  {
    id: 2848,
    vendorId: 28,
    categoryId: 4,
    name: 'Soya Chap Tikka',
    description: 'Spiced grilled soya chaap skewers with onion and capsicum (Full: ₹220 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soya tikka', 'chaap'],
    displayOrder: 48
  },
  {
    id: 2849,
    vendorId: 28,
    categoryId: 4,
    name: 'Masala Chap Gravy',
    description: 'Soya chaap cooked in rich spicy North Indian gravy (Full: ₹220 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['masala chaap', 'chaap gravy'],
    displayOrder: 49
  },

  // ================= 🍚 RICE & BIRYANI KHAZANA (Category 4) =================
  {
    id: 2850,
    vendorId: 28,
    categoryId: 4,
    name: 'Steam Plain Rice',
    description: 'Fluffy steamed long-grain basmati rice (Full: ₹90 / Half: ₹60)',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'steamed rice', 'plain rice'],
    displayOrder: 50
  },
  {
    id: 2851,
    vendorId: 28,
    categoryId: 4,
    name: 'Jeera Rice',
    description: 'Basmati rice tempered with aromatic roasted cumin and desi ghee (Full: ₹90 / Half: ₹60)',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['jeera rice', 'rice'],
    displayOrder: 51
  },
  {
    id: 2852,
    vendorId: 28,
    categoryId: 4,
    name: 'Vegetable Pulao',
    description: 'Fragrant basmati rice tossed with garden veggies and mild whole spices (Full: ₹120 / Half: ₹70)',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg pulao', 'pulao'],
    displayOrder: 52
  },
  {
    id: 2853,
    vendorId: 28,
    categoryId: 4,
    name: 'Peas Pulao (Matar Pulao)',
    description: 'Long-grain rice tossed with sweet green peas and cumin (Full: ₹120 / Half: ₹70)',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['peas pulao', 'matar pulao'],
    displayOrder: 53
  },
  {
    id: 2854,
    vendorId: 28,
    categoryId: 4,
    name: 'Veg Biryani',
    description: 'Layered dum biryani with seasoned vegetables and saffron rice (Full: ₹140 / Half: ₹90)',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg biryani', 'biryani'],
    displayOrder: 54
  },
  {
    id: 2855,
    vendorId: 28,
    categoryId: 4,
    name: 'Chicken Biryani',
    description: 'Aromatic dum biryani with juicy spiced chicken and boiled egg (Full: ₹250 / Half: ₹150)',
    price: '150.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken biryani', 'biryani', 'nonveg', 'bestseller'],
    displayOrder: 55
  },
  {
    id: 2856,
    vendorId: 28,
    categoryId: 4,
    name: 'Hyderabadi Chicken Biryani',
    description: 'Authentic spicy Hyderabadi-style layered chicken dum biryani (Full: ₹250 / Half: ₹150)',
    price: '150.00',
    isVeg: false,
    isAvailable: true,
    tags: ['hyderabadi biryani', 'biryani', 'nonveg'],
    displayOrder: 56
  },
  {
    id: 2857,
    vendorId: 28,
    categoryId: 4,
    name: 'Chicken Fry Piece Biryani',
    description: 'Fragrant biryani rice served with crispy spiced fried chicken pieces (Full: ₹250 / Half: ₹150)',
    price: '150.00',
    isVeg: false,
    isAvailable: true,
    tags: ['fry piece biryani', 'chicken biryani', 'nonveg'],
    displayOrder: 57
  },
  {
    id: 2858,
    vendorId: 28,
    categoryId: 4,
    name: 'Paneer Fry Rice',
    description: 'Wok-tossed rice with pan-fried cottage cheese cubes and veggies (Full: ₹150 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer rice', 'fried rice'],
    displayOrder: 58
  },
  {
    id: 2859,
    vendorId: 28,
    categoryId: 4,
    name: 'Egg Biryani',
    description: 'Fragrant basmati biryani layered with golden spiced boiled eggs (Full: ₹170 / Half: ₹120)',
    price: '120.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg biryani', 'biryani', 'egg', 'eggs'],
    displayOrder: 59
  },
  {
    id: 2860,
    vendorId: 28,
    categoryId: 4,
    name: 'Lemon Rice',
    description: 'South-style tangy rice tempered with mustard, curry leaves, and lemon (Full: ₹150 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lemon rice', 'rice'],
    displayOrder: 60
  },
  {
    id: 2861,
    vendorId: 28,
    categoryId: 4,
    name: 'Paneer Biryani',
    description: 'Fragrant spiced dum biryani layered with marinated paneer cubes (Full: ₹150 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer biryani', 'biryani'],
    displayOrder: 61
  },

  // ================= 🥢 NOODLES & CHINESE STARTERS (Category 2) =================
  {
    id: 2862,
    vendorId: 28,
    categoryId: 2,
    name: 'Veg Noodle',
    description: 'Classic stir-fried noodles with crunchy cabbage, carrots and capsicum (Full: ₹100 / Half: ₹70)',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['noodles', 'chowmein', 'chinese'],
    displayOrder: 62
  },
  {
    id: 2863,
    vendorId: 28,
    categoryId: 2,
    name: 'Veg Hakka Noodle',
    description: 'Authentic wok-tossed thin noodles with ginger, garlic and soy (Full: ₹100 / Half: ₹70)',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['hakka noodle', 'noodles'],
    displayOrder: 63
  },
  {
    id: 2864,
    vendorId: 28,
    categoryId: 2,
    name: 'Egg Noodle',
    description: 'Stir-fried noodles scrambled with farm fresh eggs and veggies (Full: ₹130 / Half: ₹90)',
    price: '90.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg noodles', 'noodles', 'egg', 'eggs'],
    displayOrder: 64
  },
  {
    id: 2865,
    vendorId: 28,
    categoryId: 2,
    name: 'Egg Hakka Noodle',
    description: 'Wok-tossed hakka noodles tossed with scrambled egg (Full: ₹130 / Half: ₹90)',
    price: '90.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg hakka', 'egg noodles', 'egg', 'eggs'],
    displayOrder: 65
  },
  {
    id: 2866,
    vendorId: 28,
    categoryId: 2,
    name: 'Chicken Noodle',
    description: 'Stir-fried noodles with seasoned shredded chicken and veggies (Full: ₹170 / Half: ₹120)',
    price: '120.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken noodles', 'noodles', 'nonveg'],
    displayOrder: 66
  },
  {
    id: 2867,
    vendorId: 28,
    categoryId: 2,
    name: 'Schezwan Noodle',
    description: 'Spicy wok-tossed noodles in zesty homemade Schezwan sauce (Full: ₹130 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['schezwan noodles', 'spicy'],
    displayOrder: 67
  },
  {
    id: 2868,
    vendorId: 28,
    categoryId: 1,
    name: 'French Fries',
    description: 'Crispy golden potato finger chips tossed with seasoning (Full: ₹110 / Half: ₹70)',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['french fries', 'fries', 'snack'],
    displayOrder: 68
  },
  {
    id: 2869,
    vendorId: 28,
    categoryId: 2,
    name: 'Honey Chilli Potato',
    description: 'Crispy potato fingers glazed with sweet chili honey sesame sauce (Full: ₹130 / Half: ₹90)',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['honey chilli potato', 'chinese', 'bestseller'],
    displayOrder: 69
  },
  {
    id: 2870,
    vendorId: 28,
    categoryId: 2,
    name: 'Chilli Potato',
    description: 'Spicy wok-tossed crispy potato fingers with green chilies and garlic (Full: ₹130 / Half: ₹90)',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilli potato', 'spicy'],
    displayOrder: 70
  },
  {
    id: 2871,
    vendorId: 28,
    categoryId: 2,
    name: 'Chilli Garlic Noodle',
    description: 'Noodles tossed with fiery red chilies, burnt garlic and herbs (Full: ₹140 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilli garlic', 'noodles'],
    displayOrder: 71
  },
  {
    id: 2872,
    vendorId: 28,
    categoryId: 2,
    name: 'Singapuri Noodle',
    description: 'Curried stir-fried noodles with turmeric, peppers and sprouts (Full: ₹150 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['singapuri noodles', 'noodles'],
    displayOrder: 72
  },
  {
    id: 2873,
    vendorId: 28,
    categoryId: 2,
    name: 'Veg Fried Rice',
    description: 'Wok-tossed rice with finely chopped garden vegetables (Full: ₹110 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fried rice', 'veg fried rice'],
    displayOrder: 73
  },
  {
    id: 2874,
    vendorId: 28,
    categoryId: 2,
    name: 'Egg Fried Rice',
    description: 'Savory fried rice tossed with scrambled eggs and spring onions (Full: ₹140 / Half: ₹90)',
    price: '90.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg fried rice', 'rice', 'egg', 'eggs'],
    displayOrder: 74
  },
  {
    id: 2875,
    vendorId: 28,
    categoryId: 2,
    name: 'Chicken Fried Rice',
    description: 'Wok-tossed fried rice with tender chicken chunks and veggies (Full: ₹170 / Half: ₹120)',
    price: '120.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken fried rice', 'nonveg'],
    displayOrder: 75
  },
  {
    id: 2876,
    vendorId: 28,
    categoryId: 2,
    name: 'Veg Manchurian (Dry)',
    description: 'Crispy vegetable balls tossed with ginger, garlic and green chilies (Full: ₹130 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['manchurian', 'dry manchurian', 'bestseller'],
    displayOrder: 76
  },
  {
    id: 2877,
    vendorId: 28,
    categoryId: 2,
    name: 'Veg Manchurian (Gravy)',
    description: 'Veg balls simmered in savory dark soy-garlic gravy (Full: ₹130 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['manchurian gravy'],
    displayOrder: 77
  },
  {
    id: 2878,
    vendorId: 28,
    categoryId: 2,
    name: 'Egg Chilli',
    description: 'Fried boiled egg pieces tossed in fiery chili garlic Indo-Chinese sauce (Full: ₹200 / Half: ₹100)',
    price: '100.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg chilli', 'egg', 'eggs', 'chinese'],
    displayOrder: 78
  },

  // ================= 🍝 PASTA (Category 1) =================
  {
    id: 2879,
    vendorId: 28,
    categoryId: 1,
    name: 'White Sauce Pasta',
    description: 'Penne pasta in rich creamy parmesan and herb white cheese sauce (Full: ₹170 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pasta', 'white sauce', 'cheesy'],
    displayOrder: 79
  },
  {
    id: 2880,
    vendorId: 28,
    categoryId: 1,
    name: 'Red Sauce Pasta',
    description: 'Tangy penne pasta tossed with fresh herb-infused tomato marinara sauce (Full: ₹170 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pasta', 'red sauce'],
    displayOrder: 80
  },
  {
    id: 2881,
    vendorId: 28,
    categoryId: 1,
    name: 'Pink Sauce Pasta',
    description: 'Chef special blend of creamy white sauce and tangy tomato red sauce (Full: ₹170 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pasta', 'pink sauce'],
    displayOrder: 81
  },

  // ================= 🫓 INDIAN BREADS (Category 4) =================
  {
    id: 2882,
    vendorId: 28,
    categoryId: 4,
    name: 'Tandoori Roti / Butter Roti',
    description: 'Whole wheat flatbread baked in clay oven with butter',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'tandoori roti', 'bread', 'under-50'],
    displayOrder: 82
  },
  {
    id: 2883,
    vendorId: 28,
    categoryId: 4,
    name: 'Tawa Roti / Butter Roti',
    description: 'Soft homestyle whole wheat tawa phulka with pure butter',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tawa roti', 'phulka', 'under-50'],
    displayOrder: 83
  },
  {
    id: 2884,
    vendorId: 28,
    categoryId: 4,
    name: 'Missi Roti',
    description: 'Nutritious gram flour (besan) flatbread flavored with ajwain and onion',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['missi roti', 'under-50'],
    displayOrder: 84
  },
  {
    id: 2885,
    vendorId: 28,
    categoryId: 4,
    name: 'Plain Naan',
    description: 'Soft leavened tandoor-baked refined flour bread',
    price: '35.00',
    isVeg: true,
    isAvailable: true,
    tags: ['naan', 'plain naan', 'under-50'],
    displayOrder: 85
  },
  {
    id: 2886,
    vendorId: 28,
    categoryId: 4,
    name: 'Butter Naan',
    description: 'Crispy, flaky tandoori naan brushed generously with melted butter',
    price: '45.00',
    isVeg: true,
    isAvailable: true,
    tags: ['butter naan', 'naan', 'under-50'],
    displayOrder: 86
  },
  {
    id: 2887,
    vendorId: 28,
    categoryId: 4,
    name: 'Garlic Naan',
    description: 'Tandoori naan topped with roasted minced garlic and fresh coriander',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['garlic naan', 'naan'],
    displayOrder: 87
  },
  {
    id: 2888,
    vendorId: 28,
    categoryId: 4,
    name: 'Lachha Parantha',
    description: 'Layered whole wheat tandoori parantha with crispy flaky folds',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['laccha paratha', 'under-50'],
    displayOrder: 88
  },
  {
    id: 2889,
    vendorId: 28,
    categoryId: 4,
    name: 'Stuffed Naan',
    description: 'Tandoori naan stuffed with spiced mashed potato and paneer',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['stuffed naan', 'naan'],
    displayOrder: 89
  },

  // ================= 🌯 EGG & ROLLS (Category 7) =================
  {
    id: 2890,
    vendorId: 28,
    categoryId: 7,
    name: 'Boiled Egg (2 Pcs)',
    description: 'Farm fresh boiled eggs served with chaat masala and black pepper',
    price: '30.00',
    isVeg: false,
    isAvailable: true,
    tags: ['boiled egg', 'egg', 'eggs', 'protein', 'under-50'],
    displayOrder: 90
  },
  {
    id: 2891,
    vendorId: 28,
    categoryId: 7,
    name: 'Egg Bhurji (2 Eggs)',
    description: 'Double egg scrambled with sauteed onions, tomatoes and green chilies',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg bhurji', 'egg', 'eggs', 'protein', 'under-50'],
    displayOrder: 91
  },
  {
    id: 2892,
    vendorId: 28,
    categoryId: 7,
    name: 'Double Omelet (2 Eggs)',
    description: 'Fluffy double egg spiced omelet cooked on tawa',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['omelet', 'egg', 'eggs', 'under-50'],
    displayOrder: 92
  },
  {
    id: 2893,
    vendorId: 28,
    categoryId: 7,
    name: 'Bread Omelet',
    description: 'Double egg spiced omelet wrapped around golden toasted bread slices',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['bread omelet', 'egg', 'eggs', 'breakfast', 'under-50'],
    displayOrder: 93
  },
  {
    id: 2894,
    vendorId: 28,
    categoryId: 7,
    name: 'Egg Roll',
    description: 'Crispy flaky paratha layered with double egg, fresh sliced onions and tangy sauces',
    price: '60.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg roll', 'roll', 'egg', 'eggs', 'bestseller'],
    displayOrder: 94
  },
  {
    id: 2895,
    vendorId: 28,
    categoryId: 7,
    name: 'Veg Roll',
    description: 'Fresh roll stuffed with spiced mixed vegetable filling and chutneys',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg roll', 'roll', 'under-50'],
    displayOrder: 95
  },
  {
    id: 2896,
    vendorId: 28,
    categoryId: 7,
    name: 'Paneer Veg Roll',
    description: 'Flaky roll packed with marinated spiced paneer cubes and veggies',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer roll', 'roll', 'protein'],
    displayOrder: 96
  },
  {
    id: 2897,
    vendorId: 28,
    categoryId: 7,
    name: 'Veg Cheese Roll',
    description: 'Stuffed crispy roll generously loaded with melted cheese and spiced veg mix',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cheese roll', 'roll', 'cheesy'],
    displayOrder: 97
  },
  {
    id: 2898,
    vendorId: 28,
    categoryId: 7,
    name: 'Egg & Chicken Roll',
    description: 'Special power-packed roll layered with double egg and spiced roasted chicken chunks',
    price: '120.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken roll', 'egg chicken roll', 'roll', 'nonveg', 'protein', 'bestseller'],
    displayOrder: 98
  },

  // ================= 🫓 PARATHAS (Category 8) =================
  {
    id: 2899,
    vendorId: 28,
    categoryId: 8,
    name: 'Aloo Paratha',
    description: 'Tawa paratha stuffed with spiced mashed potatoes, served with butter/curd',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paratha', 'aloo paratha', 'breakfast', 'under-50'],
    displayOrder: 99
  },
  {
    id: 2900,
    vendorId: 28,
    categoryId: 8,
    name: 'Aloo Pyaz Paratha',
    description: 'Stuffed paratha with potatoes, crunchy onions, and green chilies',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo pyaz paratha', 'paratha', 'under-50'],
    displayOrder: 100
  },
  {
    id: 2901,
    vendorId: 28,
    categoryId: 8,
    name: 'Gobi Paratha',
    description: 'Grated spiced cauliflower stuffed whole wheat paratha',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['gobi paratha', 'paratha', 'under-50'],
    displayOrder: 101
  },
  {
    id: 2902,
    vendorId: 28,
    categoryId: 8,
    name: 'Paneer Pyaz Paratha',
    description: 'Crumbled cottage cheese and onions stuffed crispy paratha',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer paratha', 'paratha', 'under-50'],
    displayOrder: 102
  },
  {
    id: 2903,
    vendorId: 28,
    categoryId: 8,
    name: 'Paneer Paratha',
    description: 'Loaded spiced paneer stuffed golden paratha',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer paratha', 'protein', 'bestseller'],
    displayOrder: 103
  },
  {
    id: 2904,
    vendorId: 28,
    categoryId: 8,
    name: 'Pyaz Paratha',
    description: 'Crispy paratha packed with spiced onions and coriander',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pyaz paratha', 'under-50'],
    displayOrder: 104
  },
  {
    id: 2905,
    vendorId: 28,
    categoryId: 8,
    name: 'Egg Onion Paratha',
    description: 'Layered paratha stuffed with egg bhurji and seasoned onions',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg paratha', 'paratha', 'egg', 'eggs', 'under-50'],
    displayOrder: 105
  },
  {
    id: 2906,
    vendorId: 28,
    categoryId: 8,
    name: 'Mix Paratha',
    description: 'Stuffed paratha loaded with paneer, aloo, gobi and onions',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix paratha', 'under-50'],
    displayOrder: 106
  },
  {
    id: 2907,
    vendorId: 28,
    categoryId: 8,
    name: 'Mooli Paratha',
    description: 'Shredded white radish and ajwain stuffed winter-special paratha',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mooli paratha', 'under-50'],
    displayOrder: 107
  },

  // ================= 🍜 MAGGI (Category 1) =================
  {
    id: 2908,
    vendorId: 28,
    categoryId: 1,
    name: 'Plain Maggi',
    description: 'Classic 2-minute masala Maggi cooked just right',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'plain maggi', 'under-50'],
    displayOrder: 108
  },
  {
    id: 2909,
    vendorId: 28,
    categoryId: 1,
    name: 'Veg Maggi',
    description: 'Masala Maggi tossed with carrots, peas, onions and capsicum',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg maggi', 'maggi', 'under-50'],
    displayOrder: 109
  },
  {
    id: 2910,
    vendorId: 28,
    categoryId: 1,
    name: 'Fry Maggi',
    description: 'Butter-fried spicy masala Maggi with caramelized onions and chillies',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fry maggi', 'maggi'],
    displayOrder: 110
  },
  {
    id: 2911,
    vendorId: 28,
    categoryId: 1,
    name: 'Paneer Maggi',
    description: 'Masala Maggi loaded with soft paneer cubes',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer maggi', 'maggi', 'protein'],
    displayOrder: 111
  },
  {
    id: 2912,
    vendorId: 28,
    categoryId: 1,
    name: 'Onion Tomato Maggi',
    description: 'Tangy Maggi cooked with extra sauteed onions and tomatoes',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'onion tomato maggi', 'under-50'],
    displayOrder: 112
  },
  {
    id: 2913,
    vendorId: 28,
    categoryId: 1,
    name: 'Cheese Maggi',
    description: 'Hot Maggi topped with generous melted processed cheese',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cheese maggi', 'maggi', 'cheesy'],
    displayOrder: 113
  },
  {
    id: 2914,
    vendorId: 28,
    categoryId: 1,
    name: 'Chicken Maggi',
    description: 'Masala Maggi tossed with spiced shredded chicken chunks',
    price: '120.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken maggi', 'maggi', 'nonveg'],
    displayOrder: 114
  },
  {
    id: 2915,
    vendorId: 28,
    categoryId: 1,
    name: 'Egg Bhurji Maggi',
    description: 'Spicy Maggi topped with scrambled double eggs',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg maggi', 'maggi', 'egg', 'eggs', 'under-50'],
    displayOrder: 115
  },

  // ================= 🥪 SANDWICHES & BURGERS (Category 1) =================
  {
    id: 2916,
    vendorId: 28,
    categoryId: 1,
    name: 'Plain Veg Sandwich',
    description: 'Soft bread slices with cucumber, tomato and mint chutney',
    price: '35.00',
    isVeg: true,
    isAvailable: true,
    tags: ['sandwich', 'plain sandwich', 'under-50'],
    displayOrder: 116
  },
  {
    id: 2917,
    vendorId: 28,
    categoryId: 1,
    name: 'Grilled Veg Sandwich',
    description: 'Golden grilled sandwich with seasoned vegetable filling',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['grilled sandwich', 'sandwich', 'under-50'],
    displayOrder: 117
  },
  {
    id: 2918,
    vendorId: 28,
    categoryId: 1,
    name: 'Cheese Sandwich',
    description: 'Toasted sandwich stuffed with melted cheese and herbs',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cheese sandwich', 'sandwich', 'cheesy', 'under-50'],
    displayOrder: 118
  },
  {
    id: 2919,
    vendorId: 28,
    categoryId: 1,
    name: 'Thousand Island Veg Sandwich',
    description: 'Grilled sandwich layered with veggies and creamy thousand island spread',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['thousand island', 'sandwich'],
    displayOrder: 119
  },
  {
    id: 2920,
    vendorId: 28,
    categoryId: 1,
    name: 'Grilled Paneer Sandwich',
    description: 'Grilled sandwich packed with spiced paneer slices and veggies',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer sandwich', 'sandwich', 'protein'],
    displayOrder: 120
  },
  {
    id: 2921,
    vendorId: 28,
    categoryId: 1,
    name: 'Tandoori Sandwich',
    description: 'Grilled sandwich with smoky tandoori-spiced filling',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tandoori sandwich', 'sandwich'],
    displayOrder: 121
  },
  {
    id: 2922,
    vendorId: 28,
    categoryId: 1,
    name: 'Double Cheese Grilled Sandwich',
    description: 'Extra loaded double layer melted cheese grilled sandwich',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['double cheese', 'sandwich', 'cheesy'],
    displayOrder: 122
  },
  {
    id: 2923,
    vendorId: 28,
    categoryId: 1,
    name: 'Grilled Chicken Sandwich',
    description: 'Grilled sandwich filled with shredded spiced chicken and mayo',
    price: '80.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken sandwich', 'sandwich', 'nonveg'],
    displayOrder: 123
  },
  {
    id: 2924,
    vendorId: 28,
    categoryId: 1,
    name: 'Basic Veg Burger',
    description: 'Crispy potato patty burger with onion, tomato and tangy burger sauce',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['burger', 'veg burger', 'under-50'],
    displayOrder: 124
  },
  {
    id: 2925,
    vendorId: 28,
    categoryId: 1,
    name: 'Grilled Veg Burger',
    description: 'Toasted burger with seasoned grilled veggie patty and fresh greens',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['grilled burger', 'burger', 'under-50'],
    displayOrder: 125
  },
  {
    id: 2926,
    vendorId: 28,
    categoryId: 1,
    name: 'Cheese Burger',
    description: 'Veggie patty burger with a slice of melted cheese',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cheese burger', 'burger', 'cheesy', 'under-50'],
    displayOrder: 126
  },
  {
    id: 2927,
    vendorId: 28,
    categoryId: 1,
    name: 'Cheese & Egg Burger',
    description: 'Burger with egg omelet, cheese slice and crisp veggies',
    price: '60.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg burger', 'burger', 'egg', 'eggs'],
    displayOrder: 127
  },
  {
    id: 2928,
    vendorId: 28,
    categoryId: 1,
    name: 'Tikki Burger',
    description: 'Desi aloo tikki burger with mint and sweet chutneys',
    price: '45.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tikki burger', 'burger', 'under-50'],
    displayOrder: 128
  },
  {
    id: 2929,
    vendorId: 28,
    categoryId: 1,
    name: 'Half Egg Fry Burger',
    description: 'Burger topped with a sunny-side half-fried egg and sauces',
    price: '60.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg fry burger', 'burger', 'egg', 'eggs'],
    displayOrder: 129
  },

  // ================= 🥣 RAITA, SALAD & SOUP (Category 4) =================
  {
    id: 2930,
    vendorId: 28,
    categoryId: 4,
    name: 'Pineapple Raita',
    description: 'Sweet and chilled whisked curd with diced pineapple chunks',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'pineapple raita'],
    displayOrder: 130
  },
  {
    id: 2931,
    vendorId: 28,
    categoryId: 4,
    name: 'Aloo Jeera Raita',
    description: 'Spiced curd with boiled potatoes and roasted cumin powder',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'aloo raita'],
    displayOrder: 131
  },
  {
    id: 2932,
    vendorId: 28,
    categoryId: 4,
    name: 'Boondi Raita',
    description: 'Classic chilled yogurt with crispy chickpea flour boondi and mint',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['boondi raita', 'raita'],
    displayOrder: 132
  },
  {
    id: 2933,
    vendorId: 28,
    categoryId: 4,
    name: 'Mint Raita (Pudina)',
    description: 'Refreshing yogurt dip blended with fresh garden mint',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mint raita', 'raita'],
    displayOrder: 133
  },
  {
    id: 2934,
    vendorId: 28,
    categoryId: 4,
    name: 'Mix Raita',
    description: 'Whisked yogurt with chopped cucumbers, onions, tomatoes and spices',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix raita', 'raita'],
    displayOrder: 134
  },
  {
    id: 2935,
    vendorId: 28,
    categoryId: 4,
    name: 'Kachumber Raita',
    description: 'Crisp diced onion, tomato, cucumber salad in chilled curd',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kachumber raita'],
    displayOrder: 135
  },
  {
    id: 2936,
    vendorId: 28,
    categoryId: 4,
    name: 'Tomato Mint Raita',
    description: 'Tangy tomato and cooling mint flavored raita',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tomato raita'],
    displayOrder: 136
  },
  {
    id: 2937,
    vendorId: 28,
    categoryId: 4,
    name: 'Lasuni Raita (Garlic Raita)',
    description: 'Special tempered yogurt with golden fried garlic and cumin',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lasuni raita', 'garlic raita'],
    displayOrder: 137
  },
  {
    id: 2938,
    vendorId: 28,
    categoryId: 4,
    name: 'Green Salad',
    description: 'Fresh sliced cucumbers, tomatoes, carrots, onions and green chilies',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['salad', 'healthy'],
    displayOrder: 138
  },
  {
    id: 2939,
    vendorId: 28,
    categoryId: 4,
    name: 'Onion Salad',
    description: 'Sliced onion rings with lemon wedges and chaat masala',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['onion salad'],
    displayOrder: 139
  },
  {
    id: 2940,
    vendorId: 28,
    categoryId: 4,
    name: 'Russian Salad',
    description: 'Diced potatoes, peas, pineapple and apples in rich creamy mayo dressing',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['russian salad'],
    displayOrder: 140
  },
  {
    id: 2941,
    vendorId: 28,
    categoryId: 4,
    name: 'Kachumber Salad',
    description: 'Finely diced cucumber, onion, tomato with lemon and herbs',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kachumber salad'],
    displayOrder: 141
  },
  {
    id: 2942,
    vendorId: 28,
    categoryId: 4,
    name: 'Mushroom Soup',
    description: 'Warm creamy cream of mushroom soup with herbs',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soup', 'mushroom soup'],
    displayOrder: 142
  },
  {
    id: 2943,
    vendorId: 28,
    categoryId: 4,
    name: 'Sour Veg Soup (Hot & Sour)',
    description: 'Spicy and tangy Indo-Chinese vegetable soup with mushrooms',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soup', 'hot and sour'],
    displayOrder: 143
  },
  {
    id: 2944,
    vendorId: 28,
    categoryId: 4,
    name: 'Mix Vegetable Soup',
    description: 'Clear healthy soup with finely chopped garden vegetables',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soup', 'veg soup'],
    displayOrder: 144
  },
  {
    id: 2945,
    vendorId: 28,
    categoryId: 4,
    name: 'Tomato Soup',
    description: 'Rich velvety cream of tomato soup served with fried bread croutons',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tomato soup', 'soup'],
    displayOrder: 145
  },

  // ================= ☕ BEVERAGES & CHAI/COLD (Category 3 / 8) =================
  {
    id: 2946,
    vendorId: 28,
    categoryId: 8,
    name: 'Hot Tea',
    description: 'Homestyle brewed hot milk tea',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tea', 'chai', 'beverage', 'under-50'],
    displayOrder: 146
  },
  {
    id: 2947,
    vendorId: 28,
    categoryId: 8,
    name: 'Special Milk Tea',
    description: 'Rich, creamy boiled milk tea with ginger and cardamom',
    price: '25.00',
    isVeg: true,
    isAvailable: true,
    tags: ['milk tea', 'chai', 'under-50'],
    displayOrder: 147
  },
  {
    id: 2948,
    vendorId: 28,
    categoryId: 8,
    name: 'Black Tea',
    description: 'Refreshing black lemon tea brewed without milk',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['black tea', 'tea', 'under-50'],
    displayOrder: 148
  },
  {
    id: 2949,
    vendorId: 28,
    categoryId: 8,
    name: 'Hot Coffee',
    description: 'Fresh frothy hot coffee made with pure milk',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['coffee', 'hot coffee', 'under-50'],
    displayOrder: 149
  },
  {
    id: 2950,
    vendorId: 28,
    categoryId: 3,
    name: 'Cold Coffee',
    description: 'Chilled frothy blended cold coffee',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cold coffee', 'coffee', 'beverage', 'under-50'],
    displayOrder: 150
  },
  {
    id: 2951,
    vendorId: 28,
    categoryId: 3,
    name: 'Butter Milk (Chhaach)',
    description: 'Chilled refreshing spiced salted buttermilk with roasted cumin',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['butter milk', 'chaas', 'beverage', 'under-50'],
    displayOrder: 151
  },
  {
    id: 2952,
    vendorId: 28,
    categoryId: 3,
    name: 'Lemon Water (Shikanji)',
    description: 'Sweet and salted freshly squeezed lemon water',
    price: '25.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lemon water', 'shikanji', 'under-50'],
    displayOrder: 152
  },
  {
    id: 2953,
    vendorId: 28,
    categoryId: 3,
    name: 'Soda Lemon Water',
    description: 'Fizzy carbonated lemon soda (sweet or salted)',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lemon soda', 'soda', 'under-50'],
    displayOrder: 153
  },
  {
    id: 2954,
    vendorId: 28,
    categoryId: 3,
    name: 'Meethi Lassi',
    description: 'Thick, creamy Punjabi sweet yogurt lassi',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lassi', 'sweet lassi', 'bestseller'],
    displayOrder: 154
  },
  {
    id: 2955,
    vendorId: 28,
    categoryId: 8,
    name: 'Roasted Papad',
    description: 'Crispy tandoor-roasted spiced lentil papad',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['papad', 'snack', 'under-50'],
    displayOrder: 155
  }
];
