export const EAT_AND_FUN_VENDOR = {
  id: 27,
  name: 'Eat and Fun Restaurant',
  slug: 'eat-and-fun',
  phone: '8569813799',
  whatsapp: '8569836799',
  address: 'Opposite NIT Kurukshetra, Kurukshetra',
  latitude: '29.9672',
  longitude: '76.8816',
  opensAt: '10:00',
  closesAt: '22:00',
  deliversTo: ['NIT Main Gate', 'NIT Back Gate', 'Girls Hostel'],
  image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
  isActive: true,
  isFeatured: true,
  displayOrder: 7,
  createdAt: new Date()
};

export const EAT_AND_FUN_MENU_ITEMS = [
  // ================= 🍱 THALIS (Category 4 - North Indian & Thali) =================
  {
    id: 2701,
    vendorId: 27,
    categoryId: 4,
    name: 'Veg Thali',
    description: 'Special Deluxe Meal: Daal Makhani + Kadhai Paneer + Shahi Paneer + Mix Veg + Rayta + Rice + 4 Tandoori Roti',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['thali', 'veg thali', 'paneer', 'dal makhani', 'lunch', 'dinner', 'bestseller'],
    displayOrder: 1
  },
  {
    id: 2702,
    vendorId: 27,
    categoryId: 4,
    name: 'Non Veg Thali',
    description: 'Complete Feast: H/M Chicken + Butter Chicken + Anda Kari (Egg Curry) + Biryani + 4 Roti + 1 Kabab + Salad',
    price: '240.00',
    isVeg: false,
    isAvailable: true,
    tags: ['thali', 'non veg thali', 'chicken', 'biryani', 'kabab', 'nonveg', 'bestseller'],
    displayOrder: 2
  },

  // ================= 🧀 VEG GRAVIES & PANEER (Category 4 - North Indian) =================
  {
    id: 2703,
    vendorId: 27,
    categoryId: 4,
    name: 'Kadhai Paneer (Half)',
    description: 'Cottage cheese cubes tossed with bell peppers, onions and crushed whole spices in wok',
    price: '170.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'kadhai paneer', 'gravy'],
    displayOrder: 3
  },
  {
    id: 2704,
    vendorId: 27,
    categoryId: 4,
    name: 'Kadhai Paneer (Full)',
    description: 'Cottage cheese cubes tossed with bell peppers, onions and crushed whole spices in wok (Full Portion)',
    price: '320.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'kadhai paneer', 'gravy'],
    displayOrder: 4
  },
  {
    id: 2705,
    vendorId: 27,
    categoryId: 4,
    name: 'Shahi Paneer (Half)',
    description: 'Royal creamy Mughlai gravy cooked with soft paneer cubes and mild spices',
    price: '170.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'shahi paneer', 'creamy', 'bestseller'],
    displayOrder: 5
  },
  {
    id: 2706,
    vendorId: 27,
    categoryId: 4,
    name: 'Shahi Paneer (Full)',
    description: 'Royal creamy Mughlai gravy cooked with soft paneer cubes and mild spices (Full Portion)',
    price: '320.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'shahi paneer', 'creamy', 'bestseller'],
    displayOrder: 6
  },
  {
    id: 2707,
    vendorId: 27,
    categoryId: 4,
    name: 'Paneer Butter Masala (Half)',
    description: 'Rich buttery tomato cashew gravy with succulent paneer chunks',
    price: '170.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'butter masala', 'gravy'],
    displayOrder: 7
  },
  {
    id: 2708,
    vendorId: 27,
    categoryId: 4,
    name: 'Paneer Butter Masala (Full)',
    description: 'Rich buttery tomato cashew gravy with succulent paneer chunks (Full Portion)',
    price: '320.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'butter masala', 'gravy'],
    displayOrder: 8
  },
  {
    id: 2709,
    vendorId: 27,
    categoryId: 4,
    name: 'Paneer Lababdar (Half)',
    description: 'Chef special grated & cubed paneer in a mildly sweet and spicy onion tomato gravy',
    price: '190.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer lababdar', 'special'],
    displayOrder: 9
  },
  {
    id: 2710,
    vendorId: 27,
    categoryId: 4,
    name: 'Paneer Lababdar (Full)',
    description: 'Chef special grated & cubed paneer in a mildly sweet and spicy onion tomato gravy (Full Portion)',
    price: '350.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer lababdar', 'special'],
    displayOrder: 10
  },
  {
    id: 2711,
    vendorId: 27,
    categoryId: 4,
    name: 'Paneer Do Pyaza (Half)',
    description: 'Paneer cooked with generous double onions, tomatoes and fragrant Indian spices',
    price: '170.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer do pyaza'],
    displayOrder: 11
  },
  {
    id: 2712,
    vendorId: 27,
    categoryId: 4,
    name: 'Paneer Do Pyaza (Full)',
    description: 'Paneer cooked with generous double onions, tomatoes and fragrant Indian spices (Full Portion)',
    price: '320.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer do pyaza'],
    displayOrder: 12
  },
  {
    id: 2713,
    vendorId: 27,
    categoryId: 4,
    name: 'Daal Makhani (Half)',
    description: 'Slow-cooked black lentils simmered overnight with butter and fresh cream',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal makhani', 'lentils', 'bestseller'],
    displayOrder: 13
  },
  {
    id: 2714,
    vendorId: 27,
    categoryId: 4,
    name: 'Daal Makhani (Full)',
    description: 'Slow-cooked black lentils simmered overnight with butter and fresh cream (Full Portion)',
    price: '250.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal makhani', 'lentils', 'bestseller'],
    displayOrder: 14
  },
  {
    id: 2715,
    vendorId: 27,
    categoryId: 4,
    name: 'Mix Veg (Half)',
    description: 'Fresh seasonal vegetables cooked in a flavorful spiced homestyle masala',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix veg', 'vegetables'],
    displayOrder: 15
  },
  {
    id: 2716,
    vendorId: 27,
    categoryId: 4,
    name: 'Mix Veg (Full)',
    description: 'Fresh seasonal vegetables cooked in a flavorful spiced homestyle masala (Full Portion)',
    price: '250.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix veg', 'vegetables'],
    displayOrder: 16
  },

  // ================= 🫓 ROTI TANDOOR SE (Category 4) =================
  {
    id: 2717,
    vendorId: 27,
    categoryId: 4,
    name: 'Plain Roti (Tandoor)',
    description: 'Crisp hot clay oven baked whole wheat tandoori roti',
    price: '10.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'tandoori roti', 'bread', 'under-50'],
    displayOrder: 17
  },
  {
    id: 2718,
    vendorId: 27,
    categoryId: 4,
    name: 'Butter Roti (Tandoor)',
    description: 'Clay oven baked tandoori roti brushed generously with melted butter',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'butter roti', 'bread', 'under-50'],
    displayOrder: 18
  },
  {
    id: 2719,
    vendorId: 27,
    categoryId: 4,
    name: 'Plain Naan',
    description: 'Soft and fluffy refined flour tandoori naan',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['naan', 'plain naan', 'bread', 'under-50'],
    displayOrder: 19
  },
  {
    id: 2720,
    vendorId: 27,
    categoryId: 4,
    name: 'Butter Naan',
    description: 'Golden blistered tandoori naan brushed with creamy butter',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['naan', 'butter naan', 'bread', 'under-50', 'bestseller'],
    displayOrder: 20
  },

  // ================= 🥣 RAYTA & SALAD (Category 4) =================
  {
    id: 2721,
    vendorId: 27,
    categoryId: 4,
    name: 'Plain Rayta (Half)',
    description: 'Cool whipped seasoned curd with roasted cumin and black salt',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rayta', 'curd', 'side'],
    displayOrder: 21
  },
  {
    id: 2722,
    vendorId: 27,
    categoryId: 4,
    name: 'Plain Rayta (Full)',
    description: 'Cool whipped seasoned curd with roasted cumin and black salt (Full Portion)',
    price: '130.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rayta', 'curd', 'side'],
    displayOrder: 22
  },
  {
    id: 2723,
    vendorId: 27,
    categoryId: 4,
    name: 'Boondi Rayta (Half)',
    description: 'Creamy spiced curd mixed with crispy golden gram flour pearls (boondi)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rayta', 'boondi rayta', 'side'],
    displayOrder: 23
  },
  {
    id: 2724,
    vendorId: 27,
    categoryId: 4,
    name: 'Boondi Rayta (Full)',
    description: 'Creamy spiced curd mixed with crispy golden gram flour pearls (boondi) (Full)',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rayta', 'boondi rayta', 'side'],
    displayOrder: 24
  },
  {
    id: 2725,
    vendorId: 27,
    categoryId: 4,
    name: 'Mix Veg Rayta (Half)',
    description: 'Chilled curd blended with chopped cucumber, tomato, onion and mint',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rayta', 'mix veg rayta', 'side'],
    displayOrder: 25
  },
  {
    id: 2726,
    vendorId: 27,
    categoryId: 4,
    name: 'Mix Veg Rayta (Full)',
    description: 'Chilled curd blended with chopped cucumber, tomato, onion and mint (Full)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rayta', 'mix veg rayta', 'side'],
    displayOrder: 26
  },
  {
    id: 2727,
    vendorId: 27,
    categoryId: 4,
    name: 'Salad (Onion)',
    description: 'Fresh sliced red onions seasoned with lemon and chat masala',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['salad', 'onion salad', 'under-50'],
    displayOrder: 27
  },
  {
    id: 2728,
    vendorId: 27,
    categoryId: 4,
    name: 'Green Salad',
    description: 'Platter of sliced cucumber, tomatoes, onions, carrots and green chilies',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['salad', 'green salad', 'healthy'],
    displayOrder: 28
  },

  // ================= 🍚 BIRYANI (Category 4 - Serves 1) =================
  {
    id: 2729,
    vendorId: 27,
    categoryId: 4,
    name: 'Muradabadi Biryani (Half)',
    description: 'Authentic mild aromatic Muradabadi style chicken dum biryani',
    price: '140.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'muradabadi biryani', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 29
  },
  {
    id: 2730,
    vendorId: 27,
    categoryId: 4,
    name: 'Muradabadi Biryani (Full)',
    description: 'Authentic mild aromatic Muradabadi style chicken dum biryani (Full Portion)',
    price: '270.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'muradabadi biryani', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 30
  },
  {
    id: 2731,
    vendorId: 27,
    categoryId: 4,
    name: 'Hyderabadi Biryani (Half)',
    description: 'Spicy rich Hyderabadi layered chicken biryani infused with saffron and fried onions',
    price: '140.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'hyderabadi biryani', 'chicken', 'nonveg'],
    displayOrder: 31
  },
  {
    id: 2732,
    vendorId: 27,
    categoryId: 4,
    name: 'Hyderabadi Biryani (Full)',
    description: 'Spicy rich Hyderabadi layered chicken biryani infused with saffron and fried onions (Full)',
    price: '270.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'hyderabadi biryani', 'chicken', 'nonveg'],
    displayOrder: 32
  },
  {
    id: 2733,
    vendorId: 27,
    categoryId: 4,
    name: 'Masala Biryani (Half)',
    description: 'Zesty pan-spiced chicken biryani cooked with fiery masala gravy',
    price: '140.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'masala biryani', 'chicken', 'nonveg'],
    displayOrder: 33
  },
  {
    id: 2734,
    vendorId: 27,
    categoryId: 4,
    name: 'Masala Biryani (Full)',
    description: 'Zesty pan-spiced chicken biryani cooked with fiery masala gravy (Full Portion)',
    price: '270.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'masala biryani', 'chicken', 'nonveg'],
    displayOrder: 34
  },
  {
    id: 2735,
    vendorId: 27,
    categoryId: 4,
    name: 'Shahi Tukkda Biryani (Half)',
    description: 'Special royal chicken biryani layered with rich gravy and aromatic spices',
    price: '150.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'shahi biryani', 'chicken', 'nonveg', 'special'],
    displayOrder: 35
  },
  {
    id: 2736,
    vendorId: 27,
    categoryId: 4,
    name: 'Shahi Tukkda Biryani (Full)',
    description: 'Special royal chicken biryani layered with rich gravy and aromatic spices (Full)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'shahi biryani', 'chicken', 'nonveg', 'special'],
    displayOrder: 36
  },
  {
    id: 2737,
    vendorId: 27,
    categoryId: 4,
    name: 'Egg Rice',
    description: 'Fragrant basmati rice stir-fried with seasoned scrambled eggs and mild spices',
    price: '160.00',
    isVeg: false,
    isAvailable: true,
    tags: ['rice', 'egg rice', 'egg', 'nonveg'],
    displayOrder: 37
  },
  {
    id: 2738,
    vendorId: 27,
    categoryId: 4,
    name: 'Veg Biryani',
    description: 'Basmati dum rice layered with seasoned mixed vegetables, paneer and mint',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['biryani', 'veg biryani', 'rice'],
    displayOrder: 38
  },

  // ================= 🍗 CHICKEN IN GRAVY (Category 4 - Serves 1 KG / Half Kg / Full Kg) =================
  {
    id: 2739,
    vendorId: 27,
    categoryId: 4,
    name: 'H/M Chicken (Handi Murgh - Half Kg)',
    description: 'Slow-cooked traditional clay pot handi chicken in rich spicy onion-tomato gravy',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'handi chicken', 'curry', 'nonveg'],
    displayOrder: 39
  },
  {
    id: 2740,
    vendorId: 27,
    categoryId: 4,
    name: 'H/M Chicken (Handi Murgh - Full Kg)',
    description: 'Slow-cooked traditional clay pot handi chicken in rich spicy onion-tomato gravy (1 KG Full)',
    price: '500.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'handi chicken', 'curry', 'nonveg', 'bestseller'],
    displayOrder: 40
  },
  {
    id: 2741,
    vendorId: 27,
    categoryId: 4,
    name: 'Chicken Changezi (Half Kg)',
    description: 'Old Delhi style royal chicken roasted and simmered in a tangy velvety milk & tomato gravy',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken changezi', 'gravy', 'nonveg', 'special'],
    displayOrder: 41
  },
  {
    id: 2742,
    vendorId: 27,
    categoryId: 4,
    name: 'Chicken Changezi (Full Kg)',
    description: 'Old Delhi style royal chicken roasted and simmered in a tangy velvety milk & tomato gravy (1 KG Full)',
    price: '550.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken changezi', 'gravy', 'nonveg', 'special'],
    displayOrder: 42
  },
  {
    id: 2743,
    vendorId: 27,
    categoryId: 4,
    name: 'Kadhai Chicken (Half Kg)',
    description: 'Tender chicken pieces cooked in iron wok with bell peppers, onions and crushed coriander',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'kadhai chicken', 'gravy', 'nonveg'],
    displayOrder: 43
  },
  {
    id: 2744,
    vendorId: 27,
    categoryId: 4,
    name: 'Kadhai Chicken (Full Kg)',
    description: 'Tender chicken pieces cooked in iron wok with bell peppers, onions and crushed coriander (1 KG Full)',
    price: '550.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'kadhai chicken', 'gravy', 'nonveg'],
    displayOrder: 44
  },
  {
    id: 2745,
    vendorId: 27,
    categoryId: 4,
    name: 'Butter Chicken (Half Kg)',
    description: 'Tandoori roasted chicken pieces simmered in silky butter, cashew and tomato makhani gravy',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'butter chicken', 'makhani', 'nonveg', 'bestseller'],
    displayOrder: 45
  },
  {
    id: 2746,
    vendorId: 27,
    categoryId: 4,
    name: 'Butter Chicken (Full Kg)',
    description: 'Tandoori roasted chicken pieces simmered in silky butter, cashew and tomato makhani gravy (1 KG Full)',
    price: '550.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'butter chicken', 'makhani', 'nonveg', 'bestseller'],
    displayOrder: 46
  },
  {
    id: 2747,
    vendorId: 27,
    categoryId: 4,
    name: 'Chicken Lababdar (Half Kg)',
    description: 'Chef signature chicken dish with rich tomato gravy, chopped onions, ginger and butter',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken lababdar', 'nonveg'],
    displayOrder: 47
  },
  {
    id: 2748,
    vendorId: 27,
    categoryId: 4,
    name: 'Chicken Lababdar (Full Kg)',
    description: 'Chef signature chicken dish with rich tomato gravy, chopped onions, ginger and butter (1 KG Full)',
    price: '550.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken lababdar', 'nonveg'],
    displayOrder: 48
  },

  // ================= 🍗 TANDOORI CUISINE & CHICKEN FRY (Category 4) =================
  {
    id: 2749,
    vendorId: 27,
    categoryId: 4,
    name: 'Tandoori Chicken (Half Kg)',
    description: 'Whole chicken marinated in yogurt and tandoori spices, charcoal roasted to smoky perfection',
    price: '320.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'tandoori chicken', 'tandoori', 'nonveg', 'bestseller'],
    displayOrder: 49
  },
  {
    id: 2750,
    vendorId: 27,
    categoryId: 4,
    name: 'Tandoori Chicken (Full Kg)',
    description: 'Whole chicken marinated in yogurt and tandoori spices, charcoal roasted to smoky perfection (1 KG Full)',
    price: '580.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'tandoori chicken', 'tandoori', 'nonveg', 'bestseller'],
    displayOrder: 50
  },
  {
    id: 2751,
    vendorId: 27,
    categoryId: 1,
    name: 'Chicken Fry (KFC Style - Half Kg)',
    description: 'Ultra crispy spiced golden deep-fried chicken with crunchy batter coating',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken fry', 'crispy', 'snack', 'nonveg', 'bestseller'],
    displayOrder: 51
  },
  {
    id: 2752,
    vendorId: 27,
    categoryId: 1,
    name: 'Chicken Fry (KFC Style - Full Kg)',
    description: 'Ultra crispy spiced golden deep-fried chicken with crunchy batter coating (Full 1 KG)',
    price: '550.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken fry', 'crispy', 'snack', 'nonveg', 'bestseller'],
    displayOrder: 52
  },

  // ================= 🥤 BEVERAGES (Category 3) =================
  {
    id: 2753,
    vendorId: 27,
    categoryId: 3,
    name: 'Cold Drink (MRP)',
    description: 'Chilled bottled beverage (Pepsi / Sprite / Mirinda / Coca Cola / Bisleri on MRP)',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cold drink', 'beverage', 'pepsi', 'sprite', 'coke', 'under-50'],
    displayOrder: 53
  }
];
