export const FOOD_POINT_VENDOR = {
  id: 24,
  name: 'Food Point',
  slug: 'food-point',
  phone: '7027708882',
  whatsapp: '9504316289',
  address: 'NIT Main Gate, Kurukshetra',
  latitude: '29.9665',
  longitude: '76.8810',
  opensAt: '08:30',
  closesAt: '23:30',
  deliversTo: ['NIT Main Gate', 'NIT Back Gate', 'Girls Hostel'],
  image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=80',
  isActive: true,
  isFeatured: true,
  displayOrder: 4,
  createdAt: new Date()
};

export const FOOD_POINT_MENU_ITEMS = [
  // ================= 🫓 PARANTHA (Category 4 - North Indian Breads) =================
  {
    id: 2401,
    vendorId: 24,
    categoryId: 4,
    name: 'Plain Parantha',
    description: 'Hot crisped tawa parantha',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'plain paratha', 'under-50'],
    displayOrder: 1
  },
  {
    id: 2402,
    vendorId: 24,
    categoryId: 4,
    name: 'Aloo Pyaz Parantha',
    description: 'Golden tawa parantha stuffed with spiced potatoes and chopped onions',
    price: '35.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'aloo pyaz', 'bestseller', 'under-50'],
    displayOrder: 2
  },
  {
    id: 2403,
    vendorId: 24,
    categoryId: 4,
    name: 'Gobhi Parantha',
    description: 'Stuffed parantha packed with seasoned grated cauliflower',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'gobhi paratha', 'under-50'],
    displayOrder: 3
  },
  {
    id: 2404,
    vendorId: 24,
    categoryId: 4,
    name: 'Plain Paneer Parantha',
    description: 'Crispy parantha loaded with generous grated cottage cheese',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'paneer paratha', 'protein'],
    displayOrder: 4
  },
  {
    id: 2405,
    vendorId: 24,
    categoryId: 4,
    name: 'Paneer Pyaz Parantha',
    description: 'Delicious mix of spiced paneer and crunchy onions in layered parantha',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'paneer pyaz', 'protein', 'under-50'],
    displayOrder: 5
  },
  {
    id: 2406,
    vendorId: 24,
    categoryId: 4,
    name: 'Cheese Parantha',
    description: 'Melted cheese stuffed crispy golden parantha',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'cheese paratha', 'cheese'],
    displayOrder: 6
  },
  {
    id: 2407,
    vendorId: 24,
    categoryId: 4,
    name: 'Double Egg Parantha',
    description: 'Layered parantha rolled with 2 scrambled spiced eggs',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['parantha', 'egg paratha', 'egg', 'protein', 'under-50', 'nonveg'],
    displayOrder: 7
  },
  {
    id: 2408,
    vendorId: 24,
    categoryId: 4,
    name: 'Sattu Parantha',
    description: 'Authentic Bihari style roasted gram sattu stuffed parantha with mustard punch',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'sattu paratha', 'desi', 'protein', 'under-50', 'bestseller'],
    displayOrder: 8
  },

  // ================= ☕ SNACKS & CHAI (Category 8 - Chai & Snacks) =================
  {
    id: 2409,
    vendorId: 24,
    categoryId: 8,
    name: 'Poha',
    description: 'Light steamed flattened rice tempered with mustard seeds, peanuts and fresh coriander',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['poha', 'breakfast', 'healthy', 'under-50'],
    displayOrder: 9
  },
  {
    id: 2410,
    vendorId: 24,
    categoryId: 2,
    name: 'Chowmein',
    description: 'Wok tossed street style vegetable chowmein noodles',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chowmein', 'noodles', 'chinese'],
    displayOrder: 10
  },
  {
    id: 2411,
    vendorId: 24,
    categoryId: 8,
    name: 'Egg Bhurji',
    description: 'Spiced scrambled double eggs cooked with onions and chillies',
    price: '40.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg bhurji', 'egg', 'protein', 'under-50', 'nonveg'],
    displayOrder: 11
  },
  {
    id: 2412,
    vendorId: 24,
    categoryId: 8,
    name: 'Plain Maggi',
    description: 'Classic 2-minute piping hot masala Maggi',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'plain maggi', 'snack', 'under-50'],
    displayOrder: 12
  },
  {
    id: 2413,
    vendorId: 24,
    categoryId: 8,
    name: 'Veg Maggi',
    description: 'Maggi noodles loaded with sweet peas, carrots and onions',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'veg maggi', 'under-50'],
    displayOrder: 13
  },
  {
    id: 2414,
    vendorId: 24,
    categoryId: 8,
    name: 'Egg Maggi',
    description: 'Masala Maggi tossed with scrambled egg and herbs',
    price: '60.00',
    isVeg: false,
    isAvailable: true,
    tags: ['maggi', 'egg maggi', 'egg', 'protein', 'nonveg'],
    displayOrder: 14
  },
  {
    id: 2415,
    vendorId: 24,
    categoryId: 8,
    name: 'Bhurji Maggi',
    description: 'Loaded spicy Maggi topped with double egg bhurji',
    price: '80.00',
    isVeg: false,
    isAvailable: true,
    tags: ['maggi', 'bhurji maggi', 'egg', 'protein', 'nonveg'],
    displayOrder: 15
  },
  {
    id: 2416,
    vendorId: 24,
    categoryId: 1,
    name: 'Cheese Sandwich',
    description: 'Grilled sandwich stuffed with melted cheese and spiced veggie mix',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['sandwich', 'cheese sandwich', 'under-50'],
    displayOrder: 16
  },
  {
    id: 2417,
    vendorId: 24,
    categoryId: 8,
    name: 'Bread Omelet',
    description: 'Toasted bread slices wrapped around a fluffy spiced double egg omelet',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['bread omelet', 'egg', 'breakfast', 'under-50', 'nonveg'],
    displayOrder: 17
  },
  {
    id: 2418,
    vendorId: 24,
    categoryId: 8,
    name: 'Desi Chai (Tea)',
    description: 'Hot brewed milk tea infused with cardamom and ginger',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chai', 'tea', 'under-50'],
    displayOrder: 18
  },
  {
    id: 2419,
    vendorId: 24,
    categoryId: 8,
    name: 'Hot Coffee',
    description: 'Fresh frothy hot coffee',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['coffee', 'hot coffee', 'under-50'],
    displayOrder: 19
  },

  // ================= 🍚 RICE & BIRYANI (Category 4 - Rice) =================
  {
    id: 2420,
    vendorId: 24,
    categoryId: 4,
    name: 'Plain Rice',
    description: 'Steamed basmati rice',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'plain rice'],
    displayOrder: 20
  },
  {
    id: 2421,
    vendorId: 24,
    categoryId: 4,
    name: 'Jeera Rice',
    description: 'Basmati rice tempered with roasted cumin seeds and ghee',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'jeera rice'],
    displayOrder: 21
  },
  {
    id: 2422,
    vendorId: 24,
    categoryId: 4,
    name: 'Veg Fried Rice',
    description: 'Wok tossed fried rice with mixed vegetables and soy sauce',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'fried rice', 'chinese'],
    displayOrder: 22
  },
  {
    id: 2423,
    vendorId: 24,
    categoryId: 4,
    name: 'Egg Rice',
    description: 'Fried rice scrambled with seasoned farm fresh eggs',
    price: '120.00',
    isVeg: false,
    isAvailable: true,
    tags: ['rice', 'egg rice', 'egg', 'protein', 'nonveg'],
    displayOrder: 23
  },
  {
    id: 2424,
    vendorId: 24,
    categoryId: 4,
    name: 'Veg Biryani',
    description: 'Fragrant spiced layered biryani with vegetables and mint',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['biryani', 'veg biryani'],
    displayOrder: 24
  },
  {
    id: 2425,
    vendorId: 24,
    categoryId: 4,
    name: 'Egg Biryani',
    description: 'Aromatic basmati biryani layered with spiced boiled eggs',
    price: '130.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'egg biryani', 'egg', 'protein', 'nonveg'],
    displayOrder: 25
  },
  {
    id: 2426,
    vendorId: 24,
    categoryId: 4,
    name: 'Chicken Biryani Rice',
    description: 'Flavorful spiced dum biryani with succulent chicken pieces (Full: ₹180 / Half: ₹120)',
    price: '120.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'chicken biryani', 'chicken', 'protein', 'bestseller', 'nonveg'],
    displayOrder: 26
  },

  // ================= 🍲 PANEER & VEGETABLE (Category 4 - North Indian Curries) =================
  {
    id: 2427,
    vendorId: 24,
    categoryId: 4,
    name: 'Mix Veg.',
    description: 'Seasonal mixed vegetables in spiced onion tomato curry (Full: ₹120 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix veg', 'curry'],
    displayOrder: 27
  },
  {
    id: 2428,
    vendorId: 24,
    categoryId: 4,
    name: 'Chana Masala',
    description: 'Punjabi style spiced chickpeas curry (Full: ₹110 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chana masala', 'protein'],
    displayOrder: 28
  },
  {
    id: 2429,
    vendorId: 24,
    categoryId: 4,
    name: 'Aaloo Jeera',
    description: 'Dry potato cubes tempered with roasted cumin and turmeric',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo jeera', 'dry sabji'],
    displayOrder: 29
  },
  {
    id: 2430,
    vendorId: 24,
    categoryId: 4,
    name: 'Dal Makhani',
    description: 'Slow-cooked black lentils with butter and cream (Full: ₹120 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal makhani', 'dal', 'desi', 'bestseller'],
    displayOrder: 30
  },
  {
    id: 2431,
    vendorId: 24,
    categoryId: 4,
    name: 'Shahi Paneer',
    description: 'Soft cottage cheese in rich sweet and savory cashew tomato gravy (Full: ₹180 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shahi paneer', 'paneer', 'protein', 'bestseller'],
    displayOrder: 31
  },
  {
    id: 2432,
    vendorId: 24,
    categoryId: 4,
    name: 'Kadhai Paneer',
    description: 'Paneer and capsicum tossed with fresh ground kadhai spices (Full: ₹180 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kadhai paneer', 'paneer', 'protein', 'spicy'],
    displayOrder: 32
  },
  {
    id: 2433,
    vendorId: 24,
    categoryId: 4,
    name: 'Paneer Butter Masala',
    description: 'Paneer cubes simmered in buttery creamy tomato sauce (Full: ₹180 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer butter masala', 'paneer', 'protein'],
    displayOrder: 33
  },
  {
    id: 2434,
    vendorId: 24,
    categoryId: 4,
    name: 'Paneer Do Pyaza',
    description: 'Paneer simmered with double onions and aromatic herbs (Full: ₹170 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer do pyaza', 'paneer', 'protein'],
    displayOrder: 34
  },
  {
    id: 2435,
    vendorId: 24,
    categoryId: 4,
    name: 'Matar Paneer',
    description: 'Home-style green peas and cottage cheese curry (Full: ₹170 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['matar paneer', 'paneer', 'protein'],
    displayOrder: 35
  },
  {
    id: 2436,
    vendorId: 24,
    categoryId: 4,
    name: 'Plain Gravy',
    description: 'Smooth spiced base curry gravy (Full: ₹150 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['gravy', 'curry'],
    displayOrder: 36
  },
  {
    id: 2437,
    vendorId: 24,
    categoryId: 4,
    name: 'Egg Curry',
    description: 'Boiled eggs simmered in rich spiced curry (Full: ₹160 / Half: ₹100)',
    price: '100.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg curry', 'egg', 'protein', 'nonveg'],
    displayOrder: 37
  },
  {
    id: 2438,
    vendorId: 24,
    categoryId: 4,
    name: 'Aaloo Matar',
    description: 'Potatoes and sweet peas cooked in light tomato curry (Full: ₹120 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo matar', 'desi'],
    displayOrder: 38
  },
  {
    id: 2439,
    vendorId: 24,
    categoryId: 4,
    name: 'Tamatar Pyaz Fried',
    description: 'Spiced pan-fried tomato and onion masala fry (Full: ₹100 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tamatar pyaz', 'fry'],
    displayOrder: 39
  },
  {
    id: 2440,
    vendorId: 24,
    categoryId: 2,
    name: 'Cheese Chilli (Chilli Paneer)',
    description: 'Indo-Chinese style crispy paneer in soy-chilli sauce (Full: ₹180 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cheese chilli', 'chilli paneer', 'bestseller'],
    displayOrder: 40
  },

  // ================= 🍗 NON-VEG SPECIALTIES (Category 4) =================
  {
    id: 2441,
    vendorId: 24,
    categoryId: 4,
    name: 'Chicken Home Style Spicily',
    description: 'Spicy rustic desi dhaba style chicken curry (Full: ₹500 / Half: ₹300)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'home style chicken', 'protein', 'spicy', 'nonveg'],
    displayOrder: 41
  },
  {
    id: 2442,
    vendorId: 24,
    categoryId: 4,
    name: 'Butter Chicken',
    description: 'Tender chicken cooked in rich buttery makhani gravy (Full: ₹500 / Half: ₹300)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'butter chicken', 'protein', 'bestseller', 'nonveg'],
    displayOrder: 42
  },
  {
    id: 2443,
    vendorId: 24,
    categoryId: 4,
    name: 'Kadhai Chicken',
    description: 'Chicken tossed with capsicum and freshly ground kadhai masala (Full: ₹500 / Half: ₹300)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'kadai chicken', 'protein', 'spicy', 'nonveg'],
    displayOrder: 43
  },
  {
    id: 2444,
    vendorId: 24,
    categoryId: 2,
    name: 'Chilli Chicken',
    description: 'Crispy fried chicken tossed in fiery chilli garlic sauce (Full: ₹500 / Half: ₹300)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chilli chicken', 'chinese', 'nonveg'],
    displayOrder: 44
  },
  {
    id: 2445,
    vendorId: 24,
    categoryId: 4,
    name: 'Chicken Curry',
    description: 'Traditional Punjabi style chicken curry (Full: ₹500 / Half: ₹300)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken curry', 'protein', 'nonveg'],
    displayOrder: 45
  },
  {
    id: 2446,
    vendorId: 24,
    categoryId: 4,
    name: 'Chicken Mirch Masala',
    description: 'Fiery roasted pepper chicken curry (Full: ₹500 / Half: ₹300)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'mirch masala', 'spicy', 'nonveg'],
    displayOrder: 46
  },
  {
    id: 2447,
    vendorId: 24,
    categoryId: 4,
    name: 'Mutton Curry',
    description: 'Slow-simmered tender desi mutton curry with whole spices (Full: ₹950 / Half: ₹500)',
    price: '500.00',
    isVeg: false,
    isAvailable: true,
    tags: ['mutton', 'mutton curry', 'protein', 'special', 'nonveg'],
    displayOrder: 47
  },

  // ================= 🫓 ROTI (Category 4 - Breads) =================
  {
    id: 2448,
    vendorId: 24,
    categoryId: 4,
    name: 'Plain Roti (Tawa)',
    description: 'Fresh wheat tawa roti',
    price: '10.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'tawa roti', 'under-50'],
    displayOrder: 48
  },
  {
    id: 2449,
    vendorId: 24,
    categoryId: 4,
    name: 'Butter Roti (Tawa)',
    description: 'Tawa roti brushed with fresh butter',
    price: '12.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'butter roti', 'under-50'],
    displayOrder: 49
  },
  {
    id: 2450,
    vendorId: 24,
    categoryId: 4,
    name: 'Plain Parantha (Tawa)',
    description: 'Crispy layered tawa parantha',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'tawa paratha', 'under-50'],
    displayOrder: 50
  },
  {
    id: 2451,
    vendorId: 24,
    categoryId: 4,
    name: 'Lachha Parantha (Tawa)',
    description: 'Flaky multi-layered tawa parantha',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'laccha paratha', 'under-50'],
    displayOrder: 51
  },

  // ================= 🌯 ROLLS (Category 7 - Rolls & Wraps) =================
  {
    id: 2452,
    vendorId: 24,
    categoryId: 7,
    name: 'Veg Roll',
    description: 'Crispy roll stuffed with seasoned vegetables and tangy mint sauce',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roll', 'veg roll', 'snack', 'under-50'],
    displayOrder: 52
  },
  {
    id: 2453,
    vendorId: 24,
    categoryId: 7,
    name: 'Double Egg Roll',
    description: 'Flaky paratha rolled with 2 scrambled eggs, onions and sauces',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['roll', 'egg roll', 'egg', 'protein', 'under-50', 'nonveg'],
    displayOrder: 53
  },
  {
    id: 2454,
    vendorId: 24,
    categoryId: 7,
    name: 'Paneer Roll',
    description: 'Loaded with spiced tawa paneer cubes, onions and chutney',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roll', 'paneer roll', 'protein'],
    displayOrder: 54
  },
  {
    id: 2455,
    vendorId: 24,
    categoryId: 7,
    name: 'Chicken Roll',
    description: 'Juicy spiced chicken shreds wrapped in crispy golden bread',
    price: '80.00',
    isVeg: false,
    isAvailable: true,
    tags: ['roll', 'chicken roll', 'chicken', 'protein', 'bestseller', 'nonveg'],
    displayOrder: 55
  }
];
