export const HANGRY_CLUB_VENDOR = {
  id: 25,
  name: 'The Hangry Club',
  slug: 'the-hangry-club',
  phone: '8901570002',
  whatsapp: '8901570002',
  address: 'Opposite N.I.T Gate, Kurukshetra',
  latitude: '29.9670',
  longitude: '76.8814',
  opensAt: '12:30',
  closesAt: '22:30',
  deliversTo: ['NITKKR campus all'],
  image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
  isActive: true,
  isFeatured: true,
  displayOrder: 5,
  createdAt: new Date()
};

export const HANGRY_CLUB_MENU_ITEMS = [
  // ================= 🍗 TANDOORI SPECIAL NON-VEG (Category 4) =================
  {
    id: 2501,
    vendorId: 25,
    categoryId: 4,
    name: 'Tandoori Chicken',
    description: 'Juicy chicken roasted in clay oven with smoky marinade (Full: ₹480 / Half: ₹300)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['tandoori chicken', 'chicken', 'tandoori', 'protein', 'bestseller', 'nonveg'],
    displayOrder: 1
  },
  {
    id: 2502,
    vendorId: 25,
    categoryId: 4,
    name: 'Afghani Chicken',
    description: 'Char-grilled chicken coated in rich cashew cream and mild spices (Full: ₹500 / Half: ₹320)',
    price: '320.00',
    isVeg: false,
    isAvailable: true,
    tags: ['afghani chicken', 'chicken', 'creamy', 'protein', 'nonveg'],
    displayOrder: 2
  },
  {
    id: 2503,
    vendorId: 25,
    categoryId: 4,
    name: 'Tangri Kabab (4pc)',
    description: '4 succulent chicken drumsticks marinated in aromatic spices and char-grilled',
    price: '350.00',
    isVeg: false,
    isAvailable: true,
    tags: ['tangri kabab', 'chicken', 'kabab', 'protein', 'nonveg'],
    displayOrder: 3
  },
  {
    id: 2504,
    vendorId: 25,
    categoryId: 4,
    name: 'Kalmi Kabab (4pc)',
    description: '4 rich and tender chicken thigh/leg kababs spiced with royal herbs',
    price: '350.00',
    isVeg: false,
    isAvailable: true,
    tags: ['kalmi kabab', 'chicken', 'kabab', 'protein', 'nonveg'],
    displayOrder: 4
  },
  {
    id: 2505,
    vendorId: 25,
    categoryId: 4,
    name: 'Chicken Tikka (8pc)',
    description: '8 pieces of boneless chicken chunks char-grilled with red tandoori masala',
    price: '350.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken tikka', 'chicken', 'tikka', 'protein', 'bestseller', 'nonveg'],
    displayOrder: 5
  },
  {
    id: 2506,
    vendorId: 25,
    categoryId: 4,
    name: 'Chicken Malai Tikka (8pc)',
    description: '8 melt-in-mouth chicken tikka pieces in cheese and malai cream marinade',
    price: '350.00',
    isVeg: false,
    isAvailable: true,
    tags: ['malai tikka', 'chicken', 'creamy', 'protein', 'nonveg'],
    displayOrder: 6
  },
  {
    id: 2507,
    vendorId: 25,
    categoryId: 4,
    name: 'Chicken Wings (8pc)',
    description: '8 crispy grilled chicken wings tossed in signature spice rub',
    price: '350.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken wings', 'wings', 'chicken', 'snack', 'nonveg'],
    displayOrder: 7
  },
  {
    id: 2508,
    vendorId: 25,
    categoryId: 4,
    name: 'Chicken Seekh Kabab',
    description: 'Minced chicken skewers flavored with garlic, ginger, mint and spices',
    price: '320.00',
    isVeg: false,
    isAvailable: true,
    tags: ['seekh kabab', 'chicken', 'kabab', 'protein', 'nonveg'],
    displayOrder: 8
  },

  // ================= 🐟 SEA FOOD (Category 4) =================
  {
    id: 2509,
    vendorId: 25,
    categoryId: 4,
    name: 'Fish Tikka (8pc - Basa)',
    description: '8 boneless Basa fish fillets marinated in tandoori spices and char-roasted',
    price: '400.00',
    isVeg: false,
    isAvailable: true,
    tags: ['fish tikka', 'fish', 'seafood', 'protein', 'nonveg'],
    displayOrder: 9
  },
  {
    id: 2510,
    vendorId: 25,
    categoryId: 4,
    name: 'Fish Finger (Basa)',
    description: 'Crispy breaded golden Basa fish fingers served with tartar/mayo',
    price: '480.00',
    isVeg: false,
    isAvailable: true,
    tags: ['fish fingers', 'fish', 'seafood', 'crispy', 'nonveg'],
    displayOrder: 10
  },
  {
    id: 2511,
    vendorId: 25,
    categoryId: 4,
    name: 'Fish Curry (Basa)',
    description: 'Tender Basa fish simmered in flavorful mustard and tomato coastal curry',
    price: '480.00',
    isVeg: false,
    isAvailable: true,
    tags: ['fish curry', 'fish', 'seafood', 'curry', 'nonveg'],
    displayOrder: 11
  },
  {
    id: 2512,
    vendorId: 25,
    categoryId: 2,
    name: 'Fish Chilly (Basa)',
    description: 'Crispy Basa fish tossed in wok with bell peppers and spicy chilli soya sauce',
    price: '480.00',
    isVeg: false,
    isAvailable: true,
    tags: ['fish chilli', 'fish', 'chinese', 'seafood', 'nonveg'],
    displayOrder: 12
  },
  {
    id: 2513,
    vendorId: 25,
    categoryId: 4,
    name: 'Fish Pakoda (Basa)',
    description: 'Crunchy spiced Amritsari style fried fish pakoras with mint chutney',
    price: '410.00',
    isVeg: false,
    isAvailable: true,
    tags: ['fish pakoda', 'fish', 'seafood', 'snack', 'nonveg'],
    displayOrder: 13
  },
  {
    id: 2514,
    vendorId: 25,
    categoryId: 4,
    name: 'Fish Lemon Pepper',
    description: 'Zesty pan-seared Basa fish fillets seasoned with cracked black pepper & lemon',
    price: '480.00',
    isVeg: false,
    isAvailable: true,
    tags: ['lemon pepper fish', 'fish', 'seafood', 'nonveg'],
    displayOrder: 14
  },

  // ================= 🥢 CHICKEN CHINESE SPECIAL (Category 2) =================
  {
    id: 2515,
    vendorId: 25,
    categoryId: 2,
    name: 'Chilly Chicken (With Bone)',
    description: 'Classic wok-tossed spicy chilli chicken with bone (Full: ₹550 / Half: ₹350)',
    price: '350.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chilli chicken', 'chicken', 'chinese', 'spicy', 'nonveg'],
    displayOrder: 15
  },
  {
    id: 2516,
    vendorId: 25,
    categoryId: 2,
    name: 'Chilly Chicken (Boneless)',
    description: 'Boneless tender chicken tossed in spicy soya garlic glaze (Full: ₹600 / Half: ₹400)',
    price: '400.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chilli chicken', 'boneless chicken', 'chinese', 'bestseller', 'nonveg'],
    displayOrder: 16
  },
  {
    id: 2517,
    vendorId: 25,
    categoryId: 2,
    name: 'Chicken Pakoda (With Bone)',
    description: 'Crispy fried spiced chicken pakoras (Full: ₹520 / Half: ₹330)',
    price: '330.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken pakoda', 'chicken', 'snack', 'nonveg'],
    displayOrder: 17
  },
  {
    id: 2518,
    vendorId: 25,
    categoryId: 2,
    name: 'Chicken Pakoda (Boneless)',
    description: 'Crunchy boneless chicken fritters with chaat masala (Full: ₹560 / Half: ₹350)',
    price: '350.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken pakoda', 'boneless', 'chicken', 'nonveg'],
    displayOrder: 18
  },
  {
    id: 2519,
    vendorId: 25,
    categoryId: 2,
    name: 'Chicken Spring Roll',
    description: 'Crispy golden rolls packed with shredded chicken and veggies',
    price: '200.00',
    isVeg: false,
    isAvailable: true,
    tags: ['spring roll', 'chicken spring roll', 'chinese', 'nonveg'],
    displayOrder: 19
  },
  {
    id: 2520,
    vendorId: 25,
    categoryId: 2,
    name: 'Crispy Chicken (8pc)',
    description: '8 deep-fried crunchy seasoned chicken pieces with dip',
    price: '280.00',
    isVeg: false,
    isAvailable: true,
    tags: ['crispy chicken', 'chicken', 'finger food', 'nonveg'],
    displayOrder: 20
  },

  // ================= 🌯 KATHI ROLLS NON-VEG (Category 7) =================
  {
    id: 2521,
    vendorId: 25,
    categoryId: 7,
    name: 'Chicken Tikka Kathi Roll',
    description: 'Flaky laccha paratha stuffed with smoky chicken tikka and mint mayo',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['kathi roll', 'chicken tikka roll', 'chicken', 'bestseller', 'nonveg'],
    displayOrder: 21
  },
  {
    id: 2522,
    vendorId: 25,
    categoryId: 7,
    name: 'Chicken Seekh Roll',
    description: 'Juicy chicken seekh kababs rolled with onions and tangy chutney',
    price: '270.00',
    isVeg: false,
    isAvailable: true,
    tags: ['kathi roll', 'seekh roll', 'chicken', 'nonveg'],
    displayOrder: 22
  },
  {
    id: 2523,
    vendorId: 25,
    categoryId: 7,
    name: 'Chicken Malai Roll',
    description: 'Creamy chicken malai tikka rolled in toasted crispy flatbread',
    price: '270.00',
    isVeg: false,
    isAvailable: true,
    tags: ['kathi roll', 'malai roll', 'chicken', 'creamy', 'nonveg'],
    displayOrder: 23
  },
  {
    id: 2524,
    vendorId: 25,
    categoryId: 7,
    name: 'Egg Roll',
    description: 'Toasted paratha wrapped with double omelet, onion rings and sauces',
    price: '150.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg roll', 'kathi roll', 'egg', 'protein', 'nonveg'],
    displayOrder: 24
  },

  // ================= 🍲 MAIN COURSE NON-VEG (Category 4) =================
  {
    id: 2525,
    vendorId: 25,
    categoryId: 4,
    name: 'Butter Chicken',
    description: 'Signature rich and buttery makhani chicken curry (Full: ₹650 / Half: ₹400)',
    price: '400.00',
    isVeg: false,
    isAvailable: true,
    tags: ['butter chicken', 'chicken', 'curry', 'bestseller', 'nonveg'],
    displayOrder: 25
  },
  {
    id: 2526,
    vendorId: 25,
    categoryId: 4,
    name: 'Kadhai Chicken',
    description: 'Chicken cooked in wok with bell peppers and roasted spices (Full: ₹660 / Half: ₹410)',
    price: '410.00',
    isVeg: false,
    isAvailable: true,
    tags: ['kadai chicken', 'chicken', 'spicy', 'nonveg'],
    displayOrder: 26
  },
  {
    id: 2527,
    vendorId: 25,
    categoryId: 4,
    name: 'Chicken Curry',
    description: 'Classic rustic chicken curry with thick aromatic gravy (Full: ₹650 / Half: ₹400)',
    price: '400.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken curry', 'chicken', 'curry', 'nonveg'],
    displayOrder: 27
  },
  {
    id: 2528,
    vendorId: 25,
    categoryId: 4,
    name: 'Tawa Chicken',
    description: 'Chicken cooked on high heat tawa with dry-roast masala (Full: ₹650 / Half: ₹400)',
    price: '400.00',
    isVeg: false,
    isAvailable: true,
    tags: ['tawa chicken', 'chicken', 'nonveg'],
    displayOrder: 28
  },
  {
    id: 2529,
    vendorId: 25,
    categoryId: 4,
    name: 'Chicken Dahi Kali Mirch',
    description: 'Chicken simmered in curd and crushed black pepper gravy (Full: ₹650 / Half: ₹400)',
    price: '400.00',
    isVeg: false,
    isAvailable: true,
    tags: ['kali mirch chicken', 'chicken', 'nonveg'],
    displayOrder: 29
  },
  {
    id: 2530,
    vendorId: 25,
    categoryId: 4,
    name: 'Chicken Methi Malai',
    description: 'Rich white cream gravy with fresh fenugreek and chicken (Full: ₹650 / Half: ₹400)',
    price: '400.00',
    isVeg: false,
    isAvailable: true,
    tags: ['methi malai chicken', 'chicken', 'creamy', 'nonveg'],
    displayOrder: 30
  },
  {
    id: 2531,
    vendorId: 25,
    categoryId: 4,
    name: 'Chicken Biryani',
    description: 'Slow-cooked aromatic dum biryani with marinated tender chicken',
    price: '350.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'chicken biryani', 'chicken', 'protein', 'bestseller', 'nonveg'],
    displayOrder: 31
  },

  // ================= 🍔 EXTRAS & SANDWICHES (NON-VEG) =================
  {
    id: 2532,
    vendorId: 25,
    categoryId: 1,
    name: 'Chicken Burger',
    description: 'Crisp seasoned chicken patty burger with special sauce',
    price: '140.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken burger', 'burger', 'fast food', 'nonveg'],
    displayOrder: 32
  },
  {
    id: 2533,
    vendorId: 25,
    categoryId: 2,
    name: 'Egg Noodles',
    description: 'Wok tossed noodles scrambled with egg and veggies',
    price: '190.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg noodles', 'noodles', 'chinese', 'nonveg'],
    displayOrder: 33
  },
  {
    id: 2534,
    vendorId: 25,
    categoryId: 2,
    name: 'Chicken Noodles',
    description: 'Spicy stir-fried noodles with shredded chicken chunks',
    price: '220.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken noodles', 'noodles', 'chinese', 'nonveg'],
    displayOrder: 34
  },
  {
    id: 2535,
    vendorId: 25,
    categoryId: 4,
    name: 'Egg Fried Rice',
    description: 'Fried rice tossed with fluffy scrambled eggs and spring onions',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg fried rice', 'rice', 'chinese', 'nonveg'],
    displayOrder: 35
  },
  {
    id: 2536,
    vendorId: 25,
    categoryId: 8,
    name: 'Egg Maggi',
    description: 'Masala Maggi tossed with double scrambled eggs',
    price: '90.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg maggi', 'maggi', 'snack', 'nonveg'],
    displayOrder: 36
  },
  {
    id: 2537,
    vendorId: 25,
    categoryId: 1,
    name: 'Chicken Sandwich',
    description: 'Toasted grilled sandwich packed with seasoned shredded chicken',
    price: '120.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken sandwich', 'sandwich', 'nonveg'],
    displayOrder: 37
  },
  {
    id: 2538,
    vendorId: 25,
    categoryId: 4,
    name: 'Non-Veg Thali',
    description: 'Complete Meal: Chicken Curry + Rice + 2 Butter Roti + Salad + Raita + Pickle',
    price: '270.00',
    isVeg: false,
    isAvailable: true,
    tags: ['non veg thali', 'thali', 'combo', 'chicken', 'bestseller', 'nonveg'],
    displayOrder: 38
  },

  // ================= 🧀 VEG SPECIAL TANDOORI & CURRIES (Category 4) =================
  {
    id: 2539,
    vendorId: 25,
    categoryId: 4,
    name: 'Paneer Tikka',
    description: 'Tandoor roasted marinated cottage cheese cubes with onions & bell peppers',
    price: '290.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer tikka', 'tandoori', 'paneer', 'bestseller'],
    displayOrder: 39
  },
  {
    id: 2540,
    vendorId: 25,
    categoryId: 4,
    name: 'Paneer Malai Tikka',
    description: 'Rich cream and cashew marinated soft paneer tikka',
    price: '300.00',
    isVeg: true,
    isAvailable: true,
    tags: ['malai tikka', 'paneer', 'creamy'],
    displayOrder: 40
  },
  {
    id: 2541,
    vendorId: 25,
    categoryId: 4,
    name: 'Mix Tikka',
    description: 'Assorted platter of Paneer, Mushroom and Chaap tandoori tikkas',
    price: '330.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix tikka', 'platter', 'tandoori'],
    displayOrder: 41
  },
  {
    id: 2542,
    vendorId: 25,
    categoryId: 4,
    name: 'Mushroom Tikka',
    description: 'Whole spiced mushrooms roasted to perfection in clay oven',
    price: '290.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom tikka', 'mushroom', 'tandoori'],
    displayOrder: 42
  },
  {
    id: 2543,
    vendorId: 25,
    categoryId: 4,
    name: 'Mushroom Malai Tikka',
    description: 'Creamy grilled mushroom tikkas marinated in malai spices',
    price: '300.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom malai tikka', 'mushroom', 'creamy'],
    displayOrder: 43
  },
  {
    id: 2544,
    vendorId: 25,
    categoryId: 2,
    name: 'Paneer Chilly',
    description: 'Crispy fried cottage cheese wok-tossed with capsicum and spicy chilli sauce',
    price: '300.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilli paneer', 'paneer chilly', 'chinese', 'bestseller'],
    displayOrder: 44
  },
  {
    id: 2545,
    vendorId: 25,
    categoryId: 2,
    name: 'Mushroom Chilly',
    description: 'Crisp mushrooms tossed with sweet and spicy chilli garlic glaze',
    price: '300.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilli mushroom', 'mushroom chilly', 'chinese'],
    displayOrder: 45
  },
  {
    id: 2546,
    vendorId: 25,
    categoryId: 4,
    name: 'Shahi Paneer',
    description: 'Paneer cubes cooked in velvety rich royal cashew tomato gravy',
    price: '300.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shahi paneer', 'paneer', 'curry'],
    displayOrder: 46
  },
  {
    id: 2547,
    vendorId: 25,
    categoryId: 4,
    name: 'Kadhai Paneer',
    description: 'Paneer tossed with roasted coriander seeds, peppers and thick masala',
    price: '300.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kadhai paneer', 'paneer', 'spicy'],
    displayOrder: 47
  },
  {
    id: 2548,
    vendorId: 25,
    categoryId: 4,
    name: 'Dal Makhani',
    description: 'Slow-simmered whole black lentils with fresh cream and country butter',
    price: '230.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal makhani', 'dal', 'desi', 'bestseller'],
    displayOrder: 48
  },
  {
    id: 2549,
    vendorId: 25,
    categoryId: 4,
    name: 'Yellow Dal (Tadka)',
    description: 'Tempered yellow arhar dal with cumin, garlic and dry red chillies',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['yellow dal', 'dal tadka', 'desi'],
    displayOrder: 49
  },
  {
    id: 2550,
    vendorId: 25,
    categoryId: 4,
    name: 'Aloo Jeera',
    description: 'Dry potato cubes sauteed with roasted cumin seeds and green chillies',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo jeera', 'dry sabji'],
    displayOrder: 50
  },
  {
    id: 2551,
    vendorId: 25,
    categoryId: 4,
    name: 'Mix Veg',
    description: 'Fresh seasonal vegetables cooked in aromatic Indian spices',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix veg', 'curry'],
    displayOrder: 51
  },
  {
    id: 2552,
    vendorId: 25,
    categoryId: 2,
    name: 'Veg Manchurian',
    description: 'Vegetable dumplings tossed in savory garlic soy Manchurian sauce',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['manchurian', 'veg manchurian', 'chinese'],
    displayOrder: 52
  },

  // ================= 🌯 KATHI ROLLS VEG (Category 7) =================
  {
    id: 2553,
    vendorId: 25,
    categoryId: 7,
    name: 'Paneer Kathi Roll',
    description: 'Flaky flatbread packed with spiced cottage cheese cubes and mint sauce',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer roll', 'kathi roll', 'paneer'],
    displayOrder: 53
  },
  {
    id: 2554,
    vendorId: 25,
    categoryId: 7,
    name: 'Paneer Malai Tikka Roll',
    description: 'Crispy roll stuffed with luscious paneer malai tikka and cream dressing',
    price: '240.00',
    isVeg: true,
    isAvailable: true,
    tags: ['malai roll', 'paneer roll', 'kathi roll'],
    displayOrder: 54
  },

  // ================= 🍟 EXTRAS VEG =================
  {
    id: 2555,
    vendorId: 25,
    categoryId: 1,
    name: 'Veg Burger',
    description: 'Crispy seasoned vegetable patty burger with fresh veggies',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg burger', 'burger', 'fast food'],
    displayOrder: 55
  },
  {
    id: 2556,
    vendorId: 25,
    categoryId: 2,
    name: 'Veg Noodles',
    description: 'Stir-fried vegetable chowmein noodles with soy and vinegar',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg noodles', 'noodles', 'chinese'],
    displayOrder: 56
  },
  {
    id: 2557,
    vendorId: 25,
    categoryId: 2,
    name: 'Veg Spring Roll',
    description: 'Crispy fried rolls filled with seasoned shredded vegetables',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['spring roll', 'veg spring roll', 'chinese'],
    displayOrder: 57
  },
  {
    id: 2558,
    vendorId: 25,
    categoryId: 1,
    name: 'French Fries',
    description: 'Crispy salted golden potato fries',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['french fries', 'fries', 'crispy'],
    displayOrder: 58
  },
  {
    id: 2559,
    vendorId: 25,
    categoryId: 1,
    name: 'Veg Sandwich',
    description: 'Grilled sandwich stuffed with fresh vegetables and green chutney',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg sandwich', 'sandwich'],
    displayOrder: 59
  },
  {
    id: 2560,
    vendorId: 25,
    categoryId: 1,
    name: 'Paneer Sandwich',
    description: 'Grilled sandwich stuffed with seasoned paneer and cheese',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer sandwich', 'sandwich', 'protein'],
    displayOrder: 60
  },

  // ================= 🫓 INDIAN BREADS & PARATHAS (Category 4) =================
  {
    id: 2561,
    vendorId: 25,
    categoryId: 4,
    name: 'Tandoori Roti',
    description: 'Whole wheat tandoori flatbread',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'tandoori roti', 'under-50'],
    displayOrder: 61
  },
  {
    id: 2562,
    vendorId: 25,
    categoryId: 4,
    name: 'Butter Roti',
    description: 'Tandoori roti brushed with fresh butter',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['butter roti', 'roti', 'under-50'],
    displayOrder: 62
  },
  {
    id: 2563,
    vendorId: 25,
    categoryId: 4,
    name: 'Onion Roti',
    description: 'Tandoori roti infused with spiced chopped onions',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['onion roti', 'roti', 'under-50'],
    displayOrder: 63
  },
  {
    id: 2564,
    vendorId: 25,
    categoryId: 4,
    name: 'Ajwain Roti',
    description: 'Aromatic tandoori roti seasoned with carom seeds',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['ajwain roti', 'roti', 'under-50'],
    displayOrder: 64
  },
  {
    id: 2565,
    vendorId: 25,
    categoryId: 4,
    name: 'Mix Veg Roti',
    description: 'Tandoori flatbread stuffed with spiced mixed vegetables',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix veg roti', 'roti', 'under-50'],
    displayOrder: 65
  },
  {
    id: 2566,
    vendorId: 25,
    categoryId: 4,
    name: 'Missi Roti',
    description: 'Gram flour seasoned tandoori roti with kasuri methi',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['missi roti', 'roti', 'under-50'],
    displayOrder: 66
  },
  {
    id: 2567,
    vendorId: 25,
    categoryId: 4,
    name: 'Lachha Paratha',
    description: 'Multi-layered flaky tandoor-baked paratha',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['laccha paratha', 'paratha', 'under-50'],
    displayOrder: 67
  },
  {
    id: 2568,
    vendorId: 25,
    categoryId: 4,
    name: 'Plain Naan',
    description: 'Soft tandoor baked leavened bread',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['plain naan', 'naan', 'under-50'],
    displayOrder: 68
  },
  {
    id: 2569,
    vendorId: 25,
    categoryId: 4,
    name: 'Butter Naan',
    description: 'Soft tandoori naan brushed with rich butter',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['butter naan', 'naan', 'bestseller', 'under-50'],
    displayOrder: 69
  },
  {
    id: 2570,
    vendorId: 25,
    categoryId: 4,
    name: 'Garlic Naan',
    description: 'Tandoori naan topped with roasted minced garlic and coriander butter',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['garlic naan', 'naan', 'bestseller'],
    displayOrder: 70
  },
  {
    id: 2571,
    vendorId: 25,
    categoryId: 4,
    name: 'Aloo Paratha',
    description: 'Tandoori paratha stuffed with spiced mashed potatoes',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo paratha', 'paratha'],
    displayOrder: 71
  },
  {
    id: 2572,
    vendorId: 25,
    categoryId: 4,
    name: 'Aloo Pyaz Paratha',
    description: 'Stuffed paratha with spiced potatoes and crunchy onions',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo pyaz paratha', 'paratha'],
    displayOrder: 72
  },
  {
    id: 2573,
    vendorId: 25,
    categoryId: 4,
    name: 'Pyaz Paratha',
    description: 'Crispy paratha filled with seasoned chopped onions and chillies',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pyaz paratha', 'paratha'],
    displayOrder: 73
  },
  {
    id: 2574,
    vendorId: 25,
    categoryId: 4,
    name: 'Paneer Paratha',
    description: 'Generously stuffed paratha with grated cottage cheese and herbs',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer paratha', 'paratha', 'protein'],
    displayOrder: 74
  },

  // ================= 🥗 SIDES, SALADS & THALI (Category 4) =================
  {
    id: 2575,
    vendorId: 25,
    categoryId: 4,
    name: 'Green Salad',
    description: 'Fresh sliced cucumbers, tomatoes, carrots and onions',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['salad', 'green salad', 'healthy'],
    displayOrder: 75
  },
  {
    id: 2576,
    vendorId: 25,
    categoryId: 8,
    name: 'Peanut Masala',
    description: 'Roasted peanuts tossed with chopped onions, tomatoes, lime and chaat masala',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['peanut masala', 'snack', 'protein'],
    displayOrder: 76
  },
  {
    id: 2577,
    vendorId: 25,
    categoryId: 8,
    name: 'Channa Chat',
    description: 'Tangy and spicy boiled chickpeas salad with lemon dressing',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chana chaat', 'snack', 'healthy'],
    displayOrder: 77
  },
  {
    id: 2578,
    vendorId: 25,
    categoryId: 4,
    name: 'Channa Masala',
    description: 'Spiced chickpeas curry cooked Punjabi style',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chana masala', 'curry'],
    displayOrder: 78
  },
  {
    id: 2579,
    vendorId: 25,
    categoryId: 8,
    name: 'Papad (Roasted/Fried)',
    description: 'Crispy papad',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['papad', 'under-50'],
    displayOrder: 79
  },
  {
    id: 2580,
    vendorId: 25,
    categoryId: 8,
    name: 'Masala Papad',
    description: 'Crisp papad topped with spicy onion-tomato-coriander mix',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['masala papad', 'snack'],
    displayOrder: 80
  },
  {
    id: 2581,
    vendorId: 25,
    categoryId: 4,
    name: 'Plain Dahi',
    description: 'Fresh cooling bowl of natural curd',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dahi', 'curd', 'under-50'],
    displayOrder: 81
  },
  {
    id: 2582,
    vendorId: 25,
    categoryId: 4,
    name: 'Veg Raita',
    description: 'Chilled spiced yogurt mixed with fresh chopped vegetables',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'veg raita'],
    displayOrder: 82
  },
  {
    id: 2583,
    vendorId: 25,
    categoryId: 4,
    name: 'Veg Thali',
    description: 'Full Meal: Daal + Paneer + 2 Butter Roti + Salad + Rice + Raita + Pickle',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg thali', 'thali', 'combo', 'bestseller'],
    displayOrder: 83
  },

  // ================= 🍚 RICE & MAGGI & BEVERAGES =================
  {
    id: 2584,
    vendorId: 25,
    categoryId: 4,
    name: 'Plain Rice',
    description: 'Steamed basmati rice',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'plain rice'],
    displayOrder: 84
  },
  {
    id: 2585,
    vendorId: 25,
    categoryId: 4,
    name: 'Jeera Rice',
    description: 'Basmati rice tempered with roasted cumin seeds and butter',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['jeera rice', 'rice'],
    displayOrder: 85
  },
  {
    id: 2586,
    vendorId: 25,
    categoryId: 4,
    name: 'Veg Fried Rice',
    description: 'Wok tossed fried rice with mixed vegetables and soy sauce',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fried rice', 'rice', 'chinese'],
    displayOrder: 86
  },
  {
    id: 2587,
    vendorId: 25,
    categoryId: 8,
    name: 'Plain Maggi',
    description: 'Classic hot masala Maggi noodles',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'plain maggi', 'under-50'],
    displayOrder: 87
  },
  {
    id: 2588,
    vendorId: 25,
    categoryId: 8,
    name: 'Veg Maggi',
    description: 'Maggi noodles loaded with sweet peas, carrots and onions',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg maggi', 'maggi'],
    displayOrder: 88
  },
  {
    id: 2589,
    vendorId: 25,
    categoryId: 3,
    name: 'Cold Drink (Can/Bottle)',
    description: 'Chilled soft drink',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cold drink', 'beverage', 'under-50'],
    displayOrder: 89
  },
  {
    id: 2590,
    vendorId: 25,
    categoryId: 8,
    name: 'Hot Coffee',
    description: 'Freshly brewed hot frothy coffee',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['coffee', 'hot coffee', 'under-50'],
    displayOrder: 90
  },
  {
    id: 2591,
    vendorId: 25,
    categoryId: 3,
    name: 'Cold Coffee',
    description: 'Rich chilled creamy chocolate-dusted cold coffee shake',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cold coffee', 'shake', 'beverage', 'bestseller'],
    displayOrder: 91
  }
];
