export const KALU_FOOD_CORNER_VENDOR = {
  id: 38,
  name: 'Kalu Food Corner',
  slug: 'kalu-food-corner',
  phone: '9996039937',
  whatsapp: '9996039937',
  address: 'Near NIT Gate, Kirmach Road, Kurukshetra',
  latitude: '29.946909143245144',
  longitude: '76.82277496008699',
  opensAt: '12:00',
  closesAt: '23:30',
  deliversTo: ['NITKKR campus all', 'Gate 1', 'Gate 2', 'All Hostels'],
  image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80',
  isActive: true,
  isFeatured: true,
  displayOrder: 18,
  createdAt: new Date()
};

export const KALU_FOOD_CORNER_MENU_ITEMS = [
  // ================= 🥞 BREAKFAST (Tawa Paratha) (Category 4) =================
  {
    id: 4001,
    vendorId: 38,
    categoryId: 4,
    name: 'Sada Paratha',
    description: 'Crispy homestyle whole wheat plain tawa paratha roasted with butter or ghee',
    price: '25.00',
    isVeg: true,
    isAvailable: true,
    tags: ['sada paratha', 'plain paratha', 'tawa paratha', 'under-50'],
    displayOrder: 1
  },
  {
    id: 4002,
    vendorId: 38,
    categoryId: 4,
    name: 'Aloo Paratha',
    description: 'Hot tawa paratha stuffed with seasoned spicy mashed potatoes and fresh green herbs',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo paratha', 'breakfast', 'under-50', 'bestseller'],
    displayOrder: 2
  },
  {
    id: 4003,
    vendorId: 38,
    categoryId: 4,
    name: 'Gobhi Paratha',
    description: 'Tawa roasted paratha stuffed with grated spiced cauliflower and fresh ginger',
    price: '45.00',
    isVeg: true,
    isAvailable: true,
    tags: ['gobhi paratha', 'cauliflower', 'under-50'],
    displayOrder: 3
  },
  {
    id: 4004,
    vendorId: 38,
    categoryId: 4,
    name: 'Pyaj Paratha',
    description: 'Golden crisp paratha packed with finely chopped spiced crunchy onions and green chilies',
    price: '45.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pyaj paratha', 'onion paratha', 'under-50'],
    displayOrder: 4
  },
  {
    id: 4005,
    vendorId: 38,
    categoryId: 4,
    name: 'Paneer Pyaj Paratha',
    description: 'Stuffed paratha loaded with grated cottage cheese and crunchy seasoned onions',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer pyaj paratha', 'paneer paratha', 'bestseller'],
    displayOrder: 5
  },
  {
    id: 4006,
    vendorId: 38,
    categoryId: 4,
    name: 'Paneer Paratha',
    description: 'Generously stuffed tawa paratha with seasoned grated fresh paneer',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer paratha', 'paneer', 'bestseller'],
    displayOrder: 6
  },
  {
    id: 4007,
    vendorId: 38,
    categoryId: 4,
    name: 'Egg Paratha',
    description: 'Whole wheat paratha layered with seasoned fluffy egg omelette and herbs',
    price: '60.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg paratha', 'egg', 'non-veg', 'bestseller'],
    displayOrder: 7
  },

  // ================= 🌯 EGG & ROLL (Category 7) =================
  {
    id: 4008,
    vendorId: 38,
    categoryId: 7,
    name: 'Egg Roll',
    description: 'Crisp paratha wrap layered with egg omelette, sliced onions, and tangy sauces',
    price: '60.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg roll', 'roll', 'wrap', 'non-veg', 'bestseller'],
    displayOrder: 8
  },
  {
    id: 4009,
    vendorId: 38,
    categoryId: 7,
    name: 'Egg Bhurji',
    description: 'Fresh eggs scrambled on tawa with chopped onions, green chilies, and desi spices',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg bhurji', 'bhurji', 'egg', 'non-veg'],
    displayOrder: 9
  },
  {
    id: 4010,
    vendorId: 38,
    categoryId: 7,
    name: 'Veg Roll',
    description: 'Golden paratha rolled with seasoned shredded vegetables and tangy mint sauce',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg roll', 'roll', 'wrap', 'under-50'],
    displayOrder: 10
  },
  {
    id: 4011,
    vendorId: 38,
    categoryId: 7,
    name: 'Paneer Roll',
    description: 'Flaky paratha roll stuffed with spiced marinated cottage cheese chunks and onions',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer roll', 'roll', 'wrap', 'bestseller'],
    displayOrder: 11
  },
  {
    id: 4012,
    vendorId: 38,
    categoryId: 7,
    name: 'Omelette',
    description: 'Double egg tawa omelette spiced with green chilies, coriander, and black pepper',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['omelette', 'egg omelette', 'egg', 'non-veg'],
    displayOrder: 12
  },
  {
    id: 4013,
    vendorId: 38,
    categoryId: 7,
    name: 'Bread Omelette',
    description: 'Two slices of buttered bread enveloped inside a fluffy spiced double-egg omelette',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['bread omelette', 'egg', 'breakfast', 'non-veg', 'bestseller'],
    displayOrder: 13
  },

  // ================= 🥪 SNACKS & MAGGI (Category 1) =================
  {
    id: 4014,
    vendorId: 38,
    categoryId: 1,
    name: 'Bhel',
    description: 'Crispy puffed rice tossed with sev, chopped onions, potatoes, and sweet-spicy chutneys',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['bhel', 'chaat', 'snacks', 'under-50'],
    displayOrder: 14
  },
  {
    id: 4015,
    vendorId: 38,
    categoryId: 1,
    name: 'Poha',
    description: 'Light flattened rice tempered with mustard seeds, curry leaves, peanuts, and turmeric',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['poha', 'breakfast', 'healthy', 'under-50'],
    displayOrder: 15
  },
  {
    id: 4016,
    vendorId: 38,
    categoryId: 1,
    name: 'Plain Maggi',
    description: 'Classic comforting hot 2-minute instant noodles cooked with tastemaker',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'plain maggi', 'comfort food', 'under-50'],
    displayOrder: 16
  },
  {
    id: 4017,
    vendorId: 38,
    categoryId: 1,
    name: 'Veg Maggi',
    description: 'Hot noodles cooked with diced onions, tomatoes, green peas, and extra seasonings',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg maggi', 'maggi', 'noodles', 'bestseller'],
    displayOrder: 17
  },
  {
    id: 4018,
    vendorId: 38,
    categoryId: 1,
    name: 'Egg Maggi',
    description: 'Fresh scrambled egg tossed into steaming spicy hot Maggi noodles',
    price: '70.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg maggi', 'maggi', 'egg', 'non-veg', 'bestseller'],
    displayOrder: 18
  },
  {
    id: 4019,
    vendorId: 38,
    categoryId: 1,
    name: 'Aloo Toast',
    description: 'Crispy pan-toasted bread sandwich stuffed with spiced mashed potato masala',
    price: '25.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo toast', 'toast', 'sandwich', 'under-50'],
    displayOrder: 19
  },

  // ================= 🫓 ROTI (Category 4) =================
  {
    id: 4020,
    vendorId: 38,
    categoryId: 4,
    name: 'Plain Roti',
    description: 'Freshly made soft whole wheat tawa roti',
    price: '12.00',
    isVeg: true,
    isAvailable: true,
    tags: ['plain roti', 'roti', 'phulka', 'under-50'],
    displayOrder: 20
  },
  {
    id: 4021,
    vendorId: 38,
    categoryId: 4,
    name: 'Butter Roti',
    description: 'Warm whole wheat tawa roti generously brushed with butter',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['butter roti', 'roti', 'under-50'],
    displayOrder: 21
  },

  // ================= 🍲 SABZI & CURRIES (Category 4) =================
  {
    id: 4022,
    vendorId: 38,
    categoryId: 4,
    name: 'Chokha',
    description: 'Traditional roasted mashed eggplant and potato seasoned with mustard oil, garlic, and green chilies',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chokha', 'baingan chokha', 'desi', 'bestseller'],
    displayOrder: 22
  },
  {
    id: 4023,
    vendorId: 38,
    categoryId: 4,
    name: 'Tomato Onion Fry',
    description: 'Spiced tawa sautéed tomatoes and onions cooked with whole cumin and green chilies',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tomato onion fry', 'fry sabzi', 'spicy'],
    displayOrder: 23
  },
  {
    id: 4024,
    vendorId: 38,
    categoryId: 4,
    name: 'Kadai Paneer (Half)',
    description: 'Cubes of cottage cheese tossed with capsicum, onion, and crushed kadai spices (Half portion)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kadai paneer', 'paneer', 'curry'],
    displayOrder: 24
  },
  {
    id: 4025,
    vendorId: 38,
    categoryId: 4,
    name: 'Kadai Paneer (Full)',
    description: 'Cubes of cottage cheese tossed with capsicum, onion, and crushed kadai spices (Full portion)',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kadai paneer', 'paneer', 'bestseller'],
    displayOrder: 25
  },
  {
    id: 4026,
    vendorId: 38,
    categoryId: 4,
    name: 'Shahi Paneer (Half)',
    description: 'Soft paneer cubes simmered in a creamy, velvety mild cashew and tomato gravy (Half portion)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shahi paneer', 'paneer', 'creamy curry'],
    displayOrder: 26
  },
  {
    id: 4027,
    vendorId: 38,
    categoryId: 4,
    name: 'Shahi Paneer (Full)',
    description: 'Soft paneer cubes simmered in a creamy, velvety mild cashew and tomato gravy (Full portion)',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shahi paneer', 'paneer', 'bestseller'],
    displayOrder: 27
  },
  {
    id: 4028,
    vendorId: 38,
    categoryId: 4,
    name: 'Paneer Butter Masala (Half)',
    description: 'Rich cottage cheese cubes cooked in buttery tomato-cream sauce with aromatic spices (Half portion)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer butter masala', 'paneer', 'curry'],
    displayOrder: 28
  },
  {
    id: 4029,
    vendorId: 38,
    categoryId: 4,
    name: 'Paneer Butter Masala (Full)',
    description: 'Rich cottage cheese cubes cooked in buttery tomato-cream sauce with aromatic spices (Full portion)',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer butter masala', 'paneer', 'bestseller'],
    displayOrder: 29
  },
  {
    id: 4030,
    vendorId: 38,
    categoryId: 4,
    name: 'Paneer Do Pyaza (Half)',
    description: 'Paneer cooked with generous diced caramelized onions and whole spices (Half portion)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer do pyaza', 'paneer'],
    displayOrder: 30
  },
  {
    id: 4031,
    vendorId: 38,
    categoryId: 4,
    name: 'Paneer Do Pyaza (Full)',
    description: 'Paneer cooked with generous diced caramelized onions and whole spices (Full portion)',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer do pyaza', 'paneer'],
    displayOrder: 31
  },
  {
    id: 4032,
    vendorId: 38,
    categoryId: 4,
    name: 'Paneer Bhurji (Half)',
    description: 'Scrambled cottage cheese sautéed with finely chopped onions, tomatoes, and green chilies (Half portion)',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer bhurji', 'paneer'],
    displayOrder: 32
  },
  {
    id: 4033,
    vendorId: 38,
    categoryId: 4,
    name: 'Paneer Bhurji (Full)',
    description: 'Scrambled cottage cheese sautéed with finely chopped onions, tomatoes, and green chilies (Full portion)',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer bhurji', 'paneer', 'bestseller'],
    displayOrder: 33
  },
  {
    id: 4034,
    vendorId: 38,
    categoryId: 4,
    name: 'Mix Veg (Half)',
    description: 'Seasonal mixed garden vegetables cooked in traditional semi-dry spiced masala (Half portion)',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix veg', 'vegetables', 'curry'],
    displayOrder: 34
  },
  {
    id: 4035,
    vendorId: 38,
    categoryId: 4,
    name: 'Mix Veg (Full)',
    description: 'Seasonal mixed garden vegetables cooked in traditional semi-dry spiced masala (Full portion)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix veg', 'vegetables', 'curry'],
    displayOrder: 35
  },
  {
    id: 4036,
    vendorId: 38,
    categoryId: 4,
    name: 'Gravy (Half)',
    description: 'Aromatic seasoned Punjabi curry gravy, perfect accompaniment with parathas and rice (Half portion)',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['gravy', 'curry gravy'],
    displayOrder: 36
  },
  {
    id: 4037,
    vendorId: 38,
    categoryId: 4,
    name: 'Gravy (Full)',
    description: 'Aromatic seasoned Punjabi curry gravy, perfect accompaniment with parathas and rice (Full portion)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['gravy', 'curry gravy'],
    displayOrder: 37
  },
  {
    id: 4038,
    vendorId: 38,
    categoryId: 4,
    name: 'Aloo Jeera (Half)',
    description: 'Potatoes cooked with toasted cumin seeds, turmeric, and fresh cilantro (Half portion)',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo jeera', 'jeera aloo', 'dry sabzi'],
    displayOrder: 38
  },
  {
    id: 4039,
    vendorId: 38,
    categoryId: 4,
    name: 'Aloo Jeera (Full)',
    description: 'Potatoes cooked with toasted cumin seeds, turmeric, and fresh cilantro (Full portion)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo jeera', 'jeera aloo', 'dry sabzi'],
    displayOrder: 39
  },
  {
    id: 4040,
    vendorId: 38,
    categoryId: 4,
    name: 'Egg Curry (Half - 2 Pcs)',
    description: 'Two boiled eggs gently pan-fried and simmered in a spiced onion-tomato gravy (Half portion)',
    price: '100.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg curry', 'egg', 'curry', 'non-veg'],
    displayOrder: 40
  },
  {
    id: 4041,
    vendorId: 38,
    categoryId: 4,
    name: 'Egg Curry (Full - 4 Pcs)',
    description: 'Four boiled eggs gently pan-fried and simmered in a spiced onion-tomato gravy (Full portion)',
    price: '130.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg curry', 'egg', 'curry', 'non-veg', 'bestseller'],
    displayOrder: 41
  },

  // ================= 🫓 DESI GHEE KE PARATHA (Category 4) =================
  {
    id: 4042,
    vendorId: 38,
    categoryId: 4,
    name: 'Aloo Paratha (Desi Ghee)',
    description: 'Crispy golden whole wheat paratha stuffed with spicy potato mash, shallow fried in pure desi ghee',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['desi ghee paratha', 'aloo paratha', 'desi ghee', 'bestseller'],
    displayOrder: 42
  },
  {
    id: 4043,
    vendorId: 38,
    categoryId: 4,
    name: 'Gobhi Paratha (Desi Ghee)',
    description: 'Paratha stuffed with spiced cauliflower and cooked crisp in pure fragrant desi ghee',
    price: '65.00',
    isVeg: true,
    isAvailable: true,
    tags: ['desi ghee paratha', 'gobhi paratha', 'desi ghee'],
    displayOrder: 43
  },
  {
    id: 4044,
    vendorId: 38,
    categoryId: 4,
    name: 'Pyaj Paratha (Desi Ghee)',
    description: 'Crisp whole wheat paratha packed with spiced diced onions, prepared in pure desi ghee',
    price: '65.00',
    isVeg: true,
    isAvailable: true,
    tags: ['desi ghee paratha', 'pyaj paratha', 'desi ghee'],
    displayOrder: 44
  },
  {
    id: 4045,
    vendorId: 38,
    categoryId: 4,
    name: 'Paneer Pyaj Paratha (Desi Ghee)',
    description: 'Paratha stuffed with seasoned cottage cheese and crunchy onions, cooked in pure desi ghee',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['desi ghee paratha', 'paneer paratha', 'desi ghee', 'bestseller'],
    displayOrder: 45
  },
  {
    id: 4046,
    vendorId: 38,
    categoryId: 4,
    name: 'Mix Paratha (Desi Ghee)',
    description: 'Overloaded stuffed paratha with potatoes, paneer, cauliflower, and onions cooked in pure desi ghee',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['desi ghee paratha', 'mix paratha', 'desi ghee', 'bestseller'],
    displayOrder: 46
  },
  {
    id: 4047,
    vendorId: 38,
    categoryId: 4,
    name: 'Egg Paratha (Desi Ghee)',
    description: 'Layered paratha lined with seasoned egg omelette, cooked to golden crisp perfection in pure desi ghee',
    price: '80.00',
    isVeg: false,
    isAvailable: true,
    tags: ['desi ghee paratha', 'egg paratha', 'desi ghee', 'non-veg'],
    displayOrder: 47
  },

  // ================= 🥣 DAHI & RAITA (Category 8) =================
  {
    id: 4048,
    vendorId: 38,
    categoryId: 8,
    name: 'Dahi',
    description: 'Fresh thick chilled natural curd',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dahi', 'curd', 'fresh curd'],
    displayOrder: 48
  },
  {
    id: 4049,
    vendorId: 38,
    categoryId: 8,
    name: 'Veg Raita',
    description: 'Chilled curd blended with diced cucumber, onions, tomatoes, and roasted cumin powder',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg raita', 'raita', 'curd', 'bestseller'],
    displayOrder: 49
  },
  {
    id: 4050,
    vendorId: 38,
    categoryId: 8,
    name: 'Bundi Raita',
    description: 'Crispy fried gram-flour boondi soaked in spiced cumin and mint yogurt',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['bundi raita', 'boondi raita', 'raita'],
    displayOrder: 50
  },
  {
    id: 4051,
    vendorId: 38,
    categoryId: 8,
    name: 'Jeera Raita',
    description: 'Smooth beaten curd flavored with roasted crushed cumin seeds and black salt',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['jeera raita', 'raita'],
    displayOrder: 51
  },

  // ================= ☕ DRINKS & BEVERAGES (Category 3) =================
  {
    id: 4052,
    vendorId: 38,
    categoryId: 3,
    name: 'Tea',
    description: 'Hot aromatic freshly brewed desi chai',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tea', 'chai', 'hot drink', 'under-50'],
    displayOrder: 52
  },
  {
    id: 4053,
    vendorId: 38,
    categoryId: 3,
    name: 'Coffee',
    description: 'Rich hot frothy milk coffee',
    price: '25.00',
    isVeg: true,
    isAvailable: true,
    tags: ['coffee', 'hot coffee', 'beverage', 'under-50'],
    displayOrder: 53
  },
  {
    id: 4054,
    vendorId: 38,
    categoryId: 3,
    name: 'Mineral Water',
    description: 'Packaged drinking water (Chilled bottle)',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['water', 'mineral water', 'under-50'],
    displayOrder: 54
  },
  {
    id: 4055,
    vendorId: 38,
    categoryId: 3,
    name: 'Cold Drink',
    description: 'Assorted chilled carbonated soft drinks',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cold drink', 'soft drink', 'soda'],
    displayOrder: 55
  },
  {
    id: 4056,
    vendorId: 38,
    categoryId: 3,
    name: 'Soda',
    description: 'Chilled bubbly soda water bottle',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soda', 'beverage', 'under-50'],
    displayOrder: 56
  }
];
