export const MEHFIL_VENDOR = {
  id: 37,
  name: 'Mehfil',
  slug: 'mehfil',
  phone: '9896208561',
  whatsapp: '9896208561',
  address: 'Near NIT Kurukshetra, Kurukshetra',
  latitude: '29.947949619656924',
  longitude: '76.82321780013733',
  opensAt: '10:30',
  closesAt: '22:00',
  deliversTo: ['NITKKR Campus', 'Gate 1', 'Gate 2', 'All Hostels'],
  image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80',
  isActive: true,
  isFeatured: true,
  displayOrder: 17,
  createdAt: new Date()
};

export const MEHFIL_MENU_ITEMS = [
  // ================= 🧋 BEVERAGES (Category 3) =================
  {
    id: 3701,
    vendorId: 37,
    categoryId: 3,
    name: 'Tea',
    description: 'Freshly brewed aromatic hot desi chai',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chai', 'tea', 'beverage', 'hot drink', 'under-50'],
    displayOrder: 1
  },
  {
    id: 3702,
    vendorId: 37,
    categoryId: 3,
    name: 'Hot Coffee',
    description: 'Freshly brewed rich and frothy hot coffee',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['coffee', 'hot coffee', 'beverage', 'under-50'],
    displayOrder: 2
  },
  {
    id: 3703,
    vendorId: 37,
    categoryId: 3,
    name: 'Cold Coffee',
    description: 'Chilled creamy blended coffee with rich chocolate notes',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cold coffee', 'coffee', 'chilled', 'beverage', 'bestseller'],
    displayOrder: 3
  },
  {
    id: 3704,
    vendorId: 37,
    categoryId: 3,
    name: 'Namkeen Lassi',
    description: 'Traditional spiced and salted curd beverage churned to perfection',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lassi', 'namkeen lassi', 'curd', 'beverage'],
    displayOrder: 4
  },
  {
    id: 3705,
    vendorId: 37,
    categoryId: 3,
    name: 'Mithi Lassi',
    description: 'Sweet thick Punjabi lassi served chilled',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lassi', 'sweet lassi', 'mithi lassi', 'bestseller'],
    displayOrder: 5
  },
  {
    id: 3706,
    vendorId: 37,
    categoryId: 3,
    name: 'Fresh Lemon Water',
    description: 'Refreshing chilled water with freshly squeezed lemon and mint',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lemon water', 'refreshing', 'under-50'],
    displayOrder: 6
  },
  {
    id: 3707,
    vendorId: 37,
    categoryId: 3,
    name: 'Cold Drinks',
    description: 'Assorted chilled soft drinks (Coke, Thums Up, Sprite)',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cold drink', 'soft drink', 'soda'],
    displayOrder: 7
  },

  // ================= 🍢 TANDOORI SNACKS (Category 4) =================
  {
    id: 3708,
    vendorId: 37,
    categoryId: 4,
    name: 'Paneer Tikka',
    description: 'Cubes of cottage cheese marinated in spiced yogurt and grilled in traditional clay tandoor',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer tikka', 'tandoori', 'paneer', 'bestseller'],
    displayOrder: 8
  },
  {
    id: 3709,
    vendorId: 37,
    categoryId: 4,
    name: 'Mushroom Tikka',
    description: 'Juicy whole button mushrooms marinated in aromatic tandoori masala and chargrilled',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom tikka', 'tandoori', 'mushroom'],
    displayOrder: 9
  },
  {
    id: 3710,
    vendorId: 37,
    categoryId: 4,
    name: 'Mushroom Malai Tikka',
    description: 'Mushroom caps marinated in rich cream, cashew paste, and mild herbs',
    price: '190.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom malai tikka', 'malai tikka', 'creamy'],
    displayOrder: 10
  },
  {
    id: 3711,
    vendorId: 37,
    categoryId: 4,
    name: 'Paneer Malai Tikka',
    description: 'Soft melt-in-mouth cottage cheese marinated in rich malai, cashew paste, and cardamom',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer malai tikka', 'malai tikka', 'bestseller'],
    displayOrder: 11
  },
  {
    id: 3712,
    vendorId: 37,
    categoryId: 4,
    name: 'Paneer Achari Tikka',
    description: 'Tangy and spicy pickled paneer cubes chargrilled with mustard and whole spices',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['achari paneer', 'achari tikka', 'spicy paneer'],
    displayOrder: 12
  },
  {
    id: 3713,
    vendorId: 37,
    categoryId: 4,
    name: 'Tandoori Chaap',
    description: 'Soy chaap marinated in authentic spicy tandoori marinade and roasted over charcoal',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tandoori chaap', 'chaap', 'soya chaap', 'bestseller'],
    displayOrder: 13
  },
  {
    id: 3714,
    vendorId: 37,
    categoryId: 4,
    name: 'Afghani Chaap',
    description: 'Rich creamy soya chaap marinated in cashew paste, fresh cream, and subtle mild spices',
    price: '170.00',
    isVeg: true,
    isAvailable: true,
    tags: ['afghani chaap', 'malai chaap', 'creamy chaap'],
    displayOrder: 14
  },

  // ================= 🌯 ROLLS (Category 7) =================
  {
    id: 3715,
    vendorId: 37,
    categoryId: 7,
    name: 'Veg Kathi Roll',
    description: 'Crisp paratha wrapped with seasoned mixed vegetables, onions, and tangy mint chutney',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg roll', 'kathi roll', 'roll', 'wrap'],
    displayOrder: 15
  },
  {
    id: 3716,
    vendorId: 37,
    categoryId: 7,
    name: 'Cheese Kathi Roll',
    description: 'Warm paratha loaded with melted mozzarella, paneer, and seasoned garden veggies',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cheese roll', 'cheese kathi roll', 'bestseller'],
    displayOrder: 16
  },
  {
    id: 3717,
    vendorId: 37,
    categoryId: 7,
    name: 'Egg Kathi Roll',
    description: 'Crispy layered paratha lined with fluffy egg omelette and rolled with crunchy spiced onions',
    price: '90.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg roll', 'egg kathi roll', 'egg'],
    displayOrder: 17
  },
  {
    id: 3718,
    vendorId: 37,
    categoryId: 7,
    name: 'Chicken Kathi Roll',
    description: 'Tender spiced roasted chicken chunks wrapped in a flaky golden paratha with onions and sauces',
    price: '120.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken roll', 'chicken kathi roll', 'non-veg', 'bestseller'],
    displayOrder: 18
  },

  // ================= 🥢 CHINESE & FAST FOOD (Category 2 & 1) =================
  {
    id: 3719,
    vendorId: 37,
    categoryId: 2,
    name: 'Cheese Chilly',
    description: 'Crisp fried paneer cubes wok-tossed with capsicum, onion, green chilies, and savory soya sauce',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilli paneer', 'cheese chilly', 'indo-chinese', 'bestseller'],
    displayOrder: 19
  },
  {
    id: 3720,
    vendorId: 37,
    categoryId: 2,
    name: 'Mushroom Chilly',
    description: 'Batter-fried button mushrooms sautéed with bell peppers, garlic, and hot chili sauce',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom chilly', 'chilli mushroom', 'spicy'],
    displayOrder: 20
  },
  {
    id: 3721,
    vendorId: 37,
    categoryId: 2,
    name: 'Chilly Potato',
    description: 'Crisp potato fingers tossed in spicy chili-garlic sauce with spring onions',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilly potato', 'crispy potato', 'chinese snack'],
    displayOrder: 21
  },
  {
    id: 3722,
    vendorId: 37,
    categoryId: 2,
    name: 'Honey Chilly Potato',
    description: 'Golden crispy potato fingers glazed with sweet honey, spicy chili paste, and toasted sesame seeds',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['honey chilly potato', 'crispy', 'sweet and spicy', 'bestseller'],
    displayOrder: 22
  },
  {
    id: 3723,
    vendorId: 37,
    categoryId: 2,
    name: 'Veg Chowmein',
    description: 'Classic street-style stir fried noodles with shredded cabbage, carrots, bell peppers, and sauces',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chowmein', 'noodles', 'veg chowmein', 'bestseller'],
    displayOrder: 23
  },
  {
    id: 3724,
    vendorId: 37,
    categoryId: 2,
    name: 'Chicken Noodles',
    description: 'Wok-tossed noodles loaded with shredded tender chicken, crunchy veggies, and oriental spices',
    price: '200.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken noodles', 'chicken chowmein', 'non-veg', 'bestseller'],
    displayOrder: 24
  },
  {
    id: 3725,
    vendorId: 37,
    categoryId: 1,
    name: 'Veg Maggi',
    description: 'Classic 2-minute instant noodles cooked with finely chopped onions, tomatoes, and peas',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'veg maggi', 'comfort food'],
    displayOrder: 25
  },
  {
    id: 3726,
    vendorId: 37,
    categoryId: 1,
    name: 'Egg Maggi',
    description: 'Comforting hot Maggi noodles cooked with scrambled eggs and aromatic spices',
    price: '80.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg maggi', 'maggi', 'egg'],
    displayOrder: 26
  },
  {
    id: 3727,
    vendorId: 37,
    categoryId: 1,
    name: 'Chicken Maggi',
    description: 'Spiced hot Maggi noodles cooked with tender juicy chicken chunks',
    price: '120.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken maggi', 'maggi', 'non-veg'],
    displayOrder: 27
  },
  {
    id: 3728,
    vendorId: 37,
    categoryId: 1,
    name: 'French Fries',
    description: 'Crispy deep-fried golden potato fries tossed with salt and peri-peri seasoning',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['french fries', 'fries', 'finger food'],
    displayOrder: 28
  },
  {
    id: 3729,
    vendorId: 37,
    categoryId: 8,
    name: 'Peanut Masala',
    description: 'Crunchy roasted peanuts mixed with diced onions, green chilies, tomatoes, and tangy lemon chaat masala',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['peanut masala', 'chaat', 'chakhna', 'snacks'],
    displayOrder: 29
  },
  {
    id: 3730,
    vendorId: 37,
    categoryId: 4,
    name: 'Malai Chaap',
    description: 'Rich, luscious soy chaap roasted with cashew-cream gravy and mild spices',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['malai chaap', 'creamy chaap', 'bestseller'],
    displayOrder: 30
  },
  {
    id: 3731,
    vendorId: 37,
    categoryId: 4,
    name: 'Masala Chaap',
    description: 'Tender soy chaap chunks simmered in a spicy, thick onion-tomato Punjabi gravy',
    price: '170.00',
    isVeg: true,
    isAvailable: true,
    tags: ['masala chaap', 'spicy chaap'],
    displayOrder: 31
  },
  {
    id: 3732,
    vendorId: 37,
    categoryId: 2,
    name: 'Veg Momos (Steamed)',
    description: 'Handcrafted delicate steamed dumplings stuffed with finely minced seasoned vegetables',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['momos', 'steamed momos', 'veg momos', 'bestseller'],
    displayOrder: 32
  },
  {
    id: 3733,
    vendorId: 37,
    categoryId: 2,
    name: 'Paneer Momos (Steamed)',
    description: 'Fresh steamed dumplings stuffed with spiced cottage cheese served with fiery red chutney',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer momos', 'steamed momos', 'momos'],
    displayOrder: 33
  },
  {
    id: 3734,
    vendorId: 37,
    categoryId: 2,
    name: 'Chicken Momos (Steamed)',
    description: 'Juicy steamed momos filled with minced chicken and herbs, served with hot spicy dip',
    price: '100.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken momos', 'steamed momos', 'non-veg momos', 'bestseller'],
    displayOrder: 34
  },

  // ================= 🥗 SALAD (Category 8) =================
  {
    id: 3735,
    vendorId: 37,
    categoryId: 8,
    name: 'Green Salad',
    description: 'Fresh sliced cucumbers, carrots, tomatoes, and onions with lemon wedges',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['green salad', 'salad', 'healthy'],
    displayOrder: 35
  },
  {
    id: 3736,
    vendorId: 37,
    categoryId: 8,
    name: 'Onion Salad',
    description: 'Crisp fresh onion rings tossed with chaat masala and green chilies',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['onion salad', 'salad', 'under-50'],
    displayOrder: 36
  },
  {
    id: 3737,
    vendorId: 37,
    categoryId: 8,
    name: 'Kachumbar Salad',
    description: 'Finely diced cucumber, tomato, and onion tossed in lemon juice and black salt',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kachumbar', 'salad', 'under-50'],
    displayOrder: 37
  },
  {
    id: 3738,
    vendorId: 37,
    categoryId: 8,
    name: 'Cream Kachumbar Salad',
    description: 'Crisp diced garden vegetables dressed in thick fresh cream and mild seasonings',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cream salad', 'kachumbar', 'rich salad'],
    displayOrder: 38
  },

  // ================= 🫓 PAPAD (Category 8) =================
  {
    id: 3739,
    vendorId: 37,
    categoryId: 8,
    name: 'Dry Papad (Roasted)',
    description: 'Crispy dry-roasted lentil papad with authentic cumin and black pepper flavor',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['papad', 'roasted papad', 'under-50'],
    displayOrder: 39
  },
  {
    id: 3740,
    vendorId: 37,
    categoryId: 8,
    name: 'Fry Papad (Fried)',
    description: 'Golden fried crispy lentil papad',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['papad', 'fry papad', 'fried papad'],
    displayOrder: 40
  },
  {
    id: 3741,
    vendorId: 37,
    categoryId: 8,
    name: 'Masala Papad',
    description: 'Crispy fried papad generously topped with chopped onions, tomatoes, coriander, and chaat masala',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['masala papad', 'papad', 'spicy papad', 'bestseller'],
    displayOrder: 41
  },

  // ================= 🍲 MAIN COURSE / CURRIES (Category 4) =================
  {
    id: 3742,
    vendorId: 37,
    categoryId: 4,
    name: 'Dal Fry (Half)',
    description: 'Home-style yellow lentils tempered with ghee, cumin, garlic, and fresh green chilies (Half portion)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal fry', 'dal', 'yellow dal', 'comfort food'],
    displayOrder: 42
  },
  {
    id: 3743,
    vendorId: 37,
    categoryId: 4,
    name: 'Dal Fry (Full)',
    description: 'Home-style yellow lentils tempered with ghee, cumin, garlic, and fresh green chilies (Full portion)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal fry', 'dal', 'yellow dal', 'bestseller'],
    displayOrder: 43
  },
  {
    id: 3744,
    vendorId: 37,
    categoryId: 4,
    name: 'Dal Makhani (Half)',
    description: 'Slow-cooked creamy black lentils simmered overnight with butter and fresh cream (Half portion)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal makhani', 'dal', 'creamy dal'],
    displayOrder: 44
  },
  {
    id: 3745,
    vendorId: 37,
    categoryId: 4,
    name: 'Dal Makhani (Full)',
    description: 'Slow-cooked creamy black lentils simmered overnight with butter and fresh cream (Full portion)',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal makhani', 'dal', 'creamy dal', 'bestseller'],
    displayOrder: 45
  },
  {
    id: 3746,
    vendorId: 37,
    categoryId: 4,
    name: 'Chana Masala',
    description: 'Tender chickpeas cooked in a spicy Punjabi onion-tomato gravy with roasted whole spices',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chana masala', 'chole', 'north indian', 'punjabi'],
    displayOrder: 46
  },
  {
    id: 3747,
    vendorId: 37,
    categoryId: 4,
    name: 'Jeera Aaloo',
    description: 'Baby potatoes sautéed with cumin seeds, turmeric, and fresh coriander leaves',
    price: '130.00',
    isVeg: true,
    isAvailable: true,
    tags: ['jeera aloo', 'aloo', 'dry sabzi'],
    displayOrder: 47
  },
  {
    id: 3748,
    vendorId: 37,
    categoryId: 4,
    name: 'Dum Aaloo',
    description: 'Whole potatoes cooked in a rich, flavorful spiced yogurt-based Kashmiri gravy',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dum aloo', 'kashmiri aloo', 'gravy'],
    displayOrder: 48
  },
  {
    id: 3749,
    vendorId: 37,
    categoryId: 4,
    name: 'Shahi Paneer',
    description: 'Cottage cheese cubes bathed in a velvety royal gravy of cashews, cream, and mild saffron spices',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shahi paneer', 'paneer', 'royal gravy', 'bestseller'],
    displayOrder: 49
  },
  {
    id: 3750,
    vendorId: 37,
    categoryId: 4,
    name: 'Kadai Paneer',
    description: 'Paneer tossed with crunchy capsicum, onions, and freshly ground spicy kadai masala',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kadai paneer', 'paneer', 'spicy paneer', 'bestseller'],
    displayOrder: 50
  },
  {
    id: 3751,
    vendorId: 37,
    categoryId: 4,
    name: 'Paneer Butter Masala',
    description: 'Succulent paneer pieces cooked in a rich tomato, butter, and cream satin sauce',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer butter masala', 'pbm', 'paneer', 'bestseller'],
    displayOrder: 51
  },
  {
    id: 3752,
    vendorId: 37,
    categoryId: 4,
    name: 'Paneer Tikka Butter Masala',
    description: 'Chargrilled tandoori paneer tikka simmered in a luscious spiced butter gravy',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer tikka masala', 'tandoori paneer', 'bestseller'],
    displayOrder: 52
  },
  {
    id: 3753,
    vendorId: 37,
    categoryId: 4,
    name: 'Paneer Do Pyaza',
    description: 'Cottage cheese prepared with double the onions in a semi-dry rich onion gravy',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer do pyaza', 'paneer', 'onion gravy'],
    displayOrder: 53
  },
  {
    id: 3754,
    vendorId: 37,
    categoryId: 4,
    name: 'Paneer Bhurji',
    description: 'Scrambled paneer sautéed with finely chopped onions, tomatoes, and green chilies',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer bhurji', 'paneer', 'scrambled paneer'],
    displayOrder: 54
  },
  {
    id: 3755,
    vendorId: 37,
    categoryId: 4,
    name: 'Mutter Paneer',
    description: 'Classic combination of tender green peas and soft paneer in fragrant home-style gravy',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mutter paneer', 'matar paneer', 'curry'],
    displayOrder: 55
  },
  {
    id: 3756,
    vendorId: 37,
    categoryId: 4,
    name: 'Veg. Kofta',
    description: 'Spiced mixed vegetable dumplings simmered in a rich aromatic gravy',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg kofta', 'kofta', 'curry'],
    displayOrder: 56
  },
  {
    id: 3757,
    vendorId: 37,
    categoryId: 4,
    name: 'Malai Kofta',
    description: 'Delicate melt-in-mouth paneer and potato dumplings served in creamy sweet-savory white gravy',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['malai kofta', 'kofta', 'creamy curry', 'bestseller'],
    displayOrder: 57
  },
  {
    id: 3758,
    vendorId: 37,
    categoryId: 4,
    name: 'Veg. Chaap Gravy',
    description: 'Soy chaap marinated and cooked in a thick spiced Punjabi gravy',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chaap gravy', 'soya chaap', 'curry'],
    displayOrder: 58
  },
  {
    id: 3759,
    vendorId: 37,
    categoryId: 4,
    name: 'Kadai Chaap',
    description: 'Soy chaap stir-fried with capsicum, onion cubes, and spicy kadai whole spices',
    price: '190.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kadai chaap', 'chaap', 'spicy chaap'],
    displayOrder: 59
  },
  {
    id: 3760,
    vendorId: 37,
    categoryId: 4,
    name: 'Chaap Tikka Butter Masala',
    description: 'Smoky charcoal grilled chaap tossed in rich creamy butter masala gravy',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chaap tikka', 'butter masala', 'bestseller'],
    displayOrder: 60
  },
  {
    id: 3761,
    vendorId: 37,
    categoryId: 4,
    name: 'Mushroom Butter Masala',
    description: 'Fresh whole button mushrooms simmered in a rich tomato, butter, and cream satin sauce',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom butter masala', 'mushroom', 'curry'],
    displayOrder: 61
  },
  {
    id: 3762,
    vendorId: 37,
    categoryId: 4,
    name: 'Mushroom Do Pyaza',
    description: 'Button mushrooms cooked with plenty of caramelized onions and aromatic spices',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom do pyaza', 'mushroom'],
    displayOrder: 62
  },
  {
    id: 3763,
    vendorId: 37,
    categoryId: 4,
    name: 'Mix Veg.',
    description: 'Seasonal assortment of fresh vegetables cooked in traditional semi-dry masala',
    price: '190.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix veg', 'vegetables', 'healthy', 'curry'],
    displayOrder: 63
  },

  // ================= 🫓 ROTI & TANDOORI BREADS (Category 4) =================
  {
    id: 3764,
    vendorId: 37,
    categoryId: 4,
    name: 'Plain Roti',
    description: 'Freshly baked whole wheat flatbread baked in traditional clay tandoor',
    price: '12.00',
    isVeg: true,
    isAvailable: true,
    tags: ['plain roti', 'tandoori roti', 'roti', 'under-50'],
    displayOrder: 64
  },
  {
    id: 3765,
    vendorId: 37,
    categoryId: 4,
    name: 'Butter Roti',
    description: 'Crisp whole wheat tandoori flatbread brushed with golden desi butter',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['butter roti', 'roti', 'tandoori', 'under-50'],
    displayOrder: 65
  },
  {
    id: 3766,
    vendorId: 37,
    categoryId: 4,
    name: 'Onion Roti',
    description: 'Whole wheat roti stuffed with finely chopped spiced onions and herbs',
    price: '25.00',
    isVeg: true,
    isAvailable: true,
    tags: ['onion roti', 'roti', 'under-50'],
    displayOrder: 66
  },
  {
    id: 3767,
    vendorId: 37,
    categoryId: 4,
    name: 'Garlic Roti',
    description: 'Whole wheat flatbread infused with roasted crushed garlic and coriander',
    price: '25.00',
    isVeg: true,
    isAvailable: true,
    tags: ['garlic roti', 'roti', 'under-50'],
    displayOrder: 67
  },
  {
    id: 3768,
    vendorId: 37,
    categoryId: 4,
    name: 'Missi Roti',
    description: 'Traditional spiced gram flour (besan) and wheat flatbread roasted in clay tandoor',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['missi roti', 'besan roti', 'punjabi roti', 'under-50'],
    displayOrder: 68
  },

  // ================= 🫓 NAAN (Category 4) =================
  {
    id: 3769,
    vendorId: 37,
    categoryId: 4,
    name: 'Plain Naan',
    description: 'Soft and pillowy leavened flatbread freshly baked on tandoor walls',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['plain naan', 'naan', 'tandoori naan', 'under-50'],
    displayOrder: 69
  },
  {
    id: 3770,
    vendorId: 37,
    categoryId: 4,
    name: 'Butter Naan',
    description: 'Flaky leavened tandoor naan generously topped with melted butter',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['butter naan', 'naan', 'bestseller'],
    displayOrder: 70
  },
  {
    id: 3771,
    vendorId: 37,
    categoryId: 4,
    name: 'Aloo Naan',
    description: 'Tandoori naan stuffed with seasoned mashed potatoes and spices',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo naan', 'stuffed naan', 'naan'],
    displayOrder: 71
  },
  {
    id: 3772,
    vendorId: 37,
    categoryId: 4,
    name: 'Cheese Naan',
    description: 'Soft tandoori naan loaded with gooey melted cheese filling',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cheese naan', 'naan', 'cheese', 'bestseller'],
    displayOrder: 72
  },
  {
    id: 3773,
    vendorId: 37,
    categoryId: 4,
    name: 'Garlic Naan',
    description: 'Crisp chewy naan topped with minced garlic butter and fresh cilantro',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['garlic naan', 'naan', 'garlic', 'bestseller'],
    displayOrder: 73
  },
  {
    id: 3774,
    vendorId: 37,
    categoryId: 4,
    name: 'Onion Naan',
    description: 'Soft tandoor baked naan stuffed with spiced diced onions',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['onion naan', 'naan'],
    displayOrder: 74
  },
  {
    id: 3775,
    vendorId: 37,
    categoryId: 4,
    name: 'Stuffed Naan',
    description: 'Rich naan stuffed with mixed veggies, paneer, potatoes, and fragrant herbs',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['stuffed naan', 'mixed naan', 'bestseller'],
    displayOrder: 75
  },

  // ================= 🫓 PARANTHA (Category 4) =================
  {
    id: 3776,
    vendorId: 37,
    categoryId: 4,
    name: 'Lacha Parantha',
    description: 'Multi-layered flaky whole wheat parantha roasted golden crisp in tandoor',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lacha parantha', 'laccha paratha', 'under-50'],
    displayOrder: 76
  },
  {
    id: 3777,
    vendorId: 37,
    categoryId: 4,
    name: 'Aloo Parantha',
    description: 'Whole wheat parantha stuffed with spicy mashed potato masala',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo parantha', 'paratha', 'under-50', 'bestseller'],
    displayOrder: 77
  },
  {
    id: 3778,
    vendorId: 37,
    categoryId: 4,
    name: 'Gobhi Parantha',
    description: 'Crisp parantha generously stuffed with spiced grated cauliflower',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['gobhi parantha', 'gobi paratha'],
    displayOrder: 78
  },
  {
    id: 3779,
    vendorId: 37,
    categoryId: 4,
    name: 'Mooli Parantha',
    description: 'Traditional spiced grated radish stuffed parantha roasted crisp',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mooli parantha', 'paratha'],
    displayOrder: 79
  },
  {
    id: 3780,
    vendorId: 37,
    categoryId: 4,
    name: 'Pudina Parantha',
    description: 'Flaky layered parantha dusted with dried aromatic mint herb and spices',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pudina parantha', 'mint paratha', 'under-50'],
    displayOrder: 80
  },
  {
    id: 3781,
    vendorId: 37,
    categoryId: 4,
    name: 'Onion Parantha',
    description: 'Whole wheat parantha stuffed with chopped spiced onions and green chilies',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['onion parantha', 'paratha', 'under-50'],
    displayOrder: 81
  },
  {
    id: 3782,
    vendorId: 37,
    categoryId: 4,
    name: 'Paneer Parantha',
    description: 'Crisp golden parantha generously loaded with seasoned grated cottage cheese',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer parantha', 'paneer paratha', 'bestseller'],
    displayOrder: 82
  },
  {
    id: 3783,
    vendorId: 37,
    categoryId: 4,
    name: 'Paneer Onion Parantha',
    description: 'Stuffed parantha loaded with spiced grated paneer and crunchy onions',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer onion parantha', 'paratha'],
    displayOrder: 83
  },
  {
    id: 3784,
    vendorId: 37,
    categoryId: 4,
    name: 'Egg Parantha',
    description: 'Layered parantha filled with spiced egg omelette and herbs',
    price: '60.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg parantha', 'egg paratha', 'non-veg'],
    displayOrder: 84
  },
  {
    id: 3785,
    vendorId: 37,
    categoryId: 4,
    name: 'Stuffed Parantha',
    description: 'Overloaded mix-veggie and spiced paneer tandoori stuffed parantha',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['stuffed parantha', 'mix paratha'],
    displayOrder: 85
  },

  // ================= 🍚 RICE & BIRYANI (Category 4) =================
  {
    id: 3786,
    vendorId: 37,
    categoryId: 4,
    name: 'Plain Rice (Half)',
    description: 'Fluffy steamed aromatic basmati rice (Half portion)',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['plain rice', 'rice', 'steamed rice'],
    displayOrder: 86
  },
  {
    id: 3787,
    vendorId: 37,
    categoryId: 4,
    name: 'Plain Rice (Full)',
    description: 'Fluffy steamed aromatic basmati rice (Full portion)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['plain rice', 'rice', 'steamed rice'],
    displayOrder: 87
  },
  {
    id: 3788,
    vendorId: 37,
    categoryId: 4,
    name: 'Jeera Rice (Half)',
    description: 'Fragrant long-grain basmati rice tempered with cumin seeds and pure desi ghee (Half portion)',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['jeera rice', 'rice'],
    displayOrder: 88
  },
  {
    id: 3789,
    vendorId: 37,
    categoryId: 4,
    name: 'Jeera Rice (Full)',
    description: 'Fragrant long-grain basmati rice tempered with cumin seeds and pure desi ghee (Full portion)',
    price: '110.00',
    isVeg: true,
    isAvailable: true,
    tags: ['jeera rice', 'rice', 'bestseller'],
    displayOrder: 89
  },
  {
    id: 3790,
    vendorId: 37,
    categoryId: 4,
    name: 'Onion Rice (Half)',
    description: 'Basmati rice tossed with caramelized sliced onions and whole spices (Half portion)',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['onion rice', 'rice'],
    displayOrder: 90
  },
  {
    id: 3791,
    vendorId: 37,
    categoryId: 4,
    name: 'Onion Rice (Full)',
    description: 'Basmati rice tossed with caramelized sliced onions and whole spices (Full portion)',
    price: '110.00',
    isVeg: true,
    isAvailable: true,
    tags: ['onion rice', 'rice'],
    displayOrder: 91
  },
  {
    id: 3792,
    vendorId: 37,
    categoryId: 4,
    name: 'Veg. Fried Rice',
    description: 'Wok-tossed basmati rice with finely chopped garden vegetables and soy seasoning',
    price: '170.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg fried rice', 'fried rice', 'chinese rice'],
    displayOrder: 92
  },
  {
    id: 3793,
    vendorId: 37,
    categoryId: 4,
    name: 'Lemon Fried Rice',
    description: 'Zesty fried rice flavored with fresh squeezed lemon, curry leaves, and green chilies',
    price: '170.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lemon rice', 'fried rice', 'tangy'],
    displayOrder: 93
  },
  {
    id: 3794,
    vendorId: 37,
    categoryId: 4,
    name: 'Egg Fried Rice',
    description: 'Aromatic basmati rice stir-fried with scrambled eggs, scallions, and pepper',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg fried rice', 'fried rice', 'egg'],
    displayOrder: 94
  },
  {
    id: 3795,
    vendorId: 37,
    categoryId: 4,
    name: 'Chicken Fried Rice',
    description: 'Wok-tossed rice with shredded tender chicken pieces, veggies, and oriental sauces',
    price: '220.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken fried rice', 'chicken rice', 'non-veg', 'bestseller'],
    displayOrder: 95
  },
  {
    id: 3796,
    vendorId: 37,
    categoryId: 4,
    name: 'Veg. Pulav',
    description: 'Mildly spiced aromatic basmati rice cooked with green peas, carrots, and whole spices',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg pulav', 'pulao', 'basmati rice'],
    displayOrder: 96
  },
  {
    id: 3797,
    vendorId: 37,
    categoryId: 4,
    name: 'Veg. Biryani',
    description: 'Fragrant layered basmati rice cooked with spiced garden vegetables and saffron herbs',
    price: '170.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg biryani', 'biryani', 'bestseller'],
    displayOrder: 97
  },
  {
    id: 3798,
    vendorId: 37,
    categoryId: 4,
    name: 'Chicken Biryani',
    description: 'Authentic dum style aromatic basmati rice layered with succulent spiced bone-in chicken',
    price: '200.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken biryani', 'biryani', 'non-veg', 'bestseller'],
    displayOrder: 98
  },

  // ================= 🥣 RAITA (Category 8) =================
  {
    id: 3799,
    vendorId: 37,
    categoryId: 8,
    name: 'Mix Raita',
    description: 'Chilled spiced beaten curd blended with finely diced cucumber, onions, and tomatoes',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix raita', 'raita', 'curd'],
    displayOrder: 99
  },
  {
    id: 3800,
    vendorId: 37,
    categoryId: 8,
    name: 'Bundi Raita',
    description: 'Crispy fried chickpea flour pearls soaked in spiced roasted cumin yogurt',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['boondi raita', 'bundi raita', 'raita', 'bestseller'],
    displayOrder: 100
  },
  {
    id: 3801,
    vendorId: 37,
    categoryId: 8,
    name: 'Pudina Raita',
    description: 'Refreshing chilled curd whipped with fresh garden mint paste and black salt',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pudina raita', 'mint raita', 'raita'],
    displayOrder: 101
  },
  {
    id: 3802,
    vendorId: 37,
    categoryId: 8,
    name: 'Onion Raita',
    description: 'Crisp finely diced onions seasoned with roasted cumin and chilled thick curd',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['onion raita', 'raita'],
    displayOrder: 102
  }
];
