export const MEHFIL_VENDOR = {
  id: 37,
  name: 'Mehfil',
  slug: 'mehfil',
  phone: '9896208561',
  whatsapp: '9896208561',
  address: 'Near NIT Kurukshetra, Kurukshetra',
  latitude: '29.947210',
  longitude: '76.819450',
  opensAt: '11:00',
  closesAt: '23:00',
  deliversTo: ['NITKKR Campus', 'Gate 1', 'Gate 2', 'All Hostels'],
  image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80',
  isActive: true,
  isFeatured: true,
  displayOrder: 17,
  createdAt: new Date()
};

export const MEHFIL_MENU_ITEMS = [
  // ================= 🧋 BEVERAGES (Category 3) =================
  {
    id: 3701,
    vendorId: 37,
    categoryId: 3,
    name: 'Tea',
    description: 'Freshly brewed aromatic hot desi chai',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chai', 'tea', 'beverage', 'hot drink', 'under-50'],
    displayOrder: 1
  },
  {
    id: 3702,
    vendorId: 37,
    categoryId: 3,
    name: 'Hot Coffee',
    description: 'Freshly brewed rich and frothy hot coffee',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['coffee', 'hot coffee', 'beverage', 'under-50'],
    displayOrder: 2
  },
  {
    id: 3703,
    vendorId: 37,
    categoryId: 3,
    name: 'Cold Coffee',
    description: 'Chilled creamy blended coffee with rich chocolate notes',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cold coffee', 'coffee', 'chilled', 'beverage', 'bestseller'],
    displayOrder: 3
  },
  {
    id: 3704,
    vendorId: 37,
    categoryId: 3,
    name: 'Namkeen Lassi',
    description: 'Traditional spiced and salted curd beverage churned to perfection',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lassi', 'namkeen lassi', 'curd', 'beverage'],
    displayOrder: 4
  },
  {
    id: 3705,
    vendorId: 37,
    categoryId: 3,
    name: 'Mithi Lassi',
    description: 'Sweet thick Punjabi lassi served chilled',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lassi', 'sweet lassi', 'mithi lassi', 'bestseller'],
    displayOrder: 5
  },
  {
    id: 3706,
    vendorId: 37,
    categoryId: 3,
    name: 'Fresh Lemon Water',
    description: 'Refreshing chilled water with freshly squeezed lemon and mint',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lemon water', 'refreshing', 'under-50'],
    displayOrder: 6
  },
  {
    id: 3707,
    vendorId: 37,
    categoryId: 3,
    name: 'Cold Drinks',
    description: 'Assorted chilled soft drinks (Coke, Thums Up, Sprite)',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cold drink', 'soft drink', 'soda'],
    displayOrder: 7
  },

  // ================= 🍢 TANDOORI SNACKS (Category 4) =================
  {
    id: 3708,
    vendorId: 37,
    categoryId: 4,
    name: 'Paneer Tikka',
    description: 'Cubes of cottage cheese marinated in spiced yogurt and grilled in traditional clay tandoor',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer tikka', 'tandoori', 'paneer', 'bestseller'],
    displayOrder: 8
  },
  {
    id: 3709,
    vendorId: 37,
    categoryId: 4,
    name: 'Mushroom Tikka',
    description: 'Juicy whole button mushrooms marinated in aromatic tandoori masala and chargrilled',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom tikka', 'tandoori', 'mushroom'],
    displayOrder: 9
  },
  {
    id: 3710,
    vendorId: 37,
    categoryId: 4,
    name: 'Mushroom Malai Tikka',
    description: 'Mushroom caps marinated in rich cream, cashew paste, and mild herbs',
    price: '190.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom malai tikka', 'malai tikka', 'creamy'],
    displayOrder: 10
  },
  {
    id: 3711,
    vendorId: 37,
    categoryId: 4,
    name: 'Paneer Malai Tikka',
    description: 'Soft melt-in-mouth cottage cheese marinated in rich malai, cashew paste, and cardamom',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer malai tikka', 'malai tikka', 'bestseller'],
    displayOrder: 11
  },
  {
    id: 3712,
    vendorId: 37,
    categoryId: 4,
    name: 'Paneer Achari Tikka',
    description: 'Tangy and spicy pickled paneer cubes chargrilled with mustard and whole spices',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['achari paneer', 'achari tikka', 'spicy paneer'],
    displayOrder: 12
  },
  {
    id: 3713,
    vendorId: 37,
    categoryId: 4,
    name: 'Tandoori Chaap',
    description: 'Soy chaap marinated in authentic spicy tandoori marinade and roasted over charcoal',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tandoori chaap', 'chaap', 'soya chaap', 'bestseller'],
    displayOrder: 13
  },
  {
    id: 3714,
    vendorId: 37,
    categoryId: 4,
    name: 'Afghani Chaap',
    description: 'Rich creamy soya chaap marinated in cashew paste, fresh cream, and subtle mild spices',
    price: '170.00',
    isVeg: true,
    isAvailable: true,
    tags: ['afghani chaap', 'malai chaap', 'creamy chaap'],
    displayOrder: 14
  },

  // ================= 🌯 ROLLS (Category 7) =================
  {
    id: 3715,
    vendorId: 37,
    categoryId: 7,
    name: 'Veg Kathi Roll',
    description: 'Crisp paratha wrapped with seasoned mixed vegetables, onions, and tangy mint chutney',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['veg roll', 'kathi roll', 'roll', 'wrap'],
    displayOrder: 15
  },
  {
    id: 3716,
    vendorId: 37,
    categoryId: 7,
    name: 'Cheese Kathi Roll',
    description: 'Warm paratha loaded with melted mozzarella, paneer, and seasoned garden veggies',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cheese roll', 'cheese kathi roll', 'bestseller'],
    displayOrder: 16
  },
  {
    id: 3717,
    vendorId: 37,
    categoryId: 7,
    name: 'Egg Kathi Roll',
    description: 'Crispy layered paratha lined with fluffy egg omelette and rolled with crunchy spiced onions',
    price: '90.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg roll', 'egg kathi roll', 'egg'],
    displayOrder: 17
  },
  {
    id: 3718,
    vendorId: 37,
    categoryId: 7,
    name: 'Chicken Kathi Roll',
    description: 'Tender spiced roasted chicken chunks wrapped in a flaky golden paratha with onions and sauces',
    price: '120.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken roll', 'chicken kathi roll', 'non-veg', 'bestseller'],
    displayOrder: 18
  },

  // ================= 🥢 CHINESE & FAST FOOD (Category 2 & 1) =================
  {
    id: 3719,
    vendorId: 37,
    categoryId: 2,
    name: 'Cheese Chilly',
    description: 'Crisp fried paneer cubes wok-tossed with capsicum, onion, green chilies, and savory soya sauce',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilli paneer', 'cheese chilly', 'indo-chinese', 'bestseller'],
    displayOrder: 19
  },
  {
    id: 3720,
    vendorId: 37,
    categoryId: 2,
    name: 'Mushroom Chilly',
    description: 'Batter-fried button mushrooms sautéed with bell peppers, garlic, and hot chili sauce',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom chilly', 'chilli mushroom', 'spicy'],
    displayOrder: 20
  },
  {
    id: 3721,
    vendorId: 37,
    categoryId: 2,
    name: 'Chilly Potato',
    description: 'Crisp potato fingers tossed in spicy chili-garlic sauce with spring onions',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilly potato', 'crispy potato', 'chinese snack'],
    displayOrder: 21
  },
  {
    id: 3722,
    vendorId: 37,
    categoryId: 2,
    name: 'Honey Chilly Potato',
    description: 'Golden crispy potato fingers glazed with sweet honey, spicy chili paste, and toasted sesame seeds',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['honey chilly potato', 'crispy', 'sweet and spicy', 'bestseller'],
    displayOrder: 22
  },
  {
    id: 3723,
    vendorId: 37,
    categoryId: 2,
    name: 'Veg Chowmein',
    description: 'Classic street-style stir fried noodles with shredded cabbage, carrots, bell peppers, and sauces',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chowmein', 'noodles', 'veg chowmein', 'bestseller'],
    displayOrder: 23
  },
  {
    id: 3724,
    vendorId: 37,
    categoryId: 2,
    name: 'Chicken Noodles',
    description: 'Wok-tossed noodles loaded with shredded tender chicken, crunchy veggies, and oriental spices',
    price: '200.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken noodles', 'chicken chowmein', 'non-veg', 'bestseller'],
    displayOrder: 24
  },
  {
    id: 3725,
    vendorId: 37,
    categoryId: 1,
    name: 'Veg Maggi',
    description: 'Classic 2-minute instant noodles cooked with finely chopped onions, tomatoes, and peas',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'veg maggi', 'comfort food'],
    displayOrder: 25
  },
  {
    id: 3726,
    vendorId: 37,
    categoryId: 1,
    name: 'Egg Maggi',
    description: 'Comforting hot Maggi noodles cooked with scrambled eggs and aromatic spices',
    price: '80.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg maggi', 'maggi', 'egg'],
    displayOrder: 26
  },
  {
    id: 3727,
    vendorId: 37,
    categoryId: 1,
    name: 'Chicken Maggi',
    description: 'Spiced hot Maggi noodles cooked with tender juicy chicken chunks',
    price: '120.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken maggi', 'maggi', 'non-veg'],
    displayOrder: 27
  },
  {
    id: 3728,
    vendorId: 37,
    categoryId: 1,
    name: 'French Fries',
    description: 'Crispy deep-fried golden potato fries tossed with salt and peri-peri seasoning',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['french fries', 'fries', 'finger food'],
    displayOrder: 28
  },
  {
    id: 3729,
    vendorId: 37,
    categoryId: 8,
    name: 'Peanut Masala',
    description: 'Crunchy roasted peanuts mixed with diced onions, green chilies, tomatoes, and tangy lemon chaat masala',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['peanut masala', 'chaat', 'chakhna', 'snacks'],
    displayOrder: 29
  },
  {
    id: 3730,
    vendorId: 37,
    categoryId: 4,
    name: 'Malai Chaap',
    description: 'Rich, luscious soy chaap roasted with cashew-cream gravy and mild spices',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['malai chaap', 'creamy chaap', 'bestseller'],
    displayOrder: 30
  },
  {
    id: 3731,
    vendorId: 37,
    categoryId: 4,
    name: 'Masala Chaap',
    description: 'Tender soy chaap chunks simmered in a spicy, thick onion-tomato Punjabi gravy',
    price: '170.00',
    isVeg: true,
    isAvailable: true,
    tags: ['masala chaap', 'spicy chaap'],
    displayOrder: 31
  },
  {
    id: 3732,
    vendorId: 37,
    categoryId: 2,
    name: 'Veg Momos (Steamed)',
    description: 'Handcrafted delicate steamed dumplings stuffed with finely minced seasoned vegetables',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['momos', 'steamed momos', 'veg momos', 'bestseller'],
    displayOrder: 32
  },
  {
    id: 3733,
    vendorId: 37,
    categoryId: 2,
    name: 'Paneer Momos (Steamed)',
    description: 'Fresh steamed dumplings stuffed with spiced cottage cheese served with fiery red chutney',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer momos', 'steamed momos', 'momos'],
    displayOrder: 33
  },
  {
    id: 3734,
    vendorId: 37,
    categoryId: 2,
    name: 'Chicken Momos (Steamed)',
    description: 'Juicy steamed momos filled with minced chicken and herbs, served with hot spicy dip',
    price: '100.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken momos', 'steamed momos', 'non-veg momos', 'bestseller'],
    displayOrder: 34
  },

  // ================= 🥗 SALAD (Category 8) =================
  {
    id: 3735,
    vendorId: 37,
    categoryId: 8,
    name: 'Green Salad',
    description: 'Fresh sliced cucumbers, carrots, tomatoes, and onions with lemon wedges',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['green salad', 'salad', 'healthy'],
    displayOrder: 35
  },
  {
    id: 3736,
    vendorId: 37,
    categoryId: 8,
    name: 'Onion Salad',
    description: 'Crisp fresh onion rings tossed with chaat masala and green chilies',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['onion salad', 'salad', 'under-50'],
    displayOrder: 36
  },
  {
    id: 3737,
    vendorId: 37,
    categoryId: 8,
    name: 'Kachumbar Salad',
    description: 'Finely diced cucumber, tomato, and onion tossed in lemon juice and black salt',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kachumbar', 'salad', 'under-50'],
    displayOrder: 37
  },
  {
    id: 3738,
    vendorId: 37,
    categoryId: 8,
    name: 'Cream Kachumbar Salad',
    description: 'Crisp diced garden vegetables dressed in thick fresh cream and mild seasonings',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cream salad', 'kachumbar', 'rich salad'],
    displayOrder: 38
  },

  // ================= 🫓 PAPAD (Category 8) =================
  {
    id: 3739,
    vendorId: 37,
    categoryId: 8,
    name: 'Dry Papad (Roasted)',
    description: 'Crispy dry-roasted lentil papad with authentic cumin and black pepper flavor',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['papad', 'roasted papad', 'under-50'],
    displayOrder: 39
  },
  {
    id: 3740,
    vendorId: 37,
    categoryId: 8,
    name: 'Fry Papad (Fried)',
    description: 'Golden fried crispy lentil papad',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['papad', 'fry papad', 'fried papad'],
    displayOrder: 40
  },
  {
    id: 3741,
    vendorId: 37,
    categoryId: 8,
    name: 'Masala Papad',
    description: 'Crispy fried papad generously topped with chopped onions, tomatoes, coriander, and chaat masala',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['masala papad', 'papad', 'spicy papad', 'bestseller'],
    displayOrder: 41
  }
];
