export const PIZZA_KING_VENDOR = {
  id: 36,
  name: 'Pizza King',
  slug: 'pizza-king',
  phone: '830769374',
  whatsapp: '830769374',
  address: 'Opposite NIT Main Gate 1, Kurukshetra',
  latitude: '29.947552610875434',
  longitude: '76.82277278795115',
  opensAt: '15:00',
  closesAt: '22:30',
  deliversTo: ['Campus wide', 'Gate 1', 'All Hostels'],
  image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
  isActive: true,
  isFeatured: true,
  displayOrder: 16,
  createdAt: new Date()
};

export const PIZZA_KING_MENU_ITEMS = [
  // ================= 🍕 SINGLE TOPPING / REGULAR VEG PIZZAS =================
  {
    id: 3601,
    vendorId: 36,
    categoryId: 1,
    name: 'Onion Pizza',
    description: 'Fresh crunchy sliced onions with melted mozzarella cheese (Small: ₹60 / Medium: ₹100 / Large: ₹190)',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'onion pizza', 'veg', 'under-100', 'bestseller'],
    displayOrder: 1
  },
  {
    id: 3602,
    vendorId: 36,
    categoryId: 1,
    name: 'Capsicum Pizza',
    description: 'Crisp green bell peppers and melted mozzarella cheese on freshly baked crust (Small: ₹60 / Medium: ₹100 / Large: ₹190)',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'capsicum pizza', 'veg', 'under-100'],
    displayOrder: 2
  },
  {
    id: 3603,
    vendorId: 36,
    categoryId: 1,
    name: 'Tomato Pizza',
    description: 'Juicy red ripe tomatoes with aromatic herbs and melted cheese (Small: ₹60 / Medium: ₹100 / Large: ₹190)',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'tomato pizza', 'veg', 'under-100'],
    displayOrder: 3
  },
  {
    id: 3604,
    vendorId: 36,
    categoryId: 1,
    name: 'Corn Pizza',
    description: 'Sweet golden corn kernels layered with gooey mozzarella cheese (Small: ₹70 / Medium: ₹110 / Large: ₹210)',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'corn pizza', 'sweet corn', 'veg', 'under-100'],
    displayOrder: 4
  },

  // ================= 🧀 PANEER DOUBLE PIZZA =================
  {
    id: 3605,
    vendorId: 36,
    categoryId: 1,
    name: 'Paneer & Onion Pizza',
    description: 'Tender cottage cheese cubes and crisp onions with mozzarella (Small: ₹90 / Medium: ₹130 / Large: ₹250)',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'paneer pizza', 'paneer onion', 'veg', 'bestseller'],
    displayOrder: 5
  },
  {
    id: 3606,
    vendorId: 36,
    categoryId: 1,
    name: 'Paneer & Capsicum Pizza',
    description: 'Soft spiced paneer chunks paired with crunchy green bell peppers (Small: ₹90 / Medium: ₹130 / Large: ₹250)',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'paneer capsicum', 'paneer pizza', 'veg'],
    displayOrder: 6
  },
  {
    id: 3607,
    vendorId: 36,
    categoryId: 1,
    name: 'Paneer & Corn Pizza',
    description: 'Rich paneer cubes and sweet golden corn with melted cheese (Small: ₹100 / Medium: ₹140 / Large: ₹270)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'paneer corn', 'paneer pizza', 'sweet corn'],
    displayOrder: 7
  },
  {
    id: 3608,
    vendorId: 36,
    categoryId: 1,
    name: 'Paneer Double Pizza',
    description: 'Loaded with a double portion of fresh spiced cottage cheese and mozzarella (Small: ₹110 / Medium: ₹150 / Large: ₹290)',
    price: '110.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'double paneer', 'paneer pizza', 'bestseller'],
    displayOrder: 8
  },

  // ================= 🌿 SIMPLY VEG PIZZA =================
  {
    id: 3609,
    vendorId: 36,
    categoryId: 1,
    name: 'Double Cheese Margherita Pizza',
    description: 'Classic Italian pizza loaded with extra mozzarella cheese and herb tomato sauce (Small: ₹100 / Medium: ₹150 / Large: ₹290)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'margherita', 'cheese pizza', 'double cheese', 'bestseller'],
    displayOrder: 9
  },
  {
    id: 3610,
    vendorId: 36,
    categoryId: 1,
    name: 'Veggie Garden Pizza',
    description: 'Loaded with garden fresh onions, juicy tomatoes, and crunchy capsicum (Small: ₹100 / Medium: ₹150 / Large: ₹290)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'veggie garden', 'veg pizza'],
    displayOrder: 10
  },
  {
    id: 3611,
    vendorId: 36,
    categoryId: 1,
    name: 'Corn Olive Pizza',
    description: 'Topped with button mushrooms, black olives, and juicy sweet corn (Small: ₹100 / Medium: ₹150 / Large: ₹290)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'olive pizza', 'mushroom pizza', 'sweet corn'],
    displayOrder: 11
  },

  // ================= ⭐ PREMIUM VEG PIZZA =================
  {
    id: 3612,
    vendorId: 36,
    categoryId: 1,
    name: 'Onion Delight Pizza',
    description: 'Crispy onions, sweet corn, and diced fresh tomatoes with melted cheese (Small: ₹110 / Medium: ₹160 / Large: ₹310)',
    price: '110.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'onion delight', 'corn pizza'],
    displayOrder: 12
  },
  {
    id: 3613,
    vendorId: 36,
    categoryId: 1,
    name: 'Farm Fresh Pizza',
    description: 'Crisp capsicum, juicy tomatoes, tender mushrooms, and fresh onions (Small: ₹110 / Medium: ₹160 / Large: ₹310)',
    price: '110.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'farm fresh', 'mushroom pizza', 'bestseller'],
    displayOrder: 13
  },
  {
    id: 3614,
    vendorId: 36,
    categoryId: 1,
    name: 'Paneer Bingo Pizza',
    description: 'Crispy onions, double paneer chunks, spicy jalapenos, and sliced mushrooms (Small: ₹110 / Medium: ₹180 / Large: ₹350)',
    price: '110.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'paneer bingo', 'jalapeno', 'double paneer'],
    displayOrder: 14
  },
  {
    id: 3615,
    vendorId: 36,
    categoryId: 1,
    name: 'Grill Special Pizza',
    description: 'Loaded with onion, capsicum, paneer, sweet corn, olives, and signature cheese dip (Small: ₹120 / Medium: ₹190 / Large: ₹370)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'grill special', 'cheese dip', 'bestseller'],
    displayOrder: 15
  },

  // ================= 👑 LUXURIOUS VEG PIZZA =================
  {
    id: 3616,
    vendorId: 36,
    categoryId: 1,
    name: 'Paneer Tikka Pizza',
    description: 'Tandoori spiced paneer tikka, capsicum, tomato, and onion with mozzarella (Small: ₹120 / Medium: ₹170 / Large: ₹330)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'paneer tikka', 'tikka pizza', 'bestseller'],
    displayOrder: 16
  },
  {
    id: 3617,
    vendorId: 36,
    categoryId: 1,
    name: 'The Lord of Cheese Pizza',
    description: 'Rich cheese dip, spicy jalapeno dip, capsicum, paneer, onion, and mushrooms (Small: ₹120 / Medium: ₹180 / Large: ₹350)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'lord of cheese', 'cheese burst', 'cheesy', 'bestseller'],
    displayOrder: 17
  },
  {
    id: 3618,
    vendorId: 36,
    categoryId: 1,
    name: 'Garlic Exotica Pizza',
    description: 'Onion, capsicum, paneer, mushroom, jalapeno dip, and zesty hot & garlic sauce (Small: ₹120 / Medium: ₹180 / Large: ₹350)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'garlic exotica', 'hot garlic', 'spicy'],
    displayOrder: 18
  },

  // ================= 🍕 SPECIAL VEGGIE & CHEESY PIZZAS =================
  {
    id: 3619,
    vendorId: 36,
    categoryId: 1,
    name: 'Fresh Veggie Pizza',
    description: 'Crunchy onions and green capsicum with melted cheese (Small: ₹80 / Medium: ₹120 / Large: ₹230)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'fresh veggie', 'budget'],
    displayOrder: 19
  },
  {
    id: 3620,
    vendorId: 36,
    categoryId: 1,
    name: 'Veg Crunch Pizza',
    description: 'Golden onions and juicy ripe tomatoes with melted mozzarella (Small: ₹80 / Medium: ₹120 / Large: ₹230)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'veg crunch'],
    displayOrder: 20
  },
  {
    id: 3621,
    vendorId: 36,
    categoryId: 1,
    name: 'Veg Choice Pizza',
    description: 'Finely sliced onions and tender sweet corn with melted cheese (Small: ₹80 / Medium: ₹120 / Large: ₹230)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'veg choice', 'sweet corn'],
    displayOrder: 21
  },
  {
    id: 3622,
    vendorId: 36,
    categoryId: 1,
    name: 'Gold Corn Pizza',
    description: 'Crunchy green capsicum and sweet golden corn with rich cheese (Small: ₹80 / Medium: ₹120 / Large: ₹230)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'gold corn', 'sweet corn'],
    displayOrder: 22
  },
  {
    id: 3623,
    vendorId: 36,
    categoryId: 1,
    name: 'Olive Jalapeno Pizza',
    description: 'Zesty sliced black olives and spicy jalapenos with crunchy onions and cheese (Small: ₹100 / Medium: ₹150 / Large: ₹290)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'olive jalapeno', 'spicy'],
    displayOrder: 23
  },
  {
    id: 3624,
    vendorId: 36,
    categoryId: 1,
    name: 'Double Cheese Pizza',
    description: 'Onion, capsicum, and sweet corn topped with a generous double layer of cheese (Small: ₹100 / Medium: ₹150 / Large: ₹290)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'double cheese', 'cheesy', 'bestseller'],
    displayOrder: 24
  },
  {
    id: 3625,
    vendorId: 36,
    categoryId: 1,
    name: 'Farm House Pizza',
    description: 'Fresh onions, bell peppers, tomatoes, and spicy jalapenos on melted mozzarella (Small: ₹110 / Medium: ₹160 / Large: ₹310)',
    price: '110.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'farm house', 'classic pizza', 'bestseller'],
    displayOrder: 25
  },
  {
    id: 3626,
    vendorId: 36,
    categoryId: 1,
    name: 'Black Olive Pizza',
    description: 'Rich black olives, crispy onions, and capsicum with mozzarella cheese (Small: ₹100 / Medium: ₹140 / Large: ₹270)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'black olive', 'olive pizza'],
    displayOrder: 26
  },
  {
    id: 3627,
    vendorId: 36,
    categoryId: 1,
    name: 'Papi Paneer Pizza',
    description: 'Tender marinated paneer cubes, crunchy capsicum, and diced onions with cheese (Small: ₹110 / Medium: ₹170 / Large: ₹340)',
    price: '110.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'papi paneer', 'paneer pizza'],
    displayOrder: 27
  },
  {
    id: 3628,
    vendorId: 36,
    categoryId: 1,
    name: 'Veg Supreme Pizza',
    description: 'Loaded with onions, capsicum, tomato, sweet corn, black olives, and extra cheese (Small: ₹120 / Medium: ₹200 / Large: ₹390)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'veg supreme', 'supreme pizza', 'bestseller'],
    displayOrder: 28
  },
  {
    id: 3629,
    vendorId: 36,
    categoryId: 1,
    name: 'Pizza King Special',
    description: 'House special with capsicum, sweet corn, onion, black olives, spicy jalapenos, and extra cheese (Small: ₹120 / Medium: ₹200 / Large: ₹390)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'pizza king special', 'chef special', 'bestseller'],
    displayOrder: 29
  },
  {
    id: 3630,
    vendorId: 36,
    categoryId: 1,
    name: 'Delux Veggie Pizza',
    description: 'Assorted onion, capsicum, tomato, and golden sweet corn with melted cheese (Small: ₹100 / Medium: ₹150 / Large: ₹290)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'delux veggie', 'veg pizza'],
    displayOrder: 30
  },
  {
    id: 3631,
    vendorId: 36,
    categoryId: 1,
    name: 'Mushroom Pizza',
    description: 'Tender sautéed button mushrooms and onions with melted mozzarella (Small: ₹100 / Medium: ₹140 / Large: ₹270)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'mushroom pizza'],
    displayOrder: 31
  },
  {
    id: 3632,
    vendorId: 36,
    categoryId: 1,
    name: 'Green Olive Pizza',
    description: 'Green olives, onions, capsicum, tomato, sweet corn, and jalapeno with extra cheese (Small: ₹120 / Medium: ₹200 / Large: ₹390)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'green olive', 'spicy olive'],
    displayOrder: 32
  },
  {
    id: 3633,
    vendorId: 36,
    categoryId: 1,
    name: 'Pizza King Mix Pizza',
    description: 'The ultimate overloaded pizza: onion, capsicum, tomato, corn, mushrooms, green & black olives, jalapenos, paneer, and extra cheese (Small: ₹180 / Medium: ₹260 / Large: ₹510)',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'mix pizza', 'overloaded pizza', 'bestseller', 'special'],
    displayOrder: 33
  },
  {
    id: 3634,
    vendorId: 36,
    categoryId: 1,
    name: 'Italian Spicy Pizza',
    description: 'Onion, sweet corn, black olives, jalapenos, spicy red paprika, and melted cheese (Small: ₹120 / Medium: ₹200 / Large: ₹390)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'italian spicy', 'spicy pizza', 'red paprika'],
    displayOrder: 34
  },
  {
    id: 3635,
    vendorId: 36,
    categoryId: 1,
    name: 'Red Paprika Spicy Pizza',
    description: 'Onion, capsicum, fiery jalapenos, red paprika, red chili seasoning, and mozzarella (Small: ₹120 / Medium: ₹200 / Large: ₹390)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'red paprika', 'spicy', 'hot pizza'],
    displayOrder: 35
  }
];
