export const SURAJ_VENDOR = {
  id: 23,
  name: 'Suraj Restaurant',
  slug: 'suraj-restaurant',
  phone: '8708367874',
  whatsapp: '8950279139',
  address: 'Opp. NIT Gate, Kirmach Road, Kurukshetra',
  latitude: '29.9668',
  longitude: '76.8812',
  opensAt: '08:00',
  closesAt: '23:30',
  deliversTo: ['NIT Main Gate', 'NIT Back Gate', 'Girls Hostel'],
  image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&auto=format&fit=crop&q=80',
  isActive: true,
  isFeatured: true,
  displayOrder: 3,
  createdAt: new Date()
};

export const SURAJ_MENU_ITEMS = [
  // ================= 🍔 BURGER (Category 1 - Fast Food) =================
  {
    id: 2301,
    vendorId: 23,
    categoryId: 1,
    name: 'Veg. Burger',
    description: 'Crispy spiced vegetable patty with fresh greens and sauces',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['burger', 'veg burger', 'fast food', 'snack', 'under-50'],
    displayOrder: 1
  },
  {
    id: 2302,
    vendorId: 23,
    categoryId: 1,
    name: 'Cheese Burger',
    description: 'Grilled vegetable patty topped with melted cheese slice',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['burger', 'cheese burger', 'cheese', 'bestseller'],
    displayOrder: 2
  },
  {
    id: 2303,
    vendorId: 23,
    categoryId: 1,
    name: 'Tandoori Burger',
    description: 'Spicy grilled burger infused with smoky tandoori mayo',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['burger', 'tandoori burger', 'spicy', 'tandoori'],
    displayOrder: 3
  },
  {
    id: 2304,
    vendorId: 23,
    categoryId: 1,
    name: 'Chicken Burger',
    description: 'Crispy juicy chicken breast patty with special dressing',
    price: '140.00',
    isVeg: false,
    isAvailable: true,
    tags: ['burger', 'chicken burger', 'chicken', 'protein', 'nonveg'],
    displayOrder: 4
  },
  {
    id: 2305,
    vendorId: 23,
    categoryId: 1,
    name: 'Hot Garlic Burger',
    description: 'Spicy burger tossed in fiery hot burnt garlic chili sauce',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['burger', 'garlic burger', 'spicy'],
    displayOrder: 5
  },

  // ================= 🍢 SOYA CHAAP & TANDOORI TIKKA (Category 4 - North Indian & Snacks) =================
  {
    id: 2306,
    vendorId: 23,
    categoryId: 4,
    name: 'Tikka Chaap',
    description: 'Clay-oven roasted soya chaap marinated in spicy tandoori masala',
    price: '130.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chaap', 'tikka chaap', 'tandoori', 'protein', 'bestseller'],
    displayOrder: 6
  },
  {
    id: 2307,
    vendorId: 23,
    categoryId: 4,
    name: 'Malai Chaap',
    description: 'Tender roasted soya chaap coated in rich cream and butter',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chaap', 'malai chaap', 'creamy', 'bestseller'],
    displayOrder: 7
  },
  {
    id: 2308,
    vendorId: 23,
    categoryId: 4,
    name: 'Afghani Chaap',
    description: 'Smoky grilled soya chaap marinated in mild cashew-cream spices',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chaap', 'afghani chaap', 'mild', 'creamy'],
    displayOrder: 8
  },
  {
    id: 2309,
    vendorId: 23,
    categoryId: 4,
    name: 'Hariyali Chaap',
    description: 'Tandoori chaap marinated in fresh mint, coriander and herbs',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chaap', 'hariyali', 'mint', 'tandoori'],
    displayOrder: 9
  },
  {
    id: 2310,
    vendorId: 23,
    categoryId: 4,
    name: 'Paneer Tikka',
    description: 'Chunks of fresh paneer marinated in tandoori spices and roasted with capsicum & onion',
    price: '230.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer tikka', 'tandoori', 'protein'],
    displayOrder: 10
  },
  {
    id: 2311,
    vendorId: 23,
    categoryId: 4,
    name: 'Mushroom Tikka',
    description: 'Juicy whole mushrooms marinated in rich spices and skewered in tandoor',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom', 'mushroom tikka', 'tandoori'],
    displayOrder: 11
  },

  // ================= 🌯 ROLLS & WRAPS (Category 7 - Rolls & Wraps) =================
  {
    id: 2312,
    vendorId: 23,
    categoryId: 7,
    name: 'Veg. Roll',
    description: 'Crispy flatbread wrapped with seasoned vegetables, onions and tangy chutney',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roll', 'veg roll', 'kathi roll', 'snack'],
    displayOrder: 12
  },
  {
    id: 2313,
    vendorId: 23,
    categoryId: 7,
    name: 'Egg Roll',
    description: 'Fresh laccha paratha layered with egg omelet, onions and spiced sauces',
    price: '80.00',
    isVeg: false,
    isAvailable: true,
    tags: ['roll', 'egg roll', 'egg', 'protein', 'nonveg'],
    displayOrder: 13
  },
  {
    id: 2314,
    vendorId: 23,
    categoryId: 7,
    name: 'Chicken Roll',
    description: 'Toasted paratha loaded with spiced juicy chicken pieces and mint mayo',
    price: '150.00',
    isVeg: false,
    isAvailable: true,
    tags: ['roll', 'chicken roll', 'chicken', 'protein', 'bestseller', 'nonveg'],
    displayOrder: 14
  },
  {
    id: 2315,
    vendorId: 23,
    categoryId: 7,
    name: 'Mushroom Roll',
    description: 'Spiced tawa mushroom stir-fry rolled in crispy flaky bread',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roll', 'mushroom roll', 'roll'],
    displayOrder: 15
  },
  {
    id: 2316,
    vendorId: 23,
    categoryId: 7,
    name: 'Cheese Roll',
    description: 'Warm crispy roll generously packed with grated cheese and veggies',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roll', 'cheese roll', 'cheese'],
    displayOrder: 16
  },

  // ================= 🥣 RAITA & SALAD (Category 4 - North Indian) =================
  {
    id: 2317,
    vendorId: 23,
    categoryId: 4,
    name: 'Mix Raita',
    description: 'Chilled spiced yogurt with cucumber, tomato and roasted cumin',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'curd', 'cooling'],
    displayOrder: 17
  },
  {
    id: 2318,
    vendorId: 23,
    categoryId: 4,
    name: 'Onion Raita',
    description: 'Beaten fresh curd mixed with chopped onions and chaat masala',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'onion raita', 'under-50'],
    displayOrder: 18
  },
  {
    id: 2319,
    vendorId: 23,
    categoryId: 4,
    name: 'Kachumbar Raita',
    description: 'Refreshing curd raita with finely diced salad greens',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'kachumbar', 'under-50'],
    displayOrder: 19
  },
  {
    id: 2320,
    vendorId: 23,
    categoryId: 4,
    name: 'Bundi Raita',
    description: 'Crispy fried gram flour boondi soaked in seasoned spiced dahi',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'boondi raita'],
    displayOrder: 20
  },
  {
    id: 2321,
    vendorId: 23,
    categoryId: 4,
    name: 'Green Salad',
    description: 'Fresh sliced cucumbers, tomatoes, onions, carrots and green chillies',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['salad', 'healthy', 'green salad'],
    displayOrder: 21
  },
  {
    id: 2322,
    vendorId: 23,
    categoryId: 4,
    name: 'Onion Salad',
    description: 'Crisp onion rings with lemon wedges and chaat masala',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['salad', 'onion salad', 'under-50'],
    displayOrder: 22
  },
  {
    id: 2323,
    vendorId: 23,
    categoryId: 4,
    name: 'Kachumbar Salad',
    description: 'Diced cucumbers, tomatoes, and onions tossed with lemon & coriander',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['salad', 'kachumbar'],
    displayOrder: 23
  },

  // ================= 🫓 ROTI, NAAN & PARANTHA (Category 4 - Breads) =================
  {
    id: 2324,
    vendorId: 23,
    categoryId: 4,
    name: 'Plain Roti',
    description: 'Tandoori wheat flatbread',
    price: '12.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'tandoori roti', 'bread', 'under-50'],
    displayOrder: 24
  },
  {
    id: 2325,
    vendorId: 23,
    categoryId: 4,
    name: 'Butter Roti',
    description: 'Tandoori whole wheat roti brushed with butter',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'butter roti', 'bread', 'under-50'],
    displayOrder: 25
  },
  {
    id: 2326,
    vendorId: 23,
    categoryId: 4,
    name: 'Plain Naan',
    description: 'Soft tandoor-baked leavened flour bread',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['naan', 'bread', 'under-50'],
    displayOrder: 26
  },
  {
    id: 2327,
    vendorId: 23,
    categoryId: 4,
    name: 'Butter Naan',
    description: 'Layered soft tandoori naan brushed generously with pure butter',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['naan', 'butter naan', 'bestseller', 'under-50'],
    displayOrder: 27
  },
  {
    id: 2328,
    vendorId: 23,
    categoryId: 4,
    name: 'Missi Roti',
    description: 'Gram flour (besan) tandoori roti seasoned with fenugreek and spices',
    price: '25.00',
    isVeg: true,
    isAvailable: true,
    tags: ['missi roti', 'roti', 'under-50'],
    displayOrder: 28
  },
  {
    id: 2329,
    vendorId: 23,
    categoryId: 4,
    name: 'Laccha Parantha',
    description: 'Multi-layered flaky crispy tandoori parantha',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'laccha paratha', 'under-50'],
    displayOrder: 29
  },
  {
    id: 2330,
    vendorId: 23,
    categoryId: 4,
    name: 'Potato Onion Parantha (Aaloo Pyaaz)',
    description: 'Tandoor roasted parantha stuffed with spiced potatoes and chopped onions',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'aloo pyaz', 'under-50'],
    displayOrder: 30
  },
  {
    id: 2331,
    vendorId: 23,
    categoryId: 4,
    name: 'Paneer Onion Parantha',
    description: 'Stuffed parantha packed with seasoned paneer and onions',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'paneer pyaz', 'protein'],
    displayOrder: 31
  },
  {
    id: 2332,
    vendorId: 23,
    categoryId: 4,
    name: 'Onion Parantha (Mix)',
    description: 'Crispy parantha loaded with spiced onions and green chillies',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'onion paratha', 'under-50'],
    displayOrder: 32
  },
  {
    id: 2333,
    vendorId: 23,
    categoryId: 4,
    name: 'Paneer Parantha',
    description: 'Hearty parantha stuffed with grated pure paneer and roasted in tandoor',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'paneer paratha', 'protein', 'bestseller'],
    displayOrder: 33
  },
  {
    id: 2334,
    vendorId: 23,
    categoryId: 4,
    name: 'Gobhi Parantha',
    description: 'Delicious parantha stuffed with grated spiced cauliflower',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'gobhi paratha', 'under-50'],
    displayOrder: 34
  },
  {
    id: 2335,
    vendorId: 23,
    categoryId: 4,
    name: 'Egg Onion Parantha',
    description: 'Tandoori parantha filled with scrambled egg and spiced onions',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['parantha', 'egg paratha', 'egg', 'protein', 'under-50'],
    displayOrder: 35
  },
  {
    id: 2336,
    vendorId: 23,
    categoryId: 4,
    name: 'Egg Bhurji Onion Parantha',
    description: 'Special parantha stuffed with spicy egg bhurji and herbs',
    price: '60.00',
    isVeg: false,
    isAvailable: true,
    tags: ['parantha', 'egg bhurji', 'egg', 'protein'],
    displayOrder: 36
  },
  {
    id: 2337,
    vendorId: 23,
    categoryId: 4,
    name: 'Stuff Naan',
    description: 'Naan bread stuffed with mashed spiced potatoes and herbs',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['naan', 'stuffed naan'],
    displayOrder: 37
  },
  {
    id: 2338,
    vendorId: 23,
    categoryId: 4,
    name: 'Paneer Naan',
    description: 'Soft tandoori naan stuffed with grated seasoned cottage cheese',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['naan', 'paneer naan', 'protein'],
    displayOrder: 38
  },
  {
    id: 2339,
    vendorId: 23,
    categoryId: 4,
    name: 'Garlic Naan',
    description: 'Tandoori naan topped with roasted minced garlic and coriander butter',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['naan', 'garlic naan', 'bestseller'],
    displayOrder: 39
  },
  {
    id: 2340,
    vendorId: 23,
    categoryId: 4,
    name: 'Chicken Naan',
    description: 'Fluffy tandoori naan stuffed with minced spiced chicken',
    price: '200.00',
    isVeg: false,
    isAvailable: true,
    tags: ['naan', 'chicken naan', 'chicken', 'protein', 'nonveg'],
    displayOrder: 40
  },
  {
    id: 2341,
    vendorId: 23,
    categoryId: 4,
    name: 'Amritsari Kulcha',
    description: 'Traditional Punjabi crispy stuffed kulcha with potato, onion and pomegranate seeds',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kulcha', 'amritsari kulcha', 'under-50'],
    displayOrder: 41
  },
  {
    id: 2342,
    vendorId: 23,
    categoryId: 4,
    name: 'Ajwain Roti / Onion Roti',
    description: 'Fragrant tandoori roti seasoned with carom seeds or onions',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'ajwain roti', 'under-50'],
    displayOrder: 42
  },

  // ================= 🍚 RICE & BIRYANI (Category 4 - Rice) =================
  {
    id: 2343,
    vendorId: 23,
    categoryId: 4,
    name: 'Plain Rice',
    description: 'Steamed aromatic basmati rice',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'steamed rice'],
    displayOrder: 43
  },
  {
    id: 2344,
    vendorId: 23,
    categoryId: 4,
    name: 'Jeera Rice',
    description: 'Fragrant basmati rice tempered with roasted cumin seeds and ghee',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'jeera rice'],
    displayOrder: 44
  },
  {
    id: 2345,
    vendorId: 23,
    categoryId: 4,
    name: 'Veg. Fried Rice',
    description: 'Wok tossed basmati rice with mixed vegetables and light soy (Full: ₹150 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'fried rice', 'chinese'],
    displayOrder: 45
  },
  {
    id: 2346,
    vendorId: 23,
    categoryId: 4,
    name: 'Egg Fry Rice',
    description: 'Wok-tossed fried rice scrambled with farm fresh eggs (Full: ₹180 / Half: ₹130)',
    price: '130.00',
    isVeg: false,
    isAvailable: true,
    tags: ['rice', 'egg fried rice', 'egg', 'protein', 'nonveg'],
    displayOrder: 46
  },
  {
    id: 2347,
    vendorId: 23,
    categoryId: 4,
    name: 'Chicken Fry Rice',
    description: 'Delicious fried rice with shredded chicken pieces and spices (Full: ₹200 / Half: ₹140)',
    price: '140.00',
    isVeg: false,
    isAvailable: true,
    tags: ['rice', 'chicken fried rice', 'chicken', 'protein', 'nonveg'],
    displayOrder: 47
  },
  {
    id: 2348,
    vendorId: 23,
    categoryId: 4,
    name: 'Veg. Singapuri Rice',
    description: 'Spicy fried rice tossed with curry powder, capsicum and veggies',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'singapuri rice', 'spicy'],
    displayOrder: 48
  },
  {
    id: 2349,
    vendorId: 23,
    categoryId: 4,
    name: 'Veg. Chilly Garlic Rice',
    description: 'Flavored spicy rice stir-fried with burnt garlic and red chilli sauce',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'garlic rice', 'spicy'],
    displayOrder: 49
  },
  {
    id: 2350,
    vendorId: 23,
    categoryId: 4,
    name: 'Mix Pulao',
    description: 'Basmati rice cooked with fresh seasonal vegetables and whole spices (Full: ₹160 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'pulao'],
    displayOrder: 50
  },
  {
    id: 2351,
    vendorId: 23,
    categoryId: 4,
    name: 'Veg. Biryani',
    description: 'Layered spiced dum biryani with assorted veggies and aromatic herbs (Full: ₹160 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['biryani', 'veg biryani', 'dum biryani'],
    displayOrder: 51
  },
  {
    id: 2352,
    vendorId: 23,
    categoryId: 4,
    name: 'Chicken Biryani',
    description: 'Slow-cooked flavorful dum biryani with tender marinated chicken pieces (Full: ₹200 / Half: ₹140)',
    price: '140.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'chicken biryani', 'chicken', 'protein', 'bestseller', 'nonveg'],
    displayOrder: 52
  },
  {
    id: 2353,
    vendorId: 23,
    categoryId: 4,
    name: 'Cheese Biryani',
    description: 'Rich spiced biryani loaded with soft cottage cheese cubes (Full: ₹180 / Half: ₹140)',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['biryani', 'cheese biryani', 'paneer'],
    displayOrder: 53
  },
  {
    id: 2354,
    vendorId: 23,
    categoryId: 4,
    name: 'Egg Biryani',
    description: 'Basmati biryani rice layered with fried boiled eggs and spices (Full: ₹180 / Half: ₹130)',
    price: '130.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'egg biryani', 'egg', 'protein', 'nonveg'],
    displayOrder: 54
  },

  // ================= 🍲 INDIAN KHANA VEG (Category 4 - North Indian Curries) =================
  {
    id: 2355,
    vendorId: 23,
    categoryId: 4,
    name: 'Dal Makhani',
    description: 'Slow-simmered black lentils with butter and rich cream (Full: ₹120 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal', 'dal makhani', 'desi', 'bestseller'],
    displayOrder: 55
  },
  {
    id: 2356,
    vendorId: 23,
    categoryId: 4,
    name: 'Dal Fry',
    description: 'Yellow lentils tempered with cumin, garlic, onions and tomatoes (Full: ₹120 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal', 'dal fry', 'desi'],
    displayOrder: 56
  },
  {
    id: 2357,
    vendorId: 23,
    categoryId: 4,
    name: 'Dal Handi',
    description: 'Rich spiced lentils slow cooked in traditional earthen handi (Full: ₹120 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal', 'dal handi'],
    displayOrder: 57
  },
  {
    id: 2358,
    vendorId: 23,
    categoryId: 4,
    name: 'Dal Tadka',
    description: 'Aromatic yellow dal with ghee, red chilies, garlic and hing tadka (Full: ₹120 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal', 'dal tadka', 'desi'],
    displayOrder: 58
  },
  {
    id: 2359,
    vendorId: 23,
    categoryId: 4,
    name: 'Shahi Paneer',
    description: 'Cottage cheese cubes in a silky, creamy tomato and cashew gravy (Full: ₹180 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'shahi paneer', 'protein', 'bestseller'],
    displayOrder: 59
  },
  {
    id: 2360,
    vendorId: 23,
    categoryId: 4,
    name: 'Kadhai Paneer',
    description: 'Paneer tossed with bell peppers, onions and freshly ground kadhai masala (Full: ₹220 / Half: ₹140)',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'kadai paneer', 'protein', 'spicy'],
    displayOrder: 60
  },
  {
    id: 2361,
    vendorId: 23,
    categoryId: 4,
    name: 'Paneer Butter Masala',
    description: 'Rich, mildly sweet and creamy tomato butter gravy with paneer cubes (Full: ₹220 / Half: ₹140)',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer butter masala', 'protein', 'bestseller'],
    displayOrder: 61
  },
  {
    id: 2362,
    vendorId: 23,
    categoryId: 4,
    name: 'Cheese Tomato',
    description: 'Creamy and tangy North Indian tomato gravy loaded with cottage cheese (Full: ₹180 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'cheese tomato', 'tangy'],
    displayOrder: 62
  },
  {
    id: 2363,
    vendorId: 23,
    categoryId: 4,
    name: 'Dhania Adrak Ki Paneer',
    description: 'Specialty paneer cooked in a rich ginger-coriander spiced gravy (Full: ₹200 / Half: ₹140)',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'dhania adrak', 'special'],
    displayOrder: 63
  },
  {
    id: 2364,
    vendorId: 23,
    categoryId: 4,
    name: 'Paneer Methi Malai',
    description: 'Creamy gravy infused with fresh fenugreek leaves and soft paneer (Full: ₹180 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'methi malai', 'creamy'],
    displayOrder: 64
  },
  {
    id: 2365,
    vendorId: 23,
    categoryId: 4,
    name: 'Matar Methi Malai',
    description: 'Sweet green peas and fenugreek simmered in a luscious white gravy (Full: ₹180 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['matar', 'methi malai', 'creamy'],
    displayOrder: 65
  },
  {
    id: 2366,
    vendorId: 23,
    categoryId: 4,
    name: 'Malai Kofta',
    description: 'Deep-fried cottage cheese & potato dumplings in a velvety cashew cream sauce',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kofta', 'malai kofta', 'rich'],
    displayOrder: 66
  },
  {
    id: 2367,
    vendorId: 23,
    categoryId: 4,
    name: 'Dum Aaloo',
    description: 'Baby potatoes cooked in a spiced and flavorful Kashmiri style gravy (Full: ₹120 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dum aloo', 'aloo', 'desi'],
    displayOrder: 67
  },
  {
    id: 2368,
    vendorId: 23,
    categoryId: 4,
    name: 'Mix Veg.',
    description: 'Assorted seasonal vegetables cooked in traditional Indian masala (Full: ₹150 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix veg', 'vegetables', 'healthy'],
    displayOrder: 68
  },
  {
    id: 2369,
    vendorId: 23,
    categoryId: 4,
    name: 'Chana Masala',
    description: 'Chickpeas cooked with onions, tomatoes and aromatic Punjabi spices (Full: ₹150 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chana masala', 'chole', 'protein'],
    displayOrder: 69
  },
  {
    id: 2370,
    vendorId: 23,
    categoryId: 4,
    name: 'Jeera Aaloo',
    description: 'Dry potato cubes tossed with roasted cumin seeds and turmeric (Full: ₹130 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['jeera aloo', 'dry veg'],
    displayOrder: 70
  },
  {
    id: 2371,
    vendorId: 23,
    categoryId: 4,
    name: 'Aaloo Chokha',
    description: 'Desi mashed potato preparation with mustard oil, green chillies and onions',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aloo chokha', 'desi'],
    displayOrder: 71
  },
  {
    id: 2372,
    vendorId: 23,
    categoryId: 4,
    name: 'Paneer Bhurji',
    description: 'Scrambled cottage cheese cooked with onions, tomatoes and butter (Full: ₹190 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer bhurji', 'protein'],
    displayOrder: 72
  },
  {
    id: 2373,
    vendorId: 23,
    categoryId: 4,
    name: 'Paneer Do Pyaza',
    description: 'Paneer cubes in a savory onion gravy with double onion layers (Full: ₹200 / Half: ₹140)',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer do pyaza', 'protein'],
    displayOrder: 73
  },
  {
    id: 2374,
    vendorId: 23,
    categoryId: 4,
    name: 'Mushroom Kadhai',
    description: 'Fresh mushrooms stir-fried with capsicum, onion and kadhai spices (Full: ₹200 / Half: ₹140)',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom', 'mushroom kadai'],
    displayOrder: 74
  },
  {
    id: 2375,
    vendorId: 23,
    categoryId: 4,
    name: 'Paneer Pasanda',
    description: 'Stuffed paneer sandwiches cooked in a luscious rich creamy gravy',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer pasanda', 'royal'],
    displayOrder: 75
  },
  {
    id: 2376,
    vendorId: 23,
    categoryId: 4,
    name: 'Matar Mushroom',
    description: 'Fresh mushrooms and sweet green peas in a spiced onion-tomato curry (Full: ₹180 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom', 'matar mushroom'],
    displayOrder: 76
  },
  {
    id: 2377,
    vendorId: 23,
    categoryId: 4,
    name: 'Matar Mushroom Methi Malai',
    description: 'Mushroom and green peas cooked in fenugreek cream gravy (Full: ₹180 / Half: ₹120)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom', 'methi malai'],
    displayOrder: 77
  },
  {
    id: 2378,
    vendorId: 23,
    categoryId: 4,
    name: 'Veg. Gravy',
    description: 'Smooth spiced mixed vegetable base curry (Full: ₹120 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['gravy', 'curry'],
    displayOrder: 78
  },
  {
    id: 2379,
    vendorId: 23,
    categoryId: 4,
    name: 'Matar Paneer',
    description: 'Classic cottage cheese and green peas curry cooked in home-style spices (Full: ₹210 / Half: ₹140)',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'matar paneer', 'protein'],
    displayOrder: 79
  },
  {
    id: 2380,
    vendorId: 23,
    categoryId: 4,
    name: 'Gravy Chaap',
    description: 'Soya chaap cooked in thick, rich and spicy Punjabi masala gravy',
    price: '190.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chaap', 'gravy chaap', 'protein', 'bestseller'],
    displayOrder: 80
  },

  // ================= 🍗 INDIAN NON-VEG (Category 4 - Non-Veg Specialties) =================
  {
    id: 2381,
    vendorId: 23,
    categoryId: 4,
    name: 'Egg Bhurji (2 Eggs)',
    description: 'Spicy scrambled eggs with chopped onions, green chillies and coriander',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg', 'egg bhurji', 'protein', 'under-50', 'nonveg'],
    displayOrder: 81
  },
  {
    id: 2382,
    vendorId: 23,
    categoryId: 4,
    name: 'Egg Omelet (2 Eggs)',
    description: 'Fluffy pan-fried spiced omelet with onions and toast/bread',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg', 'omelet', 'protein', 'under-50', 'nonveg'],
    displayOrder: 82
  },
  {
    id: 2383,
    vendorId: 23,
    categoryId: 4,
    name: 'Butter Chicken',
    description: 'Tender tandoori chicken cooked in rich buttery makhani gravy (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'butter chicken', 'protein', 'bestseller', 'nonveg'],
    displayOrder: 83
  },
  {
    id: 2384,
    vendorId: 23,
    categoryId: 4,
    name: 'Kadhai Chicken',
    description: 'Chicken tossed with bell peppers and freshly ground kadhai spices (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'kadai chicken', 'protein', 'spicy', 'nonveg'],
    displayOrder: 84
  },
  {
    id: 2385,
    vendorId: 23,
    categoryId: 4,
    name: 'Tawa Chicken',
    description: 'Spicy chicken cooked on high heat on iron tawa with roast masala (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'tawa chicken', 'protein', 'nonveg'],
    displayOrder: 85
  },
  {
    id: 2386,
    vendorId: 23,
    categoryId: 4,
    name: 'Masala Chicken',
    description: 'Home-style robust chicken curry with whole aromatic spices (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken masala', 'protein', 'nonveg'],
    displayOrder: 86
  },
  {
    id: 2387,
    vendorId: 23,
    categoryId: 4,
    name: 'Kali Mirch Chicken',
    description: 'Chicken cooked in rich black pepper and cashew cream sauce (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'kali mirch', 'protein', 'nonveg'],
    displayOrder: 87
  },
  {
    id: 2388,
    vendorId: 23,
    categoryId: 4,
    name: 'Lemon Chicken',
    description: 'Zesty and tangy chicken tossed with lemon juice and mild spices (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'lemon chicken', 'protein', 'nonveg'],
    displayOrder: 88
  },
  {
    id: 2389,
    vendorId: 23,
    categoryId: 4,
    name: 'Tandoori Chicken',
    description: 'Whole chicken pieces marinated in yogurt and tandoori spices, char-grilled in clay oven (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'tandoori chicken', 'protein', 'bestseller', 'nonveg'],
    displayOrder: 89
  },
  {
    id: 2390,
    vendorId: 23,
    categoryId: 4,
    name: 'Afghani Chicken',
    description: 'Smoky tandoori chicken coated in rich cream and mild cashew marinade (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'afghani chicken', 'protein', 'nonveg'],
    displayOrder: 90
  },
  {
    id: 2391,
    vendorId: 23,
    categoryId: 4,
    name: 'Hariyali Chicken',
    description: 'Tandoor-grilled chicken marinated in mint, cilantro and green chillies (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'hariyali chicken', 'protein', 'nonveg'],
    displayOrder: 91
  },
  {
    id: 2392,
    vendorId: 23,
    categoryId: 4,
    name: 'Chicken Tikka',
    description: 'Boneless tender chicken chunks skewered and roasted in clay oven (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken tikka', 'protein', 'nonveg'],
    displayOrder: 92
  },
  {
    id: 2393,
    vendorId: 23,
    categoryId: 4,
    name: 'Chicken Malai Tikka',
    description: 'Melt-in-mouth boneless chicken tikka in cheese and cream marinade (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'malai tikka', 'protein', 'nonveg'],
    displayOrder: 93
  },
  {
    id: 2394,
    vendorId: 23,
    categoryId: 4,
    name: 'Chicken Pakoda',
    description: 'Crispy fried chicken fritters seasoned with Punjabi chaat masala (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken pakoda', 'snack', 'nonveg'],
    displayOrder: 94
  },
  {
    id: 2395,
    vendorId: 23,
    categoryId: 4,
    name: 'Crispy Chicken',
    description: 'Deep-fried golden crunchy chicken bites tossed with spices (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'crispy chicken', 'nonveg'],
    displayOrder: 95
  },
  {
    id: 2396,
    vendorId: 23,
    categoryId: 4,
    name: 'Fried Chicken',
    description: 'Hot crispy seasoned fried chicken pieces (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'fried chicken', 'nonveg'],
    displayOrder: 96
  },
  {
    id: 2397,
    vendorId: 23,
    categoryId: 4,
    name: 'Hyderabadi Chicken',
    description: 'Rich spiced chicken curry flavored with coconut, curry leaves and chillies (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'hyderabadi chicken', 'spicy', 'nonveg'],
    displayOrder: 97
  },
  {
    id: 2398,
    vendorId: 23,
    categoryId: 4,
    name: 'Punjabi Chicken',
    description: 'Traditional Dhaba style thick chicken curry cooked with rustic spices (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'punjabi chicken', 'bestseller', 'nonveg'],
    displayOrder: 98
  },
  {
    id: 2399,
    vendorId: 23,
    categoryId: 4,
    name: 'Chilly Chicken (Gravy/Dry)',
    description: 'Indo-Chinese style chicken tossed with bell peppers and green chillies (Full: ₹300 / Half: ₹180 / 1Kg: ₹550)',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chilli chicken', 'chinese', 'nonveg'],
    displayOrder: 99
  },
  {
    id: 2400,
    vendorId: 23,
    categoryId: 4,
    name: 'Egg Curry (2 Eggs)',
    description: 'Boiled eggs cooked in seasoned spicy tomato-onion curry gravy',
    price: '130.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg', 'egg curry', 'protein', 'nonveg'],
    displayOrder: 100
  },
  {
    id: 2401,
    vendorId: 23,
    categoryId: 4,
    name: 'Egg Curry (4 Eggs)',
    description: 'Double portion egg curry with 4 boiled eggs in rich spiced gravy',
    price: '180.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg', 'egg curry', 'protein', 'nonveg'],
    displayOrder: 101
  },

  // ================= 👨‍🍳 ONLY MAKING (Custom Preparation for Hostels) =================
  {
    id: 2402,
    vendorId: 23,
    categoryId: 4,
    name: 'Only Making - 500 gm Paneer',
    description: 'Custom dhaba style curry preparation with student-provided 500g paneer',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['custom making', 'paneer'],
    displayOrder: 102
  },
  {
    id: 2403,
    vendorId: 23,
    categoryId: 4,
    name: 'Only Making - 1 Kg Paneer',
    description: 'Custom dhaba style curry preparation with student-provided 1Kg paneer',
    price: '250.00',
    isVeg: true,
    isAvailable: true,
    tags: ['custom making', 'paneer'],
    displayOrder: 103
  },
  {
    id: 2404,
    vendorId: 23,
    categoryId: 4,
    name: 'Only Making - 500 gm Chicken',
    description: 'Custom dhaba style curry preparation with student-provided 500g chicken',
    price: '130.00',
    isVeg: false,
    isAvailable: true,
    tags: ['custom making', 'chicken', 'nonveg'],
    displayOrder: 104
  },
  {
    id: 2405,
    vendorId: 23,
    categoryId: 4,
    name: 'Only Making - 1 Kg Chicken',
    description: 'Custom dhaba style curry preparation with student-provided 1Kg chicken',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['custom making', 'chicken', 'nonveg'],
    displayOrder: 105
  },
  {
    id: 2406,
    vendorId: 23,
    categoryId: 4,
    name: 'Only Making - 500 gm Mutton',
    description: 'Custom slow-simmered desi curry preparation with student-provided 500g mutton',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['custom making', 'mutton', 'nonveg'],
    displayOrder: 106
  },
  {
    id: 2407,
    vendorId: 23,
    categoryId: 4,
    name: 'Only Making - 1 Kg Mutton',
    description: 'Custom slow-simmered desi curry preparation with student-provided 1Kg mutton',
    price: '350.00',
    isVeg: false,
    isAvailable: true,
    tags: ['custom making', 'mutton', 'nonveg'],
    displayOrder: 107
  },

  // ================= 🥢 CHINESE ITEMS & MOMOS (Category 2 - Chinese & Momos) =================
  {
    id: 2408,
    vendorId: 23,
    categoryId: 2,
    name: 'Egg Chowmein',
    description: 'Wok tossed noodles scrambled with egg and crunchy veggies (Full: ₹150 / Half: ₹100)',
    price: '100.00',
    isVeg: false,
    isAvailable: true,
    tags: ['noodles', 'egg chowmein', 'egg', 'chinese', 'nonveg'],
    displayOrder: 108
  },
  {
    id: 2409,
    vendorId: 23,
    categoryId: 2,
    name: 'Chicken Chowmein',
    description: 'Spicy tossed noodles with tender chicken shreds (Full: ₹200 / Half: ₹140)',
    price: '140.00',
    isVeg: false,
    isAvailable: true,
    tags: ['noodles', 'chicken chowmein', 'chicken', 'chinese', 'nonveg'],
    displayOrder: 109
  },
  {
    id: 2410,
    vendorId: 23,
    categoryId: 2,
    name: 'Veg. Noodles',
    description: 'Classic wok-tossed vegetable chowmein (Full: ₹100 / Half: ₹70)',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['noodles', 'veg noodles', 'chinese'],
    displayOrder: 110
  },
  {
    id: 2411,
    vendorId: 23,
    categoryId: 2,
    name: 'Cheese Noodles',
    description: 'Spicy stir-fried noodles loaded with grated cheese (Full: ₹160 / Half: ₹110)',
    price: '110.00',
    isVeg: true,
    isAvailable: true,
    tags: ['noodles', 'cheese noodles', 'chinese'],
    displayOrder: 111
  },
  {
    id: 2412,
    vendorId: 23,
    categoryId: 2,
    name: 'Hakka Noodles',
    description: 'Traditional Hakka style noodles tossed with soy, vinegar and crisp vegetables (Full: ₹160 / Half: ₹110)',
    price: '110.00',
    isVeg: true,
    isAvailable: true,
    tags: ['noodles', 'hakka noodles', 'chinese'],
    displayOrder: 112
  },
  {
    id: 2413,
    vendorId: 23,
    categoryId: 2,
    name: 'Singapuri Noodles',
    description: 'Spicy thin noodles tossed in sweet & spicy curry flavored sauce (Full: ₹130 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['noodles', 'singapuri', 'spicy'],
    displayOrder: 113
  },
  {
    id: 2414,
    vendorId: 23,
    categoryId: 2,
    name: 'Chilly Garlic Noodles',
    description: 'Fiery noodles stir-fried with burnt garlic and spicy chilli sauce (Full: ₹130 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['noodles', 'chilli garlic', 'spicy', 'garlic'],
    displayOrder: 114
  },
  {
    id: 2415,
    vendorId: 23,
    categoryId: 2,
    name: 'Chicken Noodles',
    description: 'Wok tossed noodles with juicy chicken chunks and seasonings (Full: ₹200 / Half: ₹140)',
    price: '140.00',
    isVeg: false,
    isAvailable: true,
    tags: ['noodles', 'chicken noodles', 'chicken', 'nonveg'],
    displayOrder: 115
  },
  {
    id: 2416,
    vendorId: 23,
    categoryId: 2,
    name: 'Veg. Manchurian Gravy',
    description: 'Crispy fried vegetable balls in a rich sweet & tangy soy garlic gravy (Full: ₹150 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['manchurian', 'veg manchurian', 'gravy', 'chinese'],
    displayOrder: 116
  },
  {
    id: 2417,
    vendorId: 23,
    categoryId: 2,
    name: 'Veg. Manchurian Dry',
    description: 'Crispy vegetable dumplings tossed dry with garlic, chillies and spring onions (Full: ₹150 / Half: ₹100)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['manchurian', 'veg manchurian', 'dry', 'starter'],
    displayOrder: 117
  },
  {
    id: 2418,
    vendorId: 23,
    categoryId: 2,
    name: 'Cheese Manchurian Gravy',
    description: 'Paneer Manchurian balls in rich savory Indo-Chinese sauce (Full: ₹200 / Half: ₹150)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['manchurian', 'cheese manchurian', 'paneer'],
    displayOrder: 118
  },
  {
    id: 2419,
    vendorId: 23,
    categoryId: 2,
    name: 'Cheese Manchurian Dry',
    description: 'Crispy paneer balls tossed dry with capsicum, onion and spices (Full: ₹200 / Half: ₹150)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['manchurian', 'cheese manchurian', 'dry'],
    displayOrder: 119
  },
  {
    id: 2420,
    vendorId: 23,
    categoryId: 2,
    name: 'Chicken Manchurian Gravy',
    description: 'Chicken meatballs cooked in flavorful Chinese gravy (Full: ₹550 / Half: ₹300)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['manchurian', 'chicken manchurian', 'chicken', 'nonveg'],
    displayOrder: 120
  },
  {
    id: 2421,
    vendorId: 23,
    categoryId: 2,
    name: 'Chicken Manchurian Dry',
    description: 'Crispy chicken balls tossed dry with garlic, ginger and green chillies (Full: ₹550 / Half: ₹300)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['manchurian', 'chicken manchurian', 'dry', 'nonveg'],
    displayOrder: 121
  },
  {
    id: 2422,
    vendorId: 23,
    categoryId: 2,
    name: 'Cheese Chilly Gravy (Chilli Paneer)',
    description: 'Fried cottage cheese cubes tossed in spicy chilli soya gravy (Full: ₹230 / Half: ₹140)',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilli paneer', 'cheese chilly', 'bestseller'],
    displayOrder: 122
  },
  {
    id: 2423,
    vendorId: 23,
    categoryId: 2,
    name: 'Cheese Chilly Dry',
    description: 'Crisp paneer cubes wok-tossed dry with onions, bell peppers and chillies (Full: ₹230 / Half: ₹140)',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilli paneer', 'cheese chilly', 'dry', 'bestseller'],
    displayOrder: 123
  },
  {
    id: 2424,
    vendorId: 23,
    categoryId: 2,
    name: 'Crispy Veg.',
    description: 'Assorted crispy fried vegetables tossed with sweet & spicy Chinese sauce',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['crispy veg', 'starter'],
    displayOrder: 124
  },
  {
    id: 2425,
    vendorId: 23,
    categoryId: 2,
    name: 'Chilly Potato',
    description: 'Golden fried potato fingers coated in spicy sweet chilli sauce',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilli potato', 'potato', 'crispy'],
    displayOrder: 125
  },
  {
    id: 2426,
    vendorId: 23,
    categoryId: 2,
    name: 'Honey Chilly Potato',
    description: 'Crispy sesame potato fingers glazed in honey and spicy chilli sauce',
    price: '170.00',
    isVeg: true,
    isAvailable: true,
    tags: ['honey chilli potato', 'potato', 'bestseller'],
    displayOrder: 126
  },
  {
    id: 2427,
    vendorId: 23,
    categoryId: 2,
    name: 'Mushroom Chilly',
    description: 'Crispy mushrooms stir-fried with onions, capsicum and spicy sauce (Full: ₹180 / Half: ₹130)',
    price: '130.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom', 'chilli mushroom'],
    displayOrder: 127
  },
  {
    id: 2428,
    vendorId: 23,
    categoryId: 2,
    name: 'Chana Chilly',
    description: 'Crispy fried chickpeas tossed with spicy Indo-Chinese seasoning',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chana chilly', 'chole', 'crispy'],
    displayOrder: 128
  },
  {
    id: 2429,
    vendorId: 23,
    categoryId: 2,
    name: 'French Fry',
    description: 'Golden salted crispy potato french fries',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['french fries', 'fries', 'crispy'],
    displayOrder: 129
  },
  {
    id: 2430,
    vendorId: 23,
    categoryId: 2,
    name: 'Veg. Pakora',
    description: 'Hot mixed vegetable crispy pakoras served with green chutney',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pakora', 'veg pakora', 'snack'],
    displayOrder: 130
  },
  {
    id: 2431,
    vendorId: 23,
    categoryId: 2,
    name: 'Paneer Pakora',
    description: 'Soft cottage cheese slices coated in spiced gram flour batter and fried',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pakora', 'paneer pakora', 'protein'],
    displayOrder: 131
  },
  {
    id: 2432,
    vendorId: 23,
    categoryId: 2,
    name: 'Veg. Momos (Fried)',
    description: 'Crispy fried dumplings stuffed with spiced vegetables (Full: ₹100 / Half: ₹60)',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['momos', 'veg momos', 'fried momos'],
    displayOrder: 132
  },
  {
    id: 2433,
    vendorId: 23,
    categoryId: 2,
    name: 'Cheese Momos',
    description: 'Crispy momos loaded with seasoned melted paneer & cheese (Full: ₹140 / Half: ₹80)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['momos', 'cheese momos', 'paneer momos'],
    displayOrder: 133
  },
  {
    id: 2434,
    vendorId: 23,
    categoryId: 2,
    name: 'Chicken Momos (Fried)',
    description: 'Crispy fried momos filled with juicy minced chicken (Full: ₹150 / Half: ₹90)',
    price: '90.00',
    isVeg: false,
    isAvailable: true,
    tags: ['momos', 'chicken momos', 'chicken', 'protein', 'nonveg'],
    displayOrder: 134
  },
  {
    id: 2435,
    vendorId: 23,
    categoryId: 2,
    name: 'Chicken Steam Momos',
    description: 'Steamed juicy authentic Himalayan chicken momos with spicy red chutney (Full: ₹150 / Half: ₹90)',
    price: '90.00',
    isVeg: false,
    isAvailable: true,
    tags: ['momos', 'steamed momos', 'chicken momos', 'protein', 'nonveg'],
    displayOrder: 135
  },

  // ================= 🥣 SOUPS (Category 8 - Chai, Soups & Snacks) =================
  {
    id: 2436,
    vendorId: 23,
    categoryId: 8,
    name: 'Veg. Soup',
    description: 'Warm, clear mixed vegetable soup with herbs',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soup', 'veg soup', 'healthy'],
    displayOrder: 136
  },
  {
    id: 2437,
    vendorId: 23,
    categoryId: 8,
    name: 'Veg. Manchow Soup',
    description: 'Spicy Indo-Chinese soup topped with crispy fried noodles',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soup', 'manchow soup', 'chinese', 'spicy'],
    displayOrder: 137
  },
  {
    id: 2438,
    vendorId: 23,
    categoryId: 8,
    name: 'Veg. Tomato Soup',
    description: 'Creamy and tangy rich tomato soup with crunchy bread croutons',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soup', 'tomato soup', 'comfort-food'],
    displayOrder: 138
  },
  {
    id: 2439,
    vendorId: 23,
    categoryId: 8,
    name: 'Veg. Sweetcorn Soup',
    description: 'Mild, sweet and comforting soup loaded with sweet corn kernels',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soup', 'sweetcorn soup', 'comfort'],
    displayOrder: 139
  },
  {
    id: 2440,
    vendorId: 23,
    categoryId: 8,
    name: 'Veg. Hot Garlic Soup',
    description: 'Fiery broth infused with burnt roasted garlic and red chillies',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soup', 'garlic soup', 'spicy'],
    displayOrder: 140
  },
  {
    id: 2441,
    vendorId: 23,
    categoryId: 8,
    name: 'Veg. Hot & Sour Soup',
    description: 'Tangy and spicy thick broth packed with mushrooms and chopped vegetables',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soup', 'hot and sour', 'chinese'],
    displayOrder: 141
  },
  {
    id: 2442,
    vendorId: 23,
    categoryId: 8,
    name: 'Chicken Soup',
    description: 'Nourishing hot chicken broth with shredded chicken pieces and cracked black pepper',
    price: '120.00',
    isVeg: false,
    isAvailable: true,
    tags: ['soup', 'chicken soup', 'protein', 'warm', 'nonveg'],
    displayOrder: 142
  }
];
