export const THE_SPICE_CHAMBER_VENDOR = {
  id: 31,
  name: 'The Spice Chamber',
  slug: 'the-spice-chamber',
  phone: '9008704019',
  whatsapp: '9008704019',
  address: 'Kirmach Road, Near Hilton Salon, NIT Kurukshetra',
  latitude: '29.9675',
  longitude: '76.8830',
  opensAt: '12:00',
  closesAt: '22:30',
  deliversTo: ['NITKKR campus all'],
  image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80',
  isActive: true,
  isFeatured: true,
  displayOrder: 11,
  createdAt: new Date()
};

export const THE_SPICE_CHAMBER_MENU_ITEMS = [
  // ================= 🍖 MUTTON BIRYANI (Category 4 - North Indian & Thali) =================
  {
    id: 3201,
    vendorId: 31,
    categoryId: 4,
    name: 'Kolkata Mutton Biryani',
    description: 'Fragrant mild spiced basmati rice layered with juicy tender mutton pieces and signature potato (Half: ₹220 / Full: ₹400)',
    price: '220.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'mutton biryani', 'kolkata biryani', 'mutton', 'nonveg', 'bestseller'],
    displayOrder: 1
  },
  {
    id: 3202,
    vendorId: 31,
    categoryId: 4,
    name: 'Moradabadi Mutton Biryani',
    description: 'Aromatic Lucknowi-Moradabadi yakhni style mutton biryani served with spicy chutney (Half: ₹220 / Full: ₹400)',
    price: '220.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'mutton biryani', 'moradabadi', 'mutton', 'nonveg'],
    displayOrder: 2
  },
  {
    id: 3203,
    vendorId: 31,
    categoryId: 4,
    name: 'Shahi Mutton Biryani',
    description: 'Rich royal dum biryani with dry fruits, saffron, and tender slow-cooked mutton (Half: ₹220 / Full: ₹400)',
    price: '220.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'mutton biryani', 'shahi biryani', 'mutton', 'nonveg'],
    displayOrder: 3
  },
  {
    id: 3204,
    vendorId: 31,
    categoryId: 4,
    name: 'Hyderabadi Mutton Biryani',
    description: 'Spicy, flavorful authentic Hyderabadi kacchi dum mutton biryani (Half: ₹220 / Full: ₹400)',
    price: '220.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'mutton biryani', 'hyderabadi', 'mutton', 'nonveg', 'bestseller'],
    displayOrder: 4
  },
  {
    id: 3205,
    vendorId: 31,
    categoryId: 4,
    name: 'White Dum Mutton Biryani',
    description: 'Subtle, aromatic white spiced yakhni dum biryani with succulent mutton (Half: ₹220 / Full: ₹400)',
    price: '220.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'mutton biryani', 'white dum', 'mutton', 'nonveg'],
    displayOrder: 5
  },
  {
    id: 3206,
    vendorId: 31,
    categoryId: 4,
    name: 'Mutton Kacchi Biryani',
    description: 'Traditional slow dum cooked raw marinated mutton layered with long grain basmati (Half: ₹220 / Full: ₹400)',
    price: '220.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'mutton biryani', 'kacchi biryani', 'mutton', 'nonveg', 'bestseller'],
    displayOrder: 6
  },

  // ================= 🍗 CHICKEN BIRYANI (Category 4) =================
  {
    id: 3207,
    vendorId: 31,
    categoryId: 4,
    name: 'Kolkata Chicken Biryani',
    description: 'Mild spiced Kolkata style dum biryani with soft chicken and spiced potato (Half: ₹160 / Full: ₹300)',
    price: '160.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'chicken biryani', 'kolkata', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 7
  },
  {
    id: 3208,
    vendorId: 31,
    categoryId: 4,
    name: 'Moradabadi Chicken Biryani',
    description: 'Delicate yakhni infused rice with soft marinated chicken and lemon (Half: ₹160 / Full: ₹300)',
    price: '160.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'chicken biryani', 'moradabadi', 'chicken', 'nonveg'],
    displayOrder: 8
  },
  {
    id: 3209,
    vendorId: 31,
    categoryId: 4,
    name: 'Shahi Chicken Biryani',
    description: 'Mughlai style aromatic chicken dum biryani rich with spices (Half: ₹160 / Full: ₹300)',
    price: '160.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'chicken biryani', 'shahi', 'chicken', 'nonveg'],
    displayOrder: 9
  },
  {
    id: 3210,
    vendorId: 31,
    categoryId: 4,
    name: 'Hyderabadi Chicken Biryani',
    description: 'Fiery spiced authentic Nizami chicken dum biryani with fried onions (Half: ₹160 / Full: ₹300)',
    price: '160.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'chicken biryani', 'hyderabadi', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 10
  },
  {
    id: 3211,
    vendorId: 31,
    categoryId: 4,
    name: 'White Dum Chicken Biryani',
    description: 'Delicately spiced white basmati biryani with succulent chicken chunks (Half: ₹160 / Full: ₹300)',
    price: '160.00',
    isVeg: false,
    isAvailable: true,
    tags: ['biryani', 'chicken biryani', 'white dum', 'chicken', 'nonveg'],
    displayOrder: 11
  },

  // ================= 🍚 VEG BIRYANI (Category 4) =================
  {
    id: 3212,
    vendorId: 31,
    categoryId: 4,
    name: 'Veg Mix Paneer Biryani',
    description: 'Aromatic long basmati rice layered with fresh paneer cubes and vegetables (Half: ₹120 / Full: ₹240)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['biryani', 'veg biryani', 'paneer biryani', 'bestseller'],
    displayOrder: 12
  },
  {
    id: 3213,
    vendorId: 31,
    categoryId: 4,
    name: 'Paneer Tikka Biryani',
    description: 'Charcoal tandoor grilled paneer tikka tossed with spiced dum biryani (Half: ₹120 / Full: ₹240)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['biryani', 'paneer tikka biryani', 'tandoori', 'bestseller'],
    displayOrder: 13
  },

  // ================= 🥘 NON-VEG SPECIAL (Category 4) =================
  {
    id: 3214,
    vendorId: 31,
    categoryId: 4,
    name: 'Home Made Chicken',
    description: 'Desi homestyle chicken cooked in light aromatic onion tomato gravy (Half: ₹250 / Full: ₹500)',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'homemade chicken', 'curry', 'nonveg', 'bestseller'],
    displayOrder: 14
  },
  {
    id: 3215,
    vendorId: 31,
    categoryId: 4,
    name: 'Butter Chicken',
    description: 'Smoked tandoori chicken simmered in rich velvety makhani butter gravy (Half: ₹300 / Full: ₹550)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'butter chicken', 'makhani', 'nonveg', 'bestseller'],
    displayOrder: 15
  },
  {
    id: 3216,
    vendorId: 31,
    categoryId: 4,
    name: 'Kadhai Chicken',
    description: 'Tender chicken tossed with bell peppers, whole coriander and kadhai spices (Half: ₹250 / Full: ₹500)',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'kadhai chicken', 'nonveg'],
    displayOrder: 16
  },
  {
    id: 3217,
    vendorId: 31,
    categoryId: 4,
    name: 'Rara Chicken',
    description: 'Royal dish of bone chicken cooked with spicy minced chicken (keema) gravy (Half: ₹300 / Full: ₹550)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'rara chicken', 'keema', 'nonveg', 'bestseller'],
    displayOrder: 17
  },
  {
    id: 3218,
    vendorId: 31,
    categoryId: 4,
    name: 'Chicken Champaran',
    description: 'Famous Ahuna handi style slow-cooked mutton-flavored chicken with whole garlic pods (Half: ₹300 / Full: ₹550)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'champaran', 'ahuna chicken', 'handi', 'nonveg', 'bestseller'],
    displayOrder: 18
  },
  {
    id: 3219,
    vendorId: 31,
    categoryId: 4,
    name: 'Chicken Korma',
    description: 'Slow-cooked chicken in rich almond, cashew and yogurt gravy (Half: ₹250 / Full: ₹500)',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken korma', 'korma', 'nonveg'],
    displayOrder: 19
  },
  {
    id: 3220,
    vendorId: 31,
    categoryId: 4,
    name: 'Murgh Musallam',
    description: 'Mughlai delicacy of spiced roasted chicken in thick saffron almond gravy (Half: ₹300 / Full: ₹600)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'murgh musallam', 'royal', 'nonveg', 'bestseller'],
    displayOrder: 20
  },
  {
    id: 3221,
    vendorId: 31,
    categoryId: 4,
    name: 'Chicken Curry',
    description: 'Traditional dhaba style spicy chicken curry with whole spices (Half: ₹250 / Full: ₹500)',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken', 'chicken curry', 'curry', 'nonveg'],
    displayOrder: 21
  },
  {
    id: 3222,
    vendorId: 31,
    categoryId: 4,
    name: 'Fish Curry (Seasonal)',
    description: 'Fresh tender fish fillets simmered in aromatic Bengali mustard and tomato curry (Half: ₹200 / Full: ₹400)',
    price: '200.00',
    isVeg: false,
    isAvailable: true,
    tags: ['fish', 'fish curry', 'seafood', 'nonveg'],
    displayOrder: 22
  },

  // ================= 🔥 TANDOORI SPECIAL (Category 4) =================
  {
    id: 3223,
    vendorId: 31,
    categoryId: 4,
    name: 'Tandoori Chicken',
    description: 'Classic clay oven roasted bone-in chicken marinated in yogurt and tandoori spices (Half: ₹250 / Full: ₹550)',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['tandoori', 'tandoori chicken', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 23
  },
  {
    id: 3224,
    vendorId: 31,
    categoryId: 4,
    name: 'Achari Chicken',
    description: 'Tangy pickle-spiced tandoori roasted chicken with mustard punch (Half: ₹250 / Full: ₹550)',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['tandoori', 'achari chicken', 'chicken', 'nonveg'],
    displayOrder: 24
  },
  {
    id: 3225,
    vendorId: 31,
    categoryId: 4,
    name: 'Afghani Chicken',
    description: 'Mild, rich and creamy tandoori chicken marinated in cashew paste and fresh cream (Half: ₹300 / Full: ₹600)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['tandoori', 'afghani chicken', 'chicken', 'nonveg', 'bestseller'],
    displayOrder: 25
  },
  {
    id: 3226,
    vendorId: 31,
    categoryId: 4,
    name: 'Chicken Tikka',
    description: 'Smoky char-grilled boneless chicken cubes with mint chutney (Half: ₹250 / Full: ₹550)',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['tikka', 'chicken tikka', 'starter', 'nonveg', 'bestseller'],
    displayOrder: 26
  },
  {
    id: 3227,
    vendorId: 31,
    categoryId: 4,
    name: 'Achari Chicken Tikka',
    description: 'Boneless char-grilled chicken tikka with tangy pickling spices (Half: ₹250 / Full: ₹550)',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['tikka', 'achari tikka', 'chicken', 'nonveg'],
    displayOrder: 27
  },
  {
    id: 3228,
    vendorId: 31,
    categoryId: 4,
    name: 'Afghani Chicken Tikka',
    description: 'Melt-in-mouth boneless chicken tikka in luscious malai cream marinade (Half: ₹300 / Full: ₹600)',
    price: '300.00',
    isVeg: false,
    isAvailable: true,
    tags: ['tikka', 'afghani tikka', 'chicken', 'nonveg'],
    displayOrder: 28
  },
  {
    id: 3229,
    vendorId: 31,
    categoryId: 4,
    name: 'Crispy Chicken Fry',
    description: 'Spiced golden fried chicken bites with chaat masala and onions (Half: ₹250 / Full: ₹500)',
    price: '250.00',
    isVeg: false,
    isAvailable: true,
    tags: ['chicken fry', 'crispy chicken', 'nonveg'],
    displayOrder: 29
  },

  // ================= 🥦 VEG SPECIAL (Category 4) =================
  {
    id: 3230,
    vendorId: 31,
    categoryId: 4,
    name: 'Mix Veg',
    description: 'Seasonal garden fresh vegetables tossed in aromatic semi-dry gravy (Half: ₹100 / Full: ₹200)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix veg', 'veg', 'curry'],
    displayOrder: 30
  },
  {
    id: 3231,
    vendorId: 31,
    categoryId: 4,
    name: 'Dal Makhni',
    description: 'Slow-cooked black lentils simmered overnight with butter and fresh cream (Half: ₹100 / Full: ₹200)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal makhni', 'dal', 'butter', 'bestseller'],
    displayOrder: 31
  },
  {
    id: 3232,
    vendorId: 31,
    categoryId: 4,
    name: 'Shahi Paneer',
    description: 'Soft cottage cheese triangles simmered in sweet creamy royal cashew gravy (Half: ₹150 / Full: ₹300)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shahi paneer', 'paneer', 'curry', 'bestseller'],
    displayOrder: 32
  },
  {
    id: 3233,
    vendorId: 31,
    categoryId: 4,
    name: 'Paneer Butter Masala',
    description: 'Paneer cubes cooked in rich tangy tomato and butter makhani gravy (Half: ₹170 / Full: ₹320)',
    price: '170.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer butter masala', 'paneer', 'makhani', 'bestseller'],
    displayOrder: 33
  },
  {
    id: 3234,
    vendorId: 31,
    categoryId: 4,
    name: 'Kadhai Paneer',
    description: 'Fresh paneer cooked with capsicum, onion, and crushed coriander seeds (Half: ₹170 / Full: ₹320)',
    price: '170.00',
    isVeg: true,
    isAvailable: true,
    tags: ['kadhai paneer', 'paneer', 'spicy'],
    displayOrder: 34
  },
  {
    id: 3235,
    vendorId: 31,
    categoryId: 4,
    name: 'Tandoori Paneer Tikka',
    description: 'Marinated cottage cheese cubes roasted in tandoor with bell peppers and onion (Half: ₹200 / Full: ₹400)',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer tikka', 'tandoori', 'starter', 'bestseller'],
    displayOrder: 35
  },

  // ================= 🍳 EGG SPECIAL (Category 4 / Category 7) =================
  {
    id: 3236,
    vendorId: 31,
    categoryId: 4,
    name: 'Egg Curry (Special)',
    description: 'Two golden fried boiled eggs in spicy thick Punjabi gravy',
    price: '170.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg curry', 'egg', 'eggs', 'protein', 'bestseller'],
    displayOrder: 36
  },
  {
    id: 3237,
    vendorId: 31,
    categoryId: 4,
    name: 'Egg Bhurji',
    description: 'Double egg masala scramble with onions, green chilies, and coriander',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['egg bhurji', 'egg', 'eggs', 'protein', 'under-50'],
    displayOrder: 37
  },
  {
    id: 3238,
    vendorId: 31,
    categoryId: 4,
    name: 'Masala Omelette',
    description: 'Fluffy double egg masala omelet prepared with chopped veggies',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['omelet', 'egg', 'eggs', 'under-50'],
    displayOrder: 38
  },
  {
    id: 3239,
    vendorId: 31,
    categoryId: 4,
    name: 'Sunny Side Up',
    description: 'Classic fried egg with soft runny golden yolk and crispy edges',
    price: '50.00',
    isVeg: false,
    isAvailable: true,
    tags: ['sunny side up', 'egg', 'eggs', 'under-50'],
    displayOrder: 39
  },
  {
    id: 3240,
    vendorId: 31,
    categoryId: 4,
    name: 'Scrambled Egg',
    description: 'Creamy soft buttery scrambled eggs seasoned with black pepper',
    price: '70.00',
    isVeg: false,
    isAvailable: true,
    tags: ['scrambled egg', 'egg', 'eggs', 'protein'],
    displayOrder: 40
  },
  {
    id: 3241,
    vendorId: 31,
    categoryId: 4,
    name: 'Poached Egg',
    description: 'Delicately water-poached tender eggs with warm runny yolk',
    price: '80.00',
    isVeg: false,
    isAvailable: true,
    tags: ['poached egg', 'egg', 'eggs', 'healthy'],
    displayOrder: 41
  },
  {
    id: 3242,
    vendorId: 31,
    categoryId: 4,
    name: 'Boiled Egg (1 Pc)',
    description: 'Farm fresh hard-boiled egg with rock salt and pepper',
    price: '15.00',
    isVeg: false,
    isAvailable: true,
    tags: ['boiled egg', 'egg', 'eggs', 'under-50'],
    displayOrder: 42
  },

  // ================= 🥣 RAITA (Category 4) =================
  {
    id: 3243,
    vendorId: 31,
    categoryId: 4,
    name: 'Boondi Raita',
    description: 'Chilled spiced whipped curd with crispy salted chickpea boondi',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'boondi raita', 'under-50'],
    displayOrder: 43
  },
  {
    id: 3244,
    vendorId: 31,
    categoryId: 4,
    name: 'Onion Raita',
    description: 'Cool seasoned yogurt with finely chopped crunchy onions and jeera',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'onion raita'],
    displayOrder: 44
  },
  {
    id: 3245,
    vendorId: 31,
    categoryId: 4,
    name: 'Cucumber Raita',
    description: 'Refreshing cucumber grated into thick seasoned curd',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'cucumber raita'],
    displayOrder: 45
  },
  {
    id: 3246,
    vendorId: 31,
    categoryId: 4,
    name: 'Mix Veg Raita',
    description: 'Whipped curd loaded with cucumber, tomato, onion and roasted cumin',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'mix raita'],
    displayOrder: 46
  },
  {
    id: 3247,
    vendorId: 31,
    categoryId: 4,
    name: 'Burani Raita (Garlic Raita)',
    description: 'Smoky Mughlai garlic and roasted cumin infused rich yogurt dip',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'burani raita', 'garlic raita', 'bestseller'],
    displayOrder: 47
  },

  // ================= 🍚 RICE & PULAO (Category 4) =================
  {
    id: 3248,
    vendorId: 31,
    categoryId: 4,
    name: 'Steamed Rice',
    description: 'Fluffy long grain fragrant basmati rice',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'steamed rice'],
    displayOrder: 48
  },
  {
    id: 3249,
    vendorId: 31,
    categoryId: 4,
    name: 'Jeera Rice',
    description: 'Basmati rice tempered with roasted cumin seeds and desi ghee',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'jeera rice'],
    displayOrder: 49
  },
  {
    id: 3250,
    vendorId: 31,
    categoryId: 4,
    name: 'Peas Pulao',
    description: 'Sweet green peas tossed in aromatic mild spiced basmati pulao',
    price: '130.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'peas pulao', 'pulao'],
    displayOrder: 50
  },

  // ================= 🥗 SALAD & CHAAT =================
  {
    id: 3251,
    vendorId: 31,
    categoryId: 8,
    name: 'Roasted Chana Chaat',
    description: 'Crispy roasted black chickpeas tossed with onions, tomatoes, lemon and spices',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chaat', 'chana chaat', 'healthy', 'snack'],
    displayOrder: 51
  },
  {
    id: 3252,
    vendorId: 31,
    categoryId: 8,
    name: 'Peanut Chaat',
    description: 'Roasted peanuts tossed with fresh chopped onions, coriander, lime and green chilies',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chaat', 'peanut chaat', 'healthy', 'snack'],
    displayOrder: 52
  },
  {
    id: 3253,
    vendorId: 31,
    categoryId: 8,
    name: 'Onion Ring Salad',
    description: 'Sliced onion rings tossed with lemon juice, green chilies, and chaat masala',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['salad', 'onion salad'],
    displayOrder: 53
  },
  {
    id: 3254,
    vendorId: 31,
    categoryId: 8,
    name: 'Green Salad',
    description: 'Fresh sliced cucumbers, tomatoes, carrots, onions, and lemon wedges',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['salad', 'green salad', 'healthy'],
    displayOrder: 54
  },
  {
    id: 3255,
    vendorId: 31,
    categoryId: 8,
    name: 'Greek Salad',
    description: 'Crisp lettuce, bell peppers, cucumbers, olives, and fresh cheese with vinaigrette',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['salad', 'greek salad', 'healthy'],
    displayOrder: 55
  },

  // ================= 🍲 SOUPS =================
  {
    id: 3256,
    vendorId: 31,
    categoryId: 8,
    name: 'Hot Chicken Soup',
    description: 'Clear aromatic chicken broth with shredded chicken, ginger and pepper',
    price: '80.00',
    isVeg: false,
    isAvailable: true,
    tags: ['soup', 'chicken soup', 'nonveg', 'healthy'],
    displayOrder: 56
  },
  {
    id: 3257,
    vendorId: 31,
    categoryId: 8,
    name: 'Royal Mutton Soup',
    description: 'Rich slow-simmered mutton bone broth loaded with herbs and warmth',
    price: '120.00',
    isVeg: false,
    isAvailable: true,
    tags: ['soup', 'mutton soup', 'nonveg', 'bestseller'],
    displayOrder: 57
  },
  {
    id: 3258,
    vendorId: 31,
    categoryId: 8,
    name: 'Egg Drop Soup',
    description: 'Comforting pepper broth with silky scrambled egg ribbons',
    price: '70.00',
    isVeg: false,
    isAvailable: true,
    tags: ['soup', 'egg soup', 'egg', 'eggs'],
    displayOrder: 58
  },

  // ================= 🫓 ROTI & NAAN (Category 4) =================
  {
    id: 3259,
    vendorId: 31,
    categoryId: 4,
    name: 'Tandoori Roti (Plain)',
    description: 'Clay oven baked crisp whole wheat tandoori roti',
    price: '10.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'tandoori roti', 'under-50'],
    displayOrder: 59
  },
  {
    id: 3260,
    vendorId: 31,
    categoryId: 4,
    name: 'Butter Tandoori Roti',
    description: 'Crisp tandoori roti brushed with melted butter',
    price: '15.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'butter roti', 'under-50'],
    displayOrder: 60
  },
  {
    id: 3261,
    vendorId: 31,
    categoryId: 4,
    name: 'Plain Naan',
    description: 'Soft and chewy refined flour bread baked in tandoor',
    price: '35.00',
    isVeg: true,
    isAvailable: true,
    tags: ['naan', 'plain naan', 'under-50'],
    displayOrder: 61
  },
  {
    id: 3262,
    vendorId: 31,
    categoryId: 4,
    name: 'Butter Naan',
    description: 'Soft tandoori naan generously glazed with butter',
    price: '45.00',
    isVeg: true,
    isAvailable: true,
    tags: ['naan', 'butter naan', 'under-50', 'bestseller'],
    displayOrder: 62
  },
  {
    id: 3263,
    vendorId: 31,
    categoryId: 4,
    name: 'Garlic Naan',
    description: 'Tandoori naan topped with roasted minced garlic and fresh coriander',
    price: '45.00',
    isVeg: true,
    isAvailable: true,
    tags: ['naan', 'garlic naan', 'under-50', 'bestseller'],
    displayOrder: 63
  }
];
