export const YUMMY_TUMMY_FOODS_VENDOR = {
  id: 35,
  name: 'Yummy Tummy Foods & Guest House',
  slug: 'yummy-tummy-foods',
  phone: '7888551903',
  whatsapp: '7888551903',
  address: 'Opp. NIT Gate, Kirmach Road, Kurukshetra - 136118',
  latitude: '29.9680',
  longitude: '76.8824',
  opensAt: '08:00',
  closesAt: '23:30',
  deliversTo: ['NITKKR campus all'],
  image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=800&auto=format&fit=crop&q=80',
  isActive: true,
  isFeatured: true,
  displayOrder: 15,
  createdAt: new Date()
};

export const YUMMY_TUMMY_FOODS_MENU_ITEMS = [
  // ================= 🏆 BHARAT KA SABSE BDA PARANTHA & SPECIAL CHALLENGE (Category 4) =================
  {
    id: 3701,
    vendorId: 35,
    categoryId: 4,
    name: 'Bharat Ka Sabse Bda Parantha',
    description: 'Yummy Tummy signature gigantic jumbo parantha! Challenge: Eat 1 parantha in 20 minutes & win ₹1100 cash prize!',
    price: '400.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'challenge', 'bestseller', 'signature', 'jumbo parantha', 'prize'],
    displayOrder: 1
  },

  // ================= 🫓 STUFFED TANDOORI / TAWA PARANTHAS (Category 4) =================
  {
    id: 3702,
    vendorId: 35,
    categoryId: 4,
    name: 'Aalu Parantha',
    description: 'Crisp spiced potato stuffed parantha served hot with butter and pickle (Single: ₹30 / Double: ₹50)',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'aalu parantha', 'breakfast', 'popular'],
    displayOrder: 2
  },
  {
    id: 3703,
    vendorId: 35,
    categoryId: 4,
    name: 'Aalu Bhujia Parantha',
    description: 'Special savory crisp parantha stuffed with spicy aalu and crunchy bhujia (Single: ₹80 / Double: ₹120)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'aalu bhujia', 'speciality'],
    displayOrder: 3
  },
  {
    id: 3704,
    vendorId: 35,
    categoryId: 4,
    name: 'Onion Parantha',
    description: 'Delicious golden parantha stuffed with spiced chopped onions and fresh herbs (Single: ₹60 / Double: ₹100)',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'onion parantha', 'pyaz parantha'],
    displayOrder: 4
  },
  {
    id: 3705,
    vendorId: 35,
    categoryId: 4,
    name: 'Gobi Parantha',
    description: 'Grated spiced cauliflower stuffed fresh parantha (Single: ₹60 / Double: ₹100)',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'gobi parantha'],
    displayOrder: 5
  },
  {
    id: 3706,
    vendorId: 35,
    categoryId: 4,
    name: 'Paneer Parantha',
    description: 'Fresh grated cottage cheese seasoned with ajwain, green chillies and coriander (Single: ₹60 / Double: ₹100)',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'paneer parantha', 'bestseller'],
    displayOrder: 6
  },
  {
    id: 3707,
    vendorId: 35,
    categoryId: 4,
    name: 'Mix Parantha',
    description: 'Multi-veggie stuffed parantha with potato, onion, gobi and paneer (Single: ₹60 / Double: ₹100)',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'mix parantha'],
    displayOrder: 7
  },
  {
    id: 3708,
    vendorId: 35,
    categoryId: 4,
    name: 'Garlic Parantha',
    description: 'Aromatic roasted garlic infused flaky stuffed parantha (Single: ₹80 / Double: ₹100)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'garlic parantha'],
    displayOrder: 8
  },
  {
    id: 3709,
    vendorId: 35,
    categoryId: 4,
    name: 'Plain Parantha',
    description: 'Traditional golden layered triangle tawa parantha',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'plain parantha', 'roti'],
    displayOrder: 9
  },
  {
    id: 3710,
    vendorId: 35,
    categoryId: 4,
    name: 'Lachha Parantha',
    description: 'Multi-layered flaky crisp parantha brushed with fresh butter',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['parantha', 'lachha parantha', 'roti'],
    displayOrder: 10
  },

  // ================= 🍲 MAIN COURSE INDIAN VEG CURRIES (Category 4) =================
  {
    id: 3711,
    vendorId: 35,
    categoryId: 4,
    name: 'Sev Tamatar / Bhaji',
    description: 'Kathiyawadi style tangy and spicy tomato curry loaded with crisp ratlami sev (Half: ₹150 / Full: ₹180)',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['sev tamatar', 'curry', 'gujarati', 'popular'],
    displayOrder: 11
  },
  {
    id: 3712,
    vendorId: 35,
    categoryId: 4,
    name: 'Paneer Do Pyaza',
    description: 'Tender paneer cubes simmered in aromatic gravy with double caramelised onions and whole spices',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer do pyaza', 'curry'],
    displayOrder: 12
  },
  {
    id: 3713,
    vendorId: 35,
    categoryId: 4,
    name: 'Kadai Paneer',
    description: 'Cottage cheese wok-tossed with fresh crunchy bell peppers, onions and crushed coriander spices',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'kadai paneer', 'bestseller'],
    displayOrder: 13
  },
  {
    id: 3714,
    vendorId: 35,
    categoryId: 4,
    name: 'Shahi Paneer',
    description: 'Rich, creamy and mild royal cashew-tomato gravy simmered with fresh cottage cheese',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'shahi paneer', 'royal', 'bestseller'],
    displayOrder: 14
  },
  {
    id: 3715,
    vendorId: 35,
    categoryId: 4,
    name: 'Paneer Butter Masala',
    description: 'Velvety rich makhani gravy enriched with butter, cream and paneer cubes (Half: ₹160 / Full: ₹220)',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'paneer butter masala', 'butter paneer', 'bestseller'],
    displayOrder: 15
  },
  {
    id: 3716,
    vendorId: 35,
    categoryId: 4,
    name: 'Paneer Methi Chaman',
    description: 'Kashmiri delicacy of succulent paneer cooked with fragrant fenugreek leaves and aromatic herbs',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer', 'methi chaman', 'speciality'],
    displayOrder: 16
  },
  {
    id: 3717,
    vendorId: 35,
    categoryId: 4,
    name: 'Soyabeen Kadai Masala',
    description: 'Nutritious high-protein soya chunks cooked in spicy kadai onion-tomato gravy',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soya', 'kadai soya', 'protein', 'curry'],
    displayOrder: 17
  },
  {
    id: 3718,
    vendorId: 35,
    categoryId: 4,
    name: 'Soya Bhurji Gravy',
    description: 'Finely minced soya granules simmered with onions, ginger and roasted spices',
    price: '130.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soya', 'soya bhurji', 'curry'],
    displayOrder: 18
  },
  {
    id: 3719,
    vendorId: 35,
    categoryId: 4,
    name: 'Amritsari Paneer Bhurji',
    description: 'Spicy street-style scrambled paneer loaded with tomatoes, green chillies, butter and Amritsari spices',
    price: '250.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer bhurji', 'amritsari', 'bestseller'],
    displayOrder: 19
  },
  {
    id: 3720,
    vendorId: 35,
    categoryId: 4,
    name: 'Paneer Bhurji',
    description: 'Fresh hand-crumbled cottage cheese sautéed with onions, tomatoes, coriander and fragrant spices',
    price: '250.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer bhurji', 'paneer'],
    displayOrder: 20
  },
  {
    id: 3721,
    vendorId: 35,
    categoryId: 4,
    name: 'Dal Fry',
    description: 'Yellow lentils tempered with cumin seeds, garlic, ginger, green chillies and fresh ghee (Half: ₹100 / Full: ₹130)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal', 'dal fry', 'homestyle'],
    displayOrder: 21
  },
  {
    id: 3722,
    vendorId: 35,
    categoryId: 4,
    name: 'Dal Makhni',
    description: 'Creamy slow-cooked whole black lentils simmered overnight with butter and fresh cream (Half: ₹120 / Full: ₹160)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dal makhani', 'dal makhni', 'curry', 'bestseller'],
    displayOrder: 22
  },
  {
    id: 3723,
    vendorId: 35,
    categoryId: 4,
    name: 'Mix Veg.',
    description: 'Assorted seasonal vegetables tossed in semi-dry masala with fragrant cumin and coriander',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mix veg', 'vegetables', 'curry'],
    displayOrder: 23
  },
  {
    id: 3724,
    vendorId: 35,
    categoryId: 4,
    name: 'Malai Kofta',
    description: 'Melt-in-mouth cottage cheese and potato dumplings simmered in rich creamy cashew gravy',
    price: '250.00',
    isVeg: true,
    isAvailable: true,
    tags: ['malai kofta', 'kofta', 'royal'],
    displayOrder: 24
  },
  {
    id: 3725,
    vendorId: 35,
    categoryId: 4,
    name: 'Malai Pyaz Tamatar',
    description: 'Homestyle rich and creamy curry made with sliced onions, ripe tomatoes and fresh malai',
    price: '130.00',
    isVeg: true,
    isAvailable: true,
    tags: ['malai pyaz', 'curry', 'comfort food'],
    displayOrder: 25
  },
  {
    id: 3726,
    vendorId: 35,
    categoryId: 4,
    name: 'Aalu Zeera',
    description: 'Boiled diced potatoes tossed with roasted cumin seeds, turmeric and green chillies',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['aalu zeera', 'aloo jeera', 'dry sabzi'],
    displayOrder: 26
  },
  {
    id: 3727,
    vendorId: 35,
    categoryId: 4,
    name: 'Gravy Chaap',
    description: 'Tender soya chaap pieces cooked in rich, spicy and aromatic thick tomato-onion gravy',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chaap', 'soya chaap', 'gravy chaap'],
    displayOrder: 27
  },
  {
    id: 3728,
    vendorId: 35,
    categoryId: 4,
    name: 'Mushroom Masala',
    description: 'Fresh tender button mushrooms simmered in spiced onion, tomato and garlic gravy',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom', 'mushroom masala'],
    displayOrder: 28
  },
  {
    id: 3729,
    vendorId: 35,
    categoryId: 4,
    name: 'Kadai Mushroom',
    description: 'Stir-fried button mushrooms with crisp bell peppers, onions and crushed kadai spices',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom', 'kadai mushroom'],
    displayOrder: 29
  },
  {
    id: 3730,
    vendorId: 35,
    categoryId: 4,
    name: 'Chana Masala',
    description: 'Punjabi style slow-cooked chickpeas with ginger, roasted anardana and garam masala (Half: ₹120 / Full: ₹150)',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chana masala', 'chole', 'curry'],
    displayOrder: 30
  },

  // ================= 🍞 ROTI & BREADS (Category 4) =================
  {
    id: 3731,
    vendorId: 35,
    categoryId: 4,
    name: 'Tawa Roti',
    description: 'Freshly puffed whole wheat tawa phulka',
    price: '12.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'tawa roti', 'bread'],
    displayOrder: 31
  },
  {
    id: 3732,
    vendorId: 35,
    categoryId: 4,
    name: 'Butter Roti',
    description: 'Fresh whole wheat tawa roti generously brushed with creamy butter',
    price: '13.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roti', 'butter roti', 'bread'],
    displayOrder: 32
  },

  // ================= 🥣 FRESH RAITA & DAHI (Category 4) =================
  {
    id: 3733,
    vendorId: 35,
    categoryId: 4,
    name: 'Nepali Chukauni Raita',
    description: 'Authentic Nepali specialty whipped yogurt tempered with mustard seeds, fenugreek, boiled potatoes and spices',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'chukauni', 'nepali', 'speciality'],
    displayOrder: 33
  },
  {
    id: 3734,
    vendorId: 35,
    categoryId: 4,
    name: 'Mix Raita',
    description: 'Chilled curd with chopped cucumber, tomato, onion and roasted cumin',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'mix raita'],
    displayOrder: 34
  },
  {
    id: 3735,
    vendorId: 35,
    categoryId: 4,
    name: 'Onion Raita',
    description: 'Refreshing curd seasoned with crisp diced onions, black salt and mint',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'onion raita'],
    displayOrder: 35
  },
  {
    id: 3736,
    vendorId: 35,
    categoryId: 4,
    name: 'Bundi Raita',
    description: 'Classic curd blended with crispy gram flour boondi and roasted jeera powder',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['raita', 'boondi raita'],
    displayOrder: 36
  },
  {
    id: 3737,
    vendorId: 35,
    categoryId: 4,
    name: 'Fresh Dahi',
    description: 'Cool fresh bowl of homestyle curd',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dahi', 'curd'],
    displayOrder: 37
  },
  {
    id: 3738,
    vendorId: 35,
    categoryId: 4,
    name: 'Masala Dahi',
    description: 'Chilled curd seasoned with chaat masala, roasted cumin and rock salt',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['dahi', 'masala dahi'],
    displayOrder: 38
  },

  // ================= 🍚 BASMATI RICE & BIRYANI (Category 4) =================
  {
    id: 3739,
    vendorId: 35,
    categoryId: 4,
    name: 'Basmati Rice Plain',
    description: 'Steamed long-grain aromatic fragrant basmati rice (Half: ₹50 / Full: ₹70)',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'basmati rice', 'steamed rice'],
    displayOrder: 39
  },
  {
    id: 3740,
    vendorId: 35,
    categoryId: 4,
    name: 'Jeera Rice',
    description: 'Fragrant basmati rice tempered with roasted cumin seeds and fresh ghee (Half: ₹60 / Full: ₹80)',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['rice', 'jeera rice'],
    displayOrder: 40
  },
  {
    id: 3741,
    vendorId: 35,
    categoryId: 4,
    name: 'Veg. Biryani',
    description: 'Spiced aromatic basmati rice layered with garden vegetables and saffron herbs (Half: ₹90 / Full: ₹130)',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['biryani', 'veg biryani', 'bestseller'],
    displayOrder: 41
  },
  {
    id: 3742,
    vendorId: 35,
    categoryId: 4,
    name: 'Veg. Fried Rice',
    description: 'Wok-tossed basmati rice with finely diced crunchy carrots, beans and capsicum (Half: ₹90 / Full: ₹130)',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fried rice', 'chinese rice'],
    displayOrder: 42
  },
  {
    id: 3743,
    vendorId: 35,
    categoryId: 4,
    name: 'Soyabeen Fried Rice',
    description: 'Nutritious wok-fried rice tossed with crispy soya nuggets and spring onions',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fried rice', 'soya fried rice', 'protein'],
    displayOrder: 43
  },
  {
    id: 3744,
    vendorId: 35,
    categoryId: 4,
    name: 'Paneer Fried Rice',
    description: 'Wok-tossed aromatic rice packed with sautéed paneer cubes and crunchy greens',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fried rice', 'paneer fried rice', 'bestseller'],
    displayOrder: 44
  },

  // ================= 🌯 KATHI ROLLS & WRAPS (Category 7) =================
  {
    id: 3745,
    vendorId: 35,
    categoryId: 7,
    name: 'Paneer Roll',
    description: 'Flaky parantha wrap stuffed with spiced marinated paneer cubes, crisp onions and sauces',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roll', 'paneer roll', 'wrap', 'bestseller'],
    displayOrder: 45
  },
  {
    id: 3746,
    vendorId: 35,
    categoryId: 7,
    name: 'Soya Chaap Roll',
    description: 'Juicy tandoori spiced soya chaap chunks rolled with tangy mint chutney and onions',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roll', 'chaap roll', 'wrap'],
    displayOrder: 46
  },
  {
    id: 3747,
    vendorId: 35,
    categoryId: 7,
    name: 'Veg. Wrap',
    description: 'Crunchy mixed vegetables and potato stuffing rolled in a fresh warm tortilla wrap',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['wrap', 'veg wrap', 'roll'],
    displayOrder: 47
  },
  {
    id: 3748,
    vendorId: 35,
    categoryId: 7,
    name: 'Paneer Papad Roll',
    description: 'Special crisp papad roll wrapped with spiced seasoned cottage cheese stuffing',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['roll', 'papad roll', 'paneer papad roll', 'speciality'],
    displayOrder: 48
  },

  // ================= 🍔 FAST FOOD, PASTA & PIZZA (Category 1) =================
  {
    id: 3749,
    vendorId: 35,
    categoryId: 1,
    name: 'White Pasta',
    description: 'Penne pasta tossed in rich, velvety and creamy béchamel cheese sauce with Italian herbs',
    price: '180.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pasta', 'white pasta', 'alfredo', 'italian'],
    displayOrder: 49
  },
  {
    id: 3750,
    vendorId: 35,
    categoryId: 1,
    name: 'Red Pasta',
    description: 'Spicy and tangy arrabbiata tomato sauce pasta with garlic and bell peppers',
    price: '140.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pasta', 'red pasta', 'arrabbiata'],
    displayOrder: 50
  },
  {
    id: 3751,
    vendorId: 35,
    categoryId: 1,
    name: 'Classic Veg Pizza',
    description: 'Crisp oven-baked crust topped with mozzarella cheese, capsicum, onion and tomato sauce',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pizza', 'cheese pizza'],
    displayOrder: 51
  },
  {
    id: 3752,
    vendorId: 35,
    categoryId: 1,
    name: 'Macaroni',
    description: 'Desi style spiced macaroni cooked with diced vegetables and tangy sauces',
    price: '120.00',
    isVeg: true,
    isAvailable: true,
    tags: ['macaroni', 'pasta', 'desi pasta'],
    displayOrder: 52
  },
  {
    id: 3753,
    vendorId: 35,
    categoryId: 1,
    name: 'Veg Burger',
    description: 'Golden crispy potato patty topped with fresh lettuce, cucumber, onion and creamy mayo (Single: ₹40 / Double Patty: ₹60)',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['burger', 'veg burger', 'popular'],
    displayOrder: 53
  },
  {
    id: 3754,
    vendorId: 35,
    categoryId: 1,
    name: 'Veg Sandwich',
    description: 'Fresh sliced bread sandwich loaded with crisp veggies and green chutney (Plain: ₹60 / Grilled: ₹70)',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['sandwich', 'veg sandwich'],
    displayOrder: 54
  },
  {
    id: 3755,
    vendorId: 35,
    categoryId: 1,
    name: 'Pizza Sandwich',
    description: 'Toasted bread loaded with pizza sauce, mozzarella cheese, corn, bell peppers and oregano',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['sandwich', 'pizza sandwich', 'cheese sandwich'],
    displayOrder: 55
  },
  {
    id: 3756,
    vendorId: 35,
    categoryId: 1,
    name: 'Cheese Sandwich',
    description: 'Melted cheese slice grilled between golden buttered bread slices',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['sandwich', 'cheese sandwich'],
    displayOrder: 56
  },
  {
    id: 3757,
    vendorId: 35,
    categoryId: 1,
    name: 'Phool Samosa (4 Pcs.)',
    description: 'Mini bite-sized crispy floral patterned samosas stuffed with spiced potatoes (4 Pieces)',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['samosa', 'phool samosa', 'snacks'],
    displayOrder: 57
  },
  {
    id: 3758,
    vendorId: 35,
    categoryId: 1,
    name: 'Khopra Pattie',
    description: 'Indori style sweet and savory crisp potato pattie filled with spiced grated coconut stuffing',
    price: '100.00',
    isVeg: true,
    isAvailable: true,
    tags: ['pattie', 'khopra pattie', 'coconut', 'speciality'],
    displayOrder: 58
  },

  // ================= 🥢 CHINESE SPECIALS & SIZZLING CHILLI (Category 2) =================
  {
    id: 3759,
    vendorId: 35,
    categoryId: 2,
    name: 'Veg Chowmein',
    description: 'Wok-tossed noodles with shredded cabbage, carrots, bell peppers, soy sauce and vinegar',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chowmein', 'noodles', 'chinese'],
    displayOrder: 59
  },
  {
    id: 3760,
    vendorId: 35,
    categoryId: 2,
    name: 'Veg Manchurian',
    description: 'Crisp vegetable dumplings tossed in garlic, ginger, soya and chilli gravy (Half: ₹160 / Full: ₹200)',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['manchurian', 'chinese', 'bestseller'],
    displayOrder: 60
  },
  {
    id: 3761,
    vendorId: 35,
    categoryId: 2,
    name: 'Chilly Potato',
    description: 'Crispy fried potato fingers tossed in spicy sweet red chilli sauce and sesame seeds',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilli potato', 'chinese', 'popular'],
    displayOrder: 61
  },
  {
    id: 3762,
    vendorId: 35,
    categoryId: 2,
    name: 'Honey Chilly Potato',
    description: 'Super crunchy potato batons glazed in honey, chilli garlic paste and toasted sesame',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['honey chilli potato', 'chinese', 'bestseller'],
    displayOrder: 62
  },
  {
    id: 3763,
    vendorId: 35,
    categoryId: 2,
    name: 'Honey Cauliflower',
    description: 'Crisp batter-fried gobi florets glazed in spicy-sweet honey chilli sauce',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['honey cauliflower', 'gobi chilli', 'chinese'],
    displayOrder: 63
  },
  {
    id: 3764,
    vendorId: 35,
    categoryId: 2,
    name: 'Cheese Chilly',
    description: 'Crispy fried cottage cheese cubes tossed with diced bell peppers, onions and hot chilli soy sauce',
    price: '250.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chilli paneer', 'cheese chilly', 'chinese', 'bestseller'],
    displayOrder: 64
  },
  {
    id: 3765,
    vendorId: 35,
    categoryId: 2,
    name: 'Cheese Finger',
    description: 'Golden fried crispy paneer fingers served with spicy dip',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['cheese finger', 'paneer finger', 'crispy'],
    displayOrder: 65
  },
  {
    id: 3766,
    vendorId: 35,
    categoryId: 2,
    name: 'Soya Chaap Chilly',
    description: 'Fried crisp soya chaap chunks wok-tossed in pungent chilli garlic sauce and scallions',
    price: '220.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chaap chilly', 'soya chaap', 'chinese'],
    displayOrder: 66
  },
  {
    id: 3767,
    vendorId: 35,
    categoryId: 2,
    name: 'Mushroom Chilli',
    description: 'Crispy golden button mushrooms tossed with green chillies, onions and garlic soy',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom chilli', 'chinese'],
    displayOrder: 67
  },

  // ================= 🍟 SNACKS & MAGGI (Category 8) =================
  {
    id: 3768,
    vendorId: 35,
    categoryId: 8,
    name: 'Finger Chips',
    description: 'Golden salted French fries served hot with ketchup (Half: ₹70 / Full: ₹120)',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fries', 'french fries', 'finger chips'],
    displayOrder: 68
  },
  {
    id: 3769,
    vendorId: 35,
    categoryId: 8,
    name: 'Peri Peri Fries',
    description: 'Crispy potato fries dusted with zesty peri peri spice seasoning',
    price: '130.00',
    isVeg: true,
    isAvailable: true,
    tags: ['fries', 'peri peri fries', 'snacks'],
    displayOrder: 69
  },
  {
    id: 3770,
    vendorId: 35,
    categoryId: 8,
    name: 'Peanut Masala',
    description: 'Roasted crunchy peanuts tossed with chopped onions, tomatoes, green chillies and lemon juice (Half: ₹90 / Full: ₹120)',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['peanut masala', 'chakna', 'snacks'],
    displayOrder: 70
  },
  {
    id: 3771,
    vendorId: 35,
    categoryId: 8,
    name: 'Paneer Tikka Disk',
    description: 'Tandoori marinated paneer discs grilled with spices and mint chutney',
    price: '160.00',
    isVeg: true,
    isAvailable: true,
    tags: ['paneer tikka', 'starter', 'snacks'],
    displayOrder: 71
  },
  {
    id: 3772,
    vendorId: 35,
    categoryId: 8,
    name: 'Fried Mushroom',
    description: 'Crunchy golden batter-fried button mushrooms seasoned with chaat masala',
    price: '130.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mushroom', 'fried mushroom', 'crispy'],
    displayOrder: 72
  },
  {
    id: 3773,
    vendorId: 35,
    categoryId: 8,
    name: 'Bread Aalu Toast',
    description: 'Homestyle crispy pan-toasted bread stuffed with spiced potato mash',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['toast', 'bread aalu toast', 'breakfast'],
    displayOrder: 73
  },
  {
    id: 3774,
    vendorId: 35,
    categoryId: 8,
    name: 'Fresh Poha',
    description: 'Steamed flattened rice tempered with mustard seeds, curry leaves, peanuts and fresh coriander',
    price: '90.00',
    isVeg: true,
    isAvailable: true,
    tags: ['poha', 'breakfast', 'healthy'],
    displayOrder: 74
  },
  {
    id: 3775,
    vendorId: 35,
    categoryId: 8,
    name: 'Soyabeen Popcorn',
    description: 'Bite-sized ultra-crispy seasoned soya popcorn nuggets',
    price: '150.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soya popcorn', 'crispy', 'snacks'],
    displayOrder: 75
  },
  {
    id: 3776,
    vendorId: 35,
    categoryId: 8,
    name: 'Masala Chaap Dry',
    description: 'Spicy marinated dry soya chaap roasted with capsicum and onions',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chaap', 'masala chaap', 'tandoori'],
    displayOrder: 76
  },
  {
    id: 3777,
    vendorId: 35,
    categoryId: 8,
    name: 'Malai Chaap Dry',
    description: 'Creamy cashew and cream marinated soya chaap grilled to succulent perfection',
    price: '200.00',
    isVeg: true,
    isAvailable: true,
    tags: ['malai chaap', 'soya chaap', 'creamy'],
    displayOrder: 77
  },
  {
    id: 3778,
    vendorId: 35,
    categoryId: 8,
    name: 'Masala Maggi',
    description: 'Classic comfort 2-minute noodles cooked with fragrant Maggi tastemaker and spices',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'masala maggi', 'noodles'],
    displayOrder: 78
  },
  {
    id: 3779,
    vendorId: 35,
    categoryId: 8,
    name: 'Garlic Maggi',
    description: 'Flavor-packed instant noodles cooked with roasted garlic butter and herbs',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'garlic maggi'],
    displayOrder: 79
  },
  {
    id: 3780,
    vendorId: 35,
    categoryId: 8,
    name: 'Mushroom Maggi Masala',
    description: 'Comforting Maggi noodles sautéed with tender fresh mushrooms and green chillies',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'mushroom maggi'],
    displayOrder: 80
  },
  {
    id: 3781,
    vendorId: 35,
    categoryId: 8,
    name: 'Paneer Maggi Masala',
    description: 'Loaded Maggi noodles enriched with succulent paneer cubes and veggies',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['maggi', 'paneer maggi'],
    displayOrder: 81
  },
  {
    id: 3782,
    vendorId: 35,
    categoryId: 8,
    name: 'Soya Bhurji Snack',
    description: 'Dry pan-fried soya mince tossed with onions, green chillies and lemon',
    price: '130.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soya bhurji', 'snacks', 'protein'],
    displayOrder: 82
  },

  // ================= 🧋 SHAKES, BEVERAGES, CHAI & SOUPS (Category 3) =================
  {
    id: 3783,
    vendorId: 35,
    categoryId: 3,
    name: 'Cold Coffee',
    description: 'Rich, thick chilled blended coffee with creamy chocolate drizzle (Half: ₹70 / Full: ₹120)',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['coffee', 'cold coffee', 'beverage', 'bestseller'],
    displayOrder: 83
  },
  {
    id: 3784,
    vendorId: 35,
    categoryId: 3,
    name: 'Oreo Shake',
    description: 'Thick creamy milkshake blended with crunchy Oreo cookies and chocolate syrup (Half: ₹80 / Full: ₹120)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'oreo shake', 'beverage'],
    displayOrder: 84
  },
  {
    id: 3785,
    vendorId: 35,
    categoryId: 3,
    name: 'Strawberry Shake',
    description: 'Chilled sweet strawberry milkshake blended with vanilla ice cream (Half: ₹80 / Full: ₹120)',
    price: '80.00',
    isVeg: true,
    isAvailable: true,
    tags: ['shake', 'strawberry shake'],
    displayOrder: 85
  },
  {
    id: 3786,
    vendorId: 35,
    categoryId: 3,
    name: 'Hot Coffee',
    description: 'Steaming hot freshly frothed espresso milk coffee',
    price: '50.00',
    isVeg: true,
    isAvailable: true,
    tags: ['coffee', 'hot coffee', 'beverage'],
    displayOrder: 86
  },
  {
    id: 3787,
    vendorId: 35,
    categoryId: 3,
    name: 'Spl. Tea',
    description: 'Special kadak masala chai brewed with fresh ginger and cardamom',
    price: '20.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tea', 'chai', 'spl tea'],
    displayOrder: 87
  },
  {
    id: 3788,
    vendorId: 35,
    categoryId: 3,
    name: 'Lemon Grass Tea',
    description: 'Refreshing herbal tea infused with fresh fragrant lemon grass stalks',
    price: '25.00',
    isVeg: true,
    isAvailable: true,
    tags: ['tea', 'lemon grass tea', 'herbal tea'],
    displayOrder: 88
  },
  {
    id: 3789,
    vendorId: 35,
    categoryId: 3,
    name: 'Dudh Patti',
    description: 'Strong authentic milk-boiled desi dudh patti chai without added water',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['chai', 'dudh patti', 'tea'],
    displayOrder: 89
  },
  {
    id: 3790,
    vendorId: 35,
    categoryId: 3,
    name: 'Lemon Soda',
    description: 'Fizzy carbonated soda with freshly squeezed lime juice and rock salt',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soda', 'lemon soda', 'beverage'],
    displayOrder: 90
  },
  {
    id: 3791,
    vendorId: 35,
    categoryId: 3,
    name: 'Nimbu Paani',
    description: 'Chilled refreshing homemade sweet and salted lemonade',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['nimbu paani', 'lemonade', 'cooler'],
    displayOrder: 91
  },
  {
    id: 3792,
    vendorId: 35,
    categoryId: 3,
    name: 'Sweet Lassi',
    description: 'Traditional Punjabi thick sweetened yogurt drink with malai topping',
    price: '40.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lassi', 'sweet lassi'],
    displayOrder: 92
  },
  {
    id: 3793,
    vendorId: 35,
    categoryId: 3,
    name: 'Namkeen Lassi',
    description: 'Cool spiced buttermilk lassi with roasted cumin and mint',
    price: '30.00',
    isVeg: true,
    isAvailable: true,
    tags: ['lassi', 'namkeen lassi', 'chaas'],
    displayOrder: 93
  },
  {
    id: 3794,
    vendorId: 35,
    categoryId: 3,
    name: 'Virgin Mojito',
    description: 'Zesty sparkling mocktail muddled with fresh mint sprigs, lime slices and crushed ice',
    price: '60.00',
    isVeg: true,
    isAvailable: true,
    tags: ['mojito', 'mocktail', 'cooler'],
    displayOrder: 94
  },
  {
    id: 3795,
    vendorId: 35,
    categoryId: 3,
    name: 'Tomato Soup',
    description: 'Hot rich and velvety roasted tomato soup served with crispy croutons',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soup', 'tomato soup'],
    displayOrder: 95
  },
  {
    id: 3796,
    vendorId: 35,
    categoryId: 3,
    name: 'Vegetable Soup',
    description: 'Warm healthy clear broth packed with finely diced mixed vegetables and black pepper',
    price: '70.00',
    isVeg: true,
    isAvailable: true,
    tags: ['soup', 'vegetable soup', 'healthy'],
    displayOrder: 96
  }
];
