version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: nitkkr-meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
    volumes:
      - meilisearch_data:/meili_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  meilisearch_data: